"""Generate the Ark Lightning-bridge image build context (``generated/ark-cln/``).

The Ark ASP (Second's ``captaind``) bridges Ark to Lightning through a Core
Lightning node running the Boltz **hold-invoice** plugin. No published image
bundles CLN + that plugin, so — like the cashu.me wallet — Argus builds it from
source into a self-contained context (a Dockerfile plus the CLN start script).
The start script is Second's own (``contrib/docker`` in
``gitlab.com/ark-bitcoin/bark``), reproduced verbatim; the Dockerfile is a
slimmed **multi-stage** adaptation of theirs (theirs is single-stage and ships
the whole Rust toolchain — ~7 GB; this compiles the plugin in a throwaway stage
and keeps only the binary). Both pin ``elementsproject/lightningd`` and the Boltz
``hold`` plugin at the versions captaind's published image expects, generate the
gRPC + hold mTLS certs captaind connects with, and listen on the ports captaind's
config points at (CLN gRPC 9736, hold gRPC 9988, P2P 9735).

One build context is shared by every network — the per-network ``cln`` services
all tag the same ``argus-ark-cln:local`` image, so it is built once and reused.
Each network still runs its own CLN container (its certs/keys/channels stay
isolated per compose project). See :mod:`argus.builders.ark`.
"""

from __future__ import annotations

from pathlib import Path

from .config import ArgusConfig
from .constants import NETWORK_SPECS

# The shared image tag every per-network Ark CLN bridge service builds/uses.
ARK_CLN_IMAGE = "argus-ark-cln:local"


def ark_enabled_anywhere(cfg: ArgusConfig) -> bool:
    """True when any enabled network runs the Ark ASP (so the bridge is needed)."""
    return any(
        net.ark_enabled(NETWORK_SPECS[k]) for k, net in cfg.enabled_networks()
    )


# A multi-stage build of Second's CLN bridge image: their contrib/docker
# cln.Dockerfile is single-stage and ships the whole Rust toolchain + build tree
# (~7 GB), which is wasteful to build, store, and ship to each host. We compile
# the Boltz hold plugin in a throwaway builder stage and copy ONLY the resulting
# binary (kept at /hold/target/debug/hold, the path cln_start.sh references) into
# a clean lightningd runtime — same behaviour, a few hundred MB instead of ~7 GB.
# Pins match upstream: lightningd v26.04.1, Rust 1.90, hold v0.3.3.
def _dockerfile() -> str:
    return (
        "# Generated by Bitcoin Argus — the Ark Lightning-bridge image\n"
        "# (Core Lightning + the Boltz hold-invoice plugin). Multi-stage build of\n"
        "# Second's contrib/docker/cln.Dockerfile (gitlab.com/ark-bitcoin/bark),\n"
        "# slimmed so only the compiled plugin (not the Rust toolchain) ships.\n"
        "\n"
        "# Stage 1: compile the Boltz hold-invoice plugin.\n"
        "FROM docker.io/elementsproject/lightningd:v26.04.1 AS build\n"
        "ENV RUST_BACKTRACE=1 \\\n"
        "\tRUSTUP_TOOLCHAIN_VERSION=1.90 \\\n"
        "\tPATH=/root/.cargo/bin:${PATH}\n"
        "RUN apt-get update && apt-get install -y --no-install-recommends \\\n"
        "\tbuild-essential git curl gcc clang libpq-dev libsqlite3-dev \\\n"
        "\tprotobuf-compiler ca-certificates\n"
        "RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- "
        "-y --default-toolchain none\n"
        "RUN rustup toolchain install ${RUSTUP_TOOLCHAIN_VERSION}\n"
        "RUN git clone https://github.com/BoltzExchange/hold.git && \\\n"
        "\tcd hold && git checkout v0.3.3 && cargo build && \\\n"
        "\tchmod a+x /hold/target/debug/hold\n"
        "\n"
        "# Stage 2: runtime — lightningd + the hold plugin only.\n"
        "FROM docker.io/elementsproject/lightningd:v26.04.1\n"
        "# Runtime libs the hold plugin links (libpq/sqlite) + openssl (cln_start.sh\n"
        "# regenerates the gRPC/hold TLS certs) + dos2unix (normalise the script).\n"
        "RUN apt-get update && apt-get install -y --no-install-recommends \\\n"
        "\topenssl libpq5 libsqlite3-0 dos2unix \\\n"
        "\t&& rm -rf /var/lib/apt/lists/*\n"
        "COPY --from=build /hold/target/debug/hold /hold/target/debug/hold\n"
        "RUN mkdir -p /root/cln/\n"
        "ADD ./cln_start.sh /root/cln/start.sh\n"
        "RUN chmod a+x /root/cln/start.sh && dos2unix /root/cln/start.sh\n"
        "\n"
        "EXPOSE 9735\n"
        "EXPOSE 9736\n"
        "EXPOSE 9988\n"
    )


# Second's contrib/docker/cln_start.sh, verbatim. Raw string so the shell `\`
# line-continuations and `$` references are preserved exactly. Boots lightningd
# with the hold plugin + gRPC, then on first run regenerates the CLN/hold server
# certs with a SAN matching the container hostname (so captaind's TLS to
# ``cln:9736`` / ``cln:9988`` verifies) and reboots. We keep the container's
# hostname ``cln`` (set in the builder) so the default-cert path is taken.
def _cln_start_sh() -> str:
    return r"""#!/bin/sh
set -e

HOSTNAME=$(hostname -s)
echo "Running CLN start command on host: ${HOSTNAME}"

echo "Using:"
export NETWORK=${NETWORK:=regtest}
echo " - network: ${NETWORK}"
export CLN_ALIAS=${CLN_ALIAS:=second.tech-${HOSTNAME}}
echo " - alias: ${CLN_ALIAS}"
export CLN_LOG_LEVEL=${CLN_LOG_LEVEL:=debug}
echo " - log.level: ${CLN_LOG_LEVEL}"
export CLN_GRPC_PORT=${CLN_GRPC_PORT:=9736}
echo " - grpc.port: ${CLN_GRPC_PORT}"
export CLN_GRPC_HOST=${CLN_GRPC_HOST:=0.0.0.0}
echo " - grpc.host: ${CLN_GRPC_HOST}"
export GRPC_PORT_HOLD=${HOLD_GRPC_PORT:=9988}
echo " - hold.gprc.port: ${HOLD_GRPC_PORT}"
export HOLD_GRPC_HOST=${HOLD_GRPC_HOST:=0.0.0.0}
echo " - hold.grpc.host: ${HOLD_GRPC_HOST}"
export BITCOIN_RPCCONNECT=${BITCOIN_RPCCONNECT:=bitcoind:18443}
echo " - bitcoin.rpcconnect: ${BITCOIN_RPCCONNECT}"
export BITCOIN_RPCUSER=${BITCOIN_RPCUSER:=second}
echo " - bitcoin.rpcuser: ${BITCOIN_RPCUSER}"
export BITCOIN_RPCPASSWORD=${BITCOIN_RPCPASSWORD:=ark}
echo " - bitcoin.rpcpassword: ***"
export CLN_BIND_ADDR=${CLN_BIND_ADDR:=0.0.0.0:9735}
echo " - bind.addr: ${CLN_BIND_ADDR}"

if [ -n "${CLN_ANNOUNCE_ADDR}" ]; then
    echo " - announce.addr: ${CLN_ANNOUNCE_ADDR}"
    ANNOUNCE_ARG="--announce-addr=${CLN_ANNOUNCE_ADDR}"
else
    echo " - announce.addr: (not set)"
    ANNOUNCE_ARG=""
fi
if [ -n "${CLN_WALLET_DB}" ]; then
    echo " - wallet-db: ${CLN_WALLET_DB}"
    WALLET_ARG="--wallet=${CLN_WALLET_DB}"
else
    echo " - wallet-db: (not set)"
    WALLET_ARG=""
fi
if [ -n "${CLN_BOOKKEEPER_DB}" ]; then
    echo " - bookkeeper-db: ${CLN_BOOKKEEPER_DB}"
    BOOKKEEPER_ARG="--bookkeeper-db=${CLN_BOOKKEEPER_DB}"
else
    echo " - bookkeeper-db: (not set)"
    BOOKKEEPER_ARG=""
fi


echo "Booting"
lightningd --${NETWORK} --alias="${CLN_ALIAS}" --log-level=${CLN_LOG_LEVEL} \
	--grpc-port=${CLN_GRPC_PORT} --grpc-host=${CLN_GRPC_HOST} \
	--bitcoin-rpcconnect=${BITCOIN_RPCCONNECT} --bitcoin-rpcuser=${BITCOIN_RPCUSER} --bitcoin-rpcpassword=${BITCOIN_RPCPASSWORD} \
	--important-plugin=/hold/target/debug/hold --hold-grpc-host=${HOLD_GRPC_HOST} --hold-grpc-port=${HOLD_GRPC_PORT} \
	--bind-addr=${CLN_BIND_ADDR} ${ANNOUNCE_ARG} ${WALLET_ARG} ${BOOKKEEPER_ARG} &
LIGHTNINGD_PID=$!

WAIT_FILE="/root/.lightning/${NETWORK}/hold/ca.pem"
GEN_MARKER="/root/.lightning/${NETWORK}/hold/generation.done"

echo "Waiting for ${WAIT_FILE}..."
while [ ! -f "${WAIT_FILE}" ]; do
	sleep 1s
done

echo "Found file ${WAIT_FILE}"
if [ ! -f "${GEN_MARKER}" ]; then
	cat > /root/.lightning/${NETWORK}/v3.ext <<EOF
[v3_req]
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = ${HOSTNAME}
DNS.2 = localhost
IP.1 = 127.0.0.1
EOF

	if [ "${HOSTNAME}" != "cln" ]; then
		rm /root/.lightning/${NETWORK}/server-key.pem
		rm /root/.lightning/${NETWORK}/server.pem
		echo "Generating custom CLN server certificate..."
		openssl ecparam -name prime256v1 -genkey -noout -out /root/.lightning/${NETWORK}/server-key.pem
		openssl req \
			-key /root/.lightning/${NETWORK}/server-key.pem -new \
			-out /root/.lightning/${NETWORK}/server.csr \
			-subj "/C=US/ST=California/L=SanFrancisco/O=Second/OU=Dev/CN=${HOSTNAME}"
		openssl x509 -req \
			-CA /root/.lightning/${NETWORK}/ca.pem -CAkey /root/.lightning/${NETWORK}/ca-key.pem \
			-in /root/.lightning/${NETWORK}/server.csr \
			-out /root/.lightning/${NETWORK}/server.pem \
			-days 3650 -CAcreateserial \
			-extfile /root/.lightning/${NETWORK}/v3.ext -extensions v3_req

		openssl x509 -in /root/.lightning/${NETWORK}/server.pem -text -noout
		openssl verify -CAfile /root/.lightning/${NETWORK}/ca.pem /root/.lightning/${NETWORK}/server.pem
	fi

	rm /root/.lightning/${NETWORK}/hold/server-key.pem
	rm /root/.lightning/${NETWORK}/hold/server.pem
	echo "Generating custom HOLD server certificate..."
	openssl ecparam -name prime256v1 -genkey -noout -out /root/.lightning/${NETWORK}/hold/server-key.pem
	openssl req \
		-key /root/.lightning/${NETWORK}/hold/server-key.pem -new \
		-out /root/.lightning/${NETWORK}/hold/server.csr \
		-subj "/C=US/ST=California/L=SanFrancisco/O=Second/OU=Dev/CN=${HOSTNAME}"
	openssl x509 -req \
		-CA /root/.lightning/${NETWORK}/hold/ca.pem -CAkey /root/.lightning/${NETWORK}/hold/ca-key.pem \
		-in /root/.lightning/${NETWORK}/hold/server.csr \
		-out /root/.lightning/${NETWORK}/hold/server.pem \
		-days 3650 -CAcreateserial \
		-extfile /root/.lightning/${NETWORK}/v3.ext -extensions v3_req

	openssl x509 -in /root/.lightning/${NETWORK}/hold/server.pem -text -noout
	openssl verify -CAfile /root/.lightning/${NETWORK}/hold/ca.pem /root/.lightning/${NETWORK}/hold/server.pem

	touch "${GEN_MARKER}"

	echo "Generation done rebooting"
	kill ${LIGHTNINGD_PID} || echo "Warning: lightningd might have exited before kill"
	sleep 1s

	echo "Booting"
	lightningd --${NETWORK} --alias="${CLN_ALIAS}" --log-level=${CLN_LOG_LEVEL} \
		--grpc-port=${CLN_GRPC_PORT} --grpc-host=${CLN_GRPC_HOST} \
		--bitcoin-rpcconnect=${BITCOIN_RPCCONNECT} --bitcoin-rpcuser=${BITCOIN_RPCUSER} --bitcoin-rpcpassword=${BITCOIN_RPCPASSWORD} \
		--important-plugin=/hold/target/debug/hold --hold-grpc-host=${HOLD_GRPC_HOST} --hold-grpc-port=${HOLD_GRPC_PORT} \
		--bind-addr=${CLN_BIND_ADDR} ${ANNOUNCE_ARG} ${WALLET_ARG} ${BOOKKEEPER_ARG}
else
	wait ${LIGHTNINGD_PID}
fi
"""


def generate_ark_cln(cfg: ArgusConfig, output_dir: Path) -> Path | None:
    """Write ``generated/ark-cln/`` (the shared build context). Returns its dir,
    or None when no enabled network runs the Ark ASP."""
    if not ark_enabled_anywhere(cfg):
        return None

    out_dir = output_dir / "ark-cln"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "Dockerfile").write_text(_dockerfile())
    (out_dir / "cln_start.sh").write_text(_cln_start_sh())
    return out_dir
