"""Generate the per-network Bitcart deployment (env file + wrapper script).

Bitcart is deployed by the BareBits installer (deploy_bitcart_liquidity_lnd),
not as part of our compose project. Argus generates, per network with Bitcart
enabled:

  generated/<net>/bitcart/bitcart.env       -- env consumed by deploy.sh
  generated/<net>/bitcart/deploy-bitcart.sh -- wrapper run on the host

The wrapper clones the installer, sources the env, runs deploy.sh in its
multi-instance mode (DEPLOY_NAME), then attaches the btclnd container to this
network's docker network so its Neutrino LND syncs against our bitcoind. The
shared Caddy fronts the store/admin/api ports (see argus.shared).
"""

from __future__ import annotations

from pathlib import Path

from .config import ArgusConfig
from .constants import (
    BITCART_BTCLND_GRPC_OFFSET,
    BITCART_BTCLND_P2P_OFFSET,
    CHAIN_INTERNAL_PORTS,
    LND_NETWORK_KEY,
    NETWORK_SPECS,
)
from .ports import block_base

_DEPLOY_REPO = "https://github.com/BareBits/deploy_bitcart_liquidity_lnd.git"


def _bool_env(value: bool, *, upper: bool = False) -> str:
    s = "True" if value else "False"
    return s.upper() if upper else s


def _env_lines(
    cfg: ArgusConfig,
    net_key: str,
    ports: dict[str, int],
    secrets: dict[str, str],
) -> dict[str, str]:
    g = cfg.global_
    net = cfg.networks[net_key]
    spec = NETWORK_SPECS[net_key]
    bc = net.bitcart
    base = block_base(net_key)

    scheme = "https" if (g.ssl_enabled and bc.ssl) else "http"
    api_url = f"{scheme}://{g.hostname}:{ports['bitcart_api_public']}"
    challenge = net.signet_challenge or spec.default_signet_challenge

    # Raw lnd args for the Neutrino LND: a custom signet needs its challenge.
    extra_args = []
    if spec.is_signet and challenge and net_key != "signet":
        extra_args.append(f"--bitcoin.signetchallenge={challenge}")

    env: dict[str, str] = {
        # multi-instance + external-proxy mode (see deploy.sh DEPLOY_NAME)
        "DEPLOY_NAME": f"argus-bitcart-{net_key}",
        "BRANCH": bc.branch,
        "BITCART_REVERSEPROXY": "none",
        "BITCART_HOST": g.hostname,
        "BITCART_ADMIN_EMAIL": bc.admin_email or "",
        "BITCART_ADMIN_PASSWORD": secrets["BITCART_ADMIN_PASSWORD"],
        "CASHOUT_LIGHTNING_ADDRESS": bc.liquidity.cashout_lightning_address or "",
        # component ports (bind to these; the shared Caddy fronts the public ones)
        "BITCART_STORE_PORT": str(ports["bitcart_store"]),
        "BITCART_ADMIN_PORT": str(ports["bitcart_admin"]),
        "BITCART_BACKEND_PORT": str(ports["bitcart_api"]),
        "BITCART_ADMIN_API_URL": api_url,
        "BITCART_STORE_API_URL": api_url,
        # btclnd (Neutrino LND) — synced against our bitcoind
        "BTCLND_NETWORK": LND_NETWORK_KEY[spec.chain],
        "BTCLND_DEBUG": _bool_env(bc.btclnd_debug).lower(),
        "BTCLND_NEUTRINO_PEERS": f"bitcoind:{CHAIN_INTERNAL_PORTS[spec.chain]['p2p']}",
        "BTCLND_BASE_P2P_PORT": str(base + BITCART_BTCLND_P2P_OFFSET),
        "BTCLND_BASE_GRPC_PORT": str(base + BITCART_BTCLND_GRPC_OFFSET),
        "BTCLND_P2P_POOL_SIZE": str(bc.btclnd_p2p_pool_size),
        # liquidity-helper plugin
        "LIQUIDITYHELPER_LIQUIDITY_DISABLED": _bool_env(bc.liquidity.disabled),
        "LIQUIDITYHELPER_AUTOMATIC_CHANNEL_CREATION_ENABLED": _bool_env(
            bc.liquidity.automatic_channel_creation
        ),
        "LIQUIDITYHELPER_LOG_LEVEL": bc.liquidity.log_level,
    }
    if extra_args:
        env["BTCLND_LND_EXTRA_ARGS"] = " ".join(extra_args)

    # Optional installation-wide SMTP (password is operator-supplied via secrets).
    if bc.smtp.server:
        env.update(
            {
                "BITCART_SMTP_SERVER": bc.smtp.server,
                "BITCART_SMTP_PORT": str(bc.smtp.port),
                "BITCART_SMTP_TLS": _bool_env(bc.smtp.tls, upper=True),
                "BITCART_SMTP_SSL": _bool_env(bc.smtp.ssl, upper=True),
                "BITCART_SMTP_USERNAME": bc.smtp.username or "",
                "BITCART_SMTP_FROM_EMAIL": bc.smtp.from_email or bc.smtp.username or "",
            }
        )
        if secrets.get("BITCART_SMTP_PASSWORD"):
            env["BITCART_SMTP_PASSWORD"] = secrets["BITCART_SMTP_PASSWORD"]

    env.update(bc.extra_env)  # operator overrides win
    return env


_WRAPPER = """\
#!/usr/bin/env bash
# Generated by Bitcoin Argus — deploy Bitcart for the '{net}' network.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
NET="{net}"
DEPLOY_NAME="argus-bitcart-$NET"
ARGUS_NET="argus-$NET-net"
REPO_DIR="${{ARGUS_BITCART_DEPLOY_DIR:-/opt/argus/bitcart-deploy}}"

# Export all deploy env.
set -a; . "$HERE/bitcart.env"; set +a

# Fetch the BareBits installer (branch from BRANCH).
if [ ! -d "$REPO_DIR/.git" ]; then
    git clone -b "${{BRANCH:-main}}" {repo} "$REPO_DIR"
fi
cd "$REPO_DIR"

# Deploy this instance (multi-instance mode via DEPLOY_NAME, external proxy).
./deploy.sh

# Wire btclnd's Neutrino LND to our bitcoind: join our network, then restart so
# it re-resolves the BTCLND_NEUTRINO_PEERS host (bitcoind) on that network.
BTCLND_CT="$DEPLOY_NAME-btclnd-1"
docker network connect "$ARGUS_NET" "$BTCLND_CT" 2>/dev/null || true
docker restart "$BTCLND_CT" >/dev/null 2>&1 || true

echo "Bitcart [$NET] deployed; btclnd attached to $ARGUS_NET."
"""


def generate_bitcart(
    cfg: ArgusConfig,
    net_key: str,
    ports: dict[str, int],
    secrets: dict[str, str],
    output_dir: Path,
) -> Path | None:
    """Generate the Bitcart env + wrapper for one network. Returns its dir."""
    if not cfg.networks[net_key].bitcart.enabled:
        return None

    out_dir = output_dir / net_key / "bitcart"
    out_dir.mkdir(parents=True, exist_ok=True)

    env = _env_lines(cfg, net_key, ports, secrets)
    env_body = "".join(f"{k}={v}\n" for k, v in env.items())
    env_path = out_dir / "bitcart.env"
    env_path.write_text(env_body)
    env_path.chmod(0o600)  # contains admin/SMTP credentials

    script_path = out_dir / "deploy-bitcart.sh"
    script_path.write_text(_WRAPPER.format(net=net_key, repo=_DEPLOY_REPO))
    script_path.chmod(0o755)
    return out_dir
