"""Generate the cashu.me web-wallet build context (``generated/cashu-wallet/``).

cashu.me has no official published image, so Argus builds it from source. Like
the dashboard, the output is a self-contained build context (a Dockerfile plus an
nginx config) that the per-network ``cashu-wallet`` services point their
``build.context`` at. The wallet is a static PWA: stage one clones cashu.me at a
pinned ref and builds the PWA, stage two serves the static bundle with nginx.

One build context is shared by every network — the per-network services all tag
the same ``argus-cashu-wallet:local`` image, so it is built once and reused. Each
network still runs its own container on its own public port, so a browser sees a
distinct origin per network and wallet state never bleeds across networks.
"""

from __future__ import annotations

from pathlib import Path

from .config import ArgusConfig

# The shared image tag every per-network cashu-wallet service builds/uses.
CASHU_WALLET_IMAGE = "argus-cashu-wallet:local"

# Defaults for the base images the build uses; baked as ARG defaults so the build
# context is self-contained, while the source ref is injected from config.
_NODE_IMAGE = "node:24"
_NGINX_IMAGE = "nginx:stable"


def wallet_enabled(cfg: ArgusConfig) -> bool:
    """True when any enabled network runs a mint with its web wallet on."""
    return any(
        net.cashu.enabled and net.cashu.wallet for _k, net in cfg.enabled_networks()
    )


def _dockerfile() -> str:
    return (
        "# Generated by Bitcoin Argus — the cashu.me web-wallet image.\n"
        "# Global build ARGs (declared before any FROM so both stages' FROM lines\n"
        "# can resolve them).\n"
        f"ARG NODE_IMAGE={_NODE_IMAGE}\n"
        f"ARG NGINX_IMAGE={_NGINX_IMAGE}\n"
        "\n"
        "# Stage 1: build the cashu.me PWA from a pinned source ref.\n"
        "FROM ${NODE_IMAGE} AS build\n"
        "# The cashu.me git ref (commit SHA or tag) to build; injected from\n"
        "# global.cashu_wallet_ref so the wallet version is pinned + reproducible.\n"
        "ARG CASHU_WALLET_REF\n"
        "WORKDIR /app\n"
        "RUN git clone https://github.com/cashubtc/cashu.me . \\\n"
        '    && git checkout "${CASHU_WALLET_REF}" \\\n'
        "    && npm ci \\\n"
        "    && npm run build:pwa\n"
        "\n"
        "# Stage 2: serve the static PWA bundle.\n"
        "FROM ${NGINX_IMAGE}\n"
        "COPY nginx.conf /etc/nginx/conf.d/default.conf\n"
        "COPY --from=build /app/dist/pwa /usr/share/nginx/html\n"
        "EXPOSE 80\n"
    )


def _nginx_conf() -> str:
    # SPA history-mode fallback so deep links resolve to index.html, and the
    # service-worker scope header the PWA needs. The wallet is served at the root
    # of its own port, so all asset paths resolve from "/".
    return (
        "server {\n"
        "    listen 80;\n"
        "    server_name _;\n"
        "    root /usr/share/nginx/html;\n"
        "    index index.html;\n"
        "\n"
        "    location / {\n"
        "        try_files $uri $uri/ /index.html;\n"
        '        add_header Service-Worker-Allowed "/";\n'
        "    }\n"
        "}\n"
    )


def generate_cashu_wallet(cfg: ArgusConfig, output_dir: Path) -> Path | None:
    """Write ``generated/cashu-wallet/`` (the shared build context). Returns its
    dir, or None when no network needs the wallet."""
    if not wallet_enabled(cfg):
        return None

    out_dir = output_dir / "cashu-wallet"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "Dockerfile").write_text(_dockerfile())
    (out_dir / "nginx.conf").write_text(_nginx_conf())
    return out_dir
