"""Generate the CashuPayServer build context (``generated/cashupayserver/``).

CashuPayServer (the BareBits Lite fork) is a PHP app with no published image, so
Argus builds it from source — like the cashu.me wallet and the dashboard, the
output is a self-contained build context (a Dockerfile that clones the fork at a
pinned ref) plus a CLI **seed script** baked into the image.

The seed script provisions the server non-interactively (its browser setup wizard
can't be scripted): it loads the app's own ``Database``/``Config``/``Auth``
classes and, idempotently, sets the admin password, creates a store wired to this
network's Cashu mint with submarine swaps disabled, and mints a Greenfield API
key for the WooCommerce BTCPay plugin — writing the key + store id to a small
pairing file on a shared volume. See :mod:`argus.builders.cashupayserver` for the
per-network services that run the image and the init step.

One build context is shared by every network (each per-network service tags the
same ``argus-cashupayserver:local`` image), so it is built once and reused; each
network still runs its own container with its own SQLite data volume.
"""

from __future__ import annotations

from pathlib import Path

from .config import ArgusConfig

# The shared image tag every per-network cashupayserver service builds/uses.
CASHUPAYSERVER_IMAGE = "argus-cashupayserver:local"

# The fork Argus builds. Pinned to a ref via global.cashupayserver_ref.
CASHUPAYSERVER_REPO = "https://github.com/BareBits/cashupayserver.git"

# Where the app lives in the image (php:apache docroot) and where the seed script
# is staged (outside the docroot, so it is never HTTP-reachable).
_APP_ROOT = "/var/www/html"
_SEED_PATH = "/opt/argus/seed-cashupay.php"

# Base image baked as an ARG default so the build context stays self-contained.
_PHP_IMAGE = "php:8.3-apache"


def cashupayserver_enabled(cfg: ArgusConfig) -> bool:
    """True when any enabled network runs CashuPayServer."""
    return any(net.cashupayserver.enabled for _k, net in cfg.enabled_networks())


def _dockerfile() -> str:
    return (
        "# Generated by Bitcoin Argus — the CashuPayServer (BareBits Lite) image.\n"
        f"ARG PHP_IMAGE={_PHP_IMAGE}\n"
        "FROM ${PHP_IMAGE}\n"
        "# The github.com/BareBits/cashupayserver git ref (commit SHA or tag) to\n"
        "# build; injected from global.cashupayserver_ref so it is pinned.\n"
        "ARG CASHUPAYSERVER_REF=main\n"
        f"ARG CASHUPAYSERVER_REPO={CASHUPAYSERVER_REPO}\n"
        "\n"
        "# PHP extensions the app + bundled cashu-wallet-php need (SQLite store,\n"
        "# big-int math for secp256k1, zip/curl/mbstring), plus Apache rewrite.\n"
        "RUN apt-get update \\\n"
        "    && apt-get install -y --no-install-recommends \\\n"
        "        git unzip libgmp-dev libzip-dev \\\n"
        "    && docker-php-ext-install pdo pdo_sqlite gmp bcmath zip \\\n"
        "    && a2enmod rewrite \\\n"
        "    && rm -rf /var/lib/apt/lists/*\n"
        "COPY --from=composer:2 /usr/bin/composer /usr/bin/composer\n"
        "\n"
        "# Honour the app's .htaccess (clean URLs / sensitive-dir blocks).\n"
        "RUN printf '<Directory %s>\\n    AllowOverride All\\n    "
        "Require all granted\\n</Directory>\\n' \"$APP_ROOT\" \\\n"
        "        > /etc/apache2/conf-available/cashupay.conf \\\n"
        "    && a2enconf cashupay\n"
        "\n"
        f"WORKDIR {_APP_ROOT}\n"
        "# Clone at the pinned ref (checkout supports a commit SHA or a tag),\n"
        "# including the cashu-wallet-php / mint-discovery submodules.\n"
        "RUN git clone \"${CASHUPAYSERVER_REPO}\" . \\\n"
        "    && git checkout \"${CASHUPAYSERVER_REF}\" \\\n"
        "    && git submodule update --init --recursive \\\n"
        "    && composer install --no-dev --no-interaction --optimize-autoloader \\\n"
        "        --no-progress 2>/dev/null || true\n"
        "\n"
        "# The SQLite data dir is a runtime volume; keep the tree writable by the\n"
        "# web user. The seed script lives OUTSIDE the docroot (cli-only anyway).\n"
        f"RUN mkdir -p {_APP_ROOT}/data {_APP_ROOT}/api-keys /opt/argus \\\n"
        f"    && chown -R www-data:www-data {_APP_ROOT}\n"
        f"COPY seed-cashupay.php {_SEED_PATH}\n"
    ).replace("$APP_ROOT", _APP_ROOT)


# The non-interactive provisioning script, baked into the image and run by the
# per-network ``cashupayserver-init`` service. It is CLI-only and idempotent.
_SEED_PHP = r"""<?php
/**
 * Generated by Bitcoin Argus — non-interactive CashuPayServer provisioning.
 *
 * Replaces the browser setup wizard: loads the app's own classes and seeds the
 * admin user, a store wired to this network's Cashu mint (submarine swaps off),
 * and a Greenfield API key for the WooCommerce BTCPay plugin. Idempotent: safe to
 * re-run on every `docker compose up`. CLI only.
 *
 * Config comes from the environment (see argus/builders/cashupayserver.py):
 *   CASHUPAY_ADMIN_PASSWORD   admin login password (required)
 *   CASHUPAY_MINT_URL         this network's mint, e.g. http://cashu:3338 (required)
 *   CASHUPAY_MINT_UNIT        mint unit (default "sat")
 *   CASHUPAY_STORE_NAME       store display name
 *   CASHUPAY_BASE_URL         public base URL of this CashuPayServer
 *   CASHUPAY_SUBMARINE_SWAPS  "1" to enable swaps, "0" to disable (default "0")
 *   CASHUPAY_PAIRING_FILE     where to write the WooCommerce pairing JSON
 *   CASHUPAY_API_LABEL        label for the WooCommerce API key (default "woocommerce")
 */

if (php_sapi_name() !== 'cli') {
    http_response_code(403);
    exit("seed-cashupay.php is CLI-only\n");
}

function seed_log(string $m): void { fwrite(STDOUT, "[seed-cashupay] $m\n"); }
function seed_fail(string $m): int { fwrite(STDERR, "[seed-cashupay] ERROR: $m\n"); return 1; }

$root = getenv('CASHUPAY_APP_ROOT') ?: '/var/www/html';
require_once $root . '/includes/database.php';
require_once $root . '/includes/config.php';
require_once $root . '/includes/auth.php';
require_once $root . '/includes/urls.php';

$adminPw   = getenv('CASHUPAY_ADMIN_PASSWORD') ?: '';
$mintUrl   = getenv('CASHUPAY_MINT_URL') ?: '';
$mintUnit  = getenv('CASHUPAY_MINT_UNIT') ?: 'sat';
$storeName = getenv('CASHUPAY_STORE_NAME') ?: 'Argus Store';
$baseUrl   = getenv('CASHUPAY_BASE_URL') ?: '';
$swapsOn   = (getenv('CASHUPAY_SUBMARINE_SWAPS') === '1');
$pairing   = getenv('CASHUPAY_PAIRING_FILE') ?: '/pairing/pairing.json';
$apiLabel  = getenv('CASHUPAY_API_LABEL') ?: 'woocommerce';

if ($adminPw === '' || $mintUrl === '') {
    exit(seed_fail('CASHUPAY_ADMIN_PASSWORD and CASHUPAY_MINT_URL are required'));
}

try {
    if (!Database::isInitialized()) {
        seed_log('initialising database schema...');
        Database::initialize();
    }

    $complete = false;
    try { $complete = Config::isSetupComplete(); } catch (Throwable $e) { $complete = false; }

    if (!$complete) {
        seed_log('first-time setup: admin + store...');
        Auth::setAdminPassword($adminPw);
        if ($baseUrl !== '') {
            Config::set('base_url', $baseUrl);
            Config::set('url_mode', 'path');
        }

        $storeId = Database::generateId('store');
        Database::insert('stores', [
            'id'         => $storeId,
            'name'       => $storeName,
            'created_at' => Database::timestamp(),
        ]);

        // A wallet seed for the store (same generator the wizard uses).
        require_once $root . '/cashu-wallet-php/CashuWallet.php';
        $mnemonic = \Cashu\Mnemonic::generate();

        Database::update('stores', [
            'mint_url'          => $mintUrl,
            'mint_unit'         => $mintUnit,
            'seed_phrase'       => $mnemonic,
            'default_currency'  => 'sat',
            'swaps_enabled'     => $swapsOn ? 1 : 0,
            'auto_melt_use_swap'=> 0,
        ], 'id = ?', [$storeId]);

        // Site-wide swap master toggle (best-effort; the store-level flag already
        // wins for this, the only store, but keep both consistent for the UI).
        Config::set('swaps_enabled', $swapsOn);
        Config::set('submarine_swaps_enabled', $swapsOn);

        Config::set('setup_complete', true);
        seed_log("store created: $storeId");
    } else {
        $store = Database::fetchOne('SELECT id FROM stores ORDER BY created_at ASC LIMIT 1');
        if (!$store) { exit(seed_fail('setup_complete but no store exists')); }
        $storeId = $store['id'];
        // Re-assert the swap state and mint on every run (idempotent).
        Database::update('stores', [
            'swaps_enabled' => $swapsOn ? 1 : 0,
            'mint_url'      => $mintUrl,
            'mint_unit'     => $mintUnit,
        ], 'id = ?', [$storeId]);
        seed_log("using existing store: $storeId");
    }

    // Ensure exactly one WooCommerce API key; reuse the existing pairing when the
    // key it names still exists (raw keys can't be re-derived once created).
    @mkdir(dirname($pairing), 0700, true);
    $needNew = true;
    if (is_file($pairing)) {
        $p = json_decode((string)file_get_contents($pairing), true);
        if (is_array($p) && !empty($p['api_key']) && ($p['store_id'] ?? '') === $storeId) {
            $row = Database::fetchOne(
                'SELECT id FROM api_keys WHERE store_id = ? AND key_hash = ?',
                [$storeId, hash('sha256', $p['api_key'])]
            );
            if ($row) { $needNew = false; seed_log('existing API key still valid; reusing pairing.'); }
        }
    }
    if ($needNew) {
        Database::delete('api_keys', 'store_id = ? AND label = ?', [$storeId, $apiLabel]);
        $perms = [
            'btcpay.store.cancreateinvoice',
            'btcpay.store.canviewinvoices',
            'btcpay.store.canmodifyinvoices',
            'btcpay.store.canviewstoresettings',
            'btcpay.store.webhooks.canmodifywebhooks',
        ];
        $key = Auth::createApiKey($storeId, $apiLabel, $perms);
        $raw = is_array($key) ? ($key['key'] ?? ($key['api_key'] ?? '')) : '';
        if ($raw === '') { exit(seed_fail('createApiKey returned no raw key')); }
        file_put_contents($pairing, json_encode([
            'store_id'   => $storeId,
            'api_key'    => $raw,
            'created_at' => time(),
        ]));
        @chmod($pairing, 0600);
        seed_log('created API key + wrote pairing file.');
    }

    seed_log('done.');
    exit(0);
} catch (Throwable $e) {
    exit(seed_fail($e->getMessage()));
}
"""


def generate_cashupayserver(cfg: ArgusConfig, output_dir: Path) -> Path | None:
    """Write ``generated/cashupayserver/`` (the shared build context). Returns its
    dir, or None when no enabled network runs CashuPayServer."""
    if not cashupayserver_enabled(cfg):
        return None

    out_dir = output_dir / "cashupayserver"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "Dockerfile").write_text(_dockerfile())
    (out_dir / "seed-cashupay.php").write_text(_SEED_PHP)
    return out_dir
