"""Surface operator-facing admin login credentials for the deployed stack.

Today this means the **Bitcart** admin login: Argus auto-generates its password
(:mod:`argus.secrets`) and the BareBits installer bootstraps the first admin
from it on deploy. The Cashu mint runs as an open mint (no login) and so is
intentionally not listed here.

One source of truth feeds both surfaces:

* ``argus credentials`` (CLI) -- prints the table on demand, read-only.
* ``generated/CREDENTIALS.txt`` -- written by ``argus generate`` (mode 0600).

Both READ the persisted ``secrets/<net>/secrets.env`` and never generate a
value, so what is shown always matches what is deployed and stays identical
across rebuilds and storage-cap resets (which leave ``secrets/`` untouched).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .config import ArgusConfig
from .secrets import read_secrets
from .tor import onion_routes

_PENDING = "(pending -- run `argus generate`)"


@dataclass
class Credential:
    """One admin login for one component of one network."""

    network: str
    component: str
    username: str
    password: str | None  # None => not generated yet
    login_url: str | None = None
    # Same login over Tor (http://<onion>:<port>/), when the install runs Tor and
    # this service is exposed on its onion. None => clearnet only.
    onion_url: str | None = None

    @property
    def password_text(self) -> str:
        return self.password if self.password else _PENDING


def _url(cfg: ArgusConfig, service_ssl: bool, port: int) -> str:
    scheme = "https" if (cfg.global_.ssl_enabled and service_ssl) else "http"
    return f"{scheme}://{cfg.global_.hostname}:{port}/"


def build_credentials(
    cfg: ArgusConfig,
    port_map: dict[str, dict[str, int]],
    secrets_dir: Path,
    *,
    only: str | None = None,
    onion_hostname: str | None = None,
) -> list[Credential]:
    """Build the admin-credential rows for every enabled network that has a login.

    ``only`` limits the result to a single network. ``onion_hostname`` adds the
    Tor-equivalent URL for any service exposed on the installation's onion.
    """
    # Onion virtual ports per network (only those actually exposed on Tor).
    onion_ports: dict[str | None, set[int]] = {}
    if onion_hostname:
        for r in onion_routes(cfg, port_map):
            onion_ports.setdefault(r.net_key, set()).add(r.virtual_port)

    creds: list[Credential] = []
    for net_key, net in cfg.enabled_networks():
        if only is not None and net_key != only:
            continue
        if net_key not in port_map:
            continue
        ports = port_map[net_key]
        secrets = read_secrets(net_key, secrets_dir)

        # Bitcart admin -- the only component with a login today. Its password is
        # auto-generated; the admin email comes from config (required when
        # Bitcart is enabled, so never blank here).
        bc = net.bitcart
        if bc.enabled:
            port = ports["bitcart_admin_public"]
            onion = (
                f"http://{onion_hostname}:{port}/"
                if port in onion_ports.get(net_key, set())
                else None
            )
            creds.append(
                Credential(
                    network=net_key,
                    component="Bitcart admin",
                    username=bc.admin_email or "",
                    password=secrets.get("BITCART_ADMIN_PASSWORD"),
                    login_url=_url(cfg, bc.ssl, port),
                    onion_url=onion,
                )
            )
    return creds


_HEADER = """\
# Bitcoin Argus -- admin login credentials
#
# Generated by `argus generate`. Contains LIVE SECRETS -- keep this file private
# (it is mode 0600 and lives under the gitignored generated/ tree; never commit
# it or expose it on the public dashboard).
#
# These credentials are STABLE: they are read from secrets/<net>/secrets.env,
# which `argus generate` never rotates and a storage-cap reset never touches, so
# they stay identical across rebuilds and resets.
"""


def format_credentials(creds: list[Credential]) -> str:
    """Render the credential rows as the text the CLI prints / the file holds."""
    lines = [_HEADER]
    if not creds:
        lines.append("(no admin logins -- Bitcart is not enabled on any network)\n")
        return "\n".join(lines)

    by_net: dict[str, list[Credential]] = {}
    for c in creds:
        by_net.setdefault(c.network, []).append(c)

    for net_key, rows in by_net.items():
        lines.append(f"[{net_key}]")
        for c in rows:
            lines.append(f"  {c.component}")
            if c.login_url:
                lines.append(f"    URL:      {c.login_url}")
            if c.onion_url:
                lines.append(f"    Onion:    {c.onion_url}")
            lines.append(f"    Email:    {c.username}")
            lines.append(f"    Password: {c.password_text}")
        lines.append("")
    return "\n".join(lines)


def generate_credentials(
    cfg: ArgusConfig,
    port_map: dict[str, dict[str, int]],
    secrets_dir: Path,
    output_dir: Path,
    onion_hostname: str | None = None,
) -> Path | None:
    """Write ``generated/CREDENTIALS.txt`` (mode 0600), covering every enabled
    network. Returns the path, or ``None`` when no network has an admin login."""
    creds = build_credentials(
        cfg, port_map, secrets_dir, onion_hostname=onion_hostname
    )
    if not creds:
        return None
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "CREDENTIALS.txt"
    path.write_text(format_credentials(creds))
    path.chmod(0o600)  # contains the Bitcart admin password
    return path
