"""Generate the shared Electrum image build context (``generated/electrum/``).

One Electrum wallet per network runs as a submarine-swap **provider**: it holds an
on-chain reserve, opens one Lightning channel into the LND ring, and runs the
``swapserver`` plugin (Electrum >= 4.6), announcing swap offers over a local Nostr
relay. No published image ships a current (>= 4.6, nostr-swap-capable) headless
Electrum — the community images on Docker Hub are stuck on 4.0.x — so, like the
cashu.me / Ark-CLN images, Argus builds one from source into a self-contained
context (a Dockerfile plus the entrypoint that boots the daemon, provisions the
wallet, opens the ring channel, and keeps the swap server running).

One build context is shared by every network; each network still runs its own
Electrum container (its wallet/seed/channels stay isolated per compose project).
See :mod:`argus.builders.electrum`.
"""

from __future__ import annotations

from pathlib import Path

from .config import ArgusConfig
from .constants import NETWORK_SPECS

# The shared image tag every per-network Electrum service builds/uses.
ELECTRUM_IMAGE = "argus-electrum:local"

# The Electrum version the image pins. Electrum publishes source tarballs at
# download.electrum.org/<ver>/Electrum-<ver>.tar.gz; pip-installing that pulls the
# Lightning + electrum-aionostr (nostr swap) dependencies (base requirements since
# 4.6.0 — no extra needed for them). Nostr-based submarine swaps require >= 4.6.0;
# 4.7.2 is the current stable release. Surfaced on the operator dashboard (the
# built tag ``:local`` carries no version). Bump alongside any Dockerfile change.
ELECTRUM_VERSION = "4.7.2"


def electrum_enabled_anywhere(cfg: ArgusConfig) -> bool:
    """True when any enabled network runs the Electrum swap provider."""
    return any(
        net.electrum_enabled(NETWORK_SPECS[k]) for k, net in cfg.enabled_networks()
    )


# A slim, single-stage build: Debian-based Python, the libs Electrum's Lightning +
# crypto need, then pip-install the pinned source tarball with the ``[crypto]``
# extra (adds cryptography + DNSSEC). electrum-aionostr (the nostr swap transport)
# and the Lightning deps are base requirements since 4.6.0, so no extra is needed
# for them. ELECTRUM_ECC_DONT_COMPILE=1 makes electrum-ecc link the system
# libsecp256k1 instead of compiling its own. Installed system-wide so the
# ``electrum`` console script is on PATH for the daemon + the entrypoint's CLI.
def _dockerfile() -> str:
    v = ELECTRUM_VERSION
    return (
        "# Generated by Bitcoin Argus — headless Electrum (Lightning + nostr\n"
        "# submarine-swap server), built from the pinned source tarball.\n"
        "FROM docker.io/library/python:3.12-slim-bookworm\n"
        "\n"
        "# Build + runtime deps: a C toolchain for any wheels that need building,\n"
        "# libsecp256k1 (electrum-ecc links it), and curl to fetch the tarball.\n"
        "RUN apt-get update && apt-get install -y --no-install-recommends \\\n"
        "\tbuild-essential curl ca-certificates libsecp256k1-dev \\\n"
        "\t&& rm -rf /var/lib/apt/lists/*\n"
        "\n"
        f"# Fetch the pinned Electrum source tarball and install it with [crypto]\n"
        f"# (Lightning + electrum-aionostr for nostr swaps come in as base deps).\n"
        f"ENV ELECTRUM_ECC_DONT_COMPILE=1\n"
        f"RUN curl -fsSL -o /tmp/electrum.tar.gz \\\n"
        f"\thttps://download.electrum.org/{v}/Electrum-{v}.tar.gz \\\n"
        f'\t&& python3 -m pip install --no-cache-dir "/tmp/electrum.tar.gz[crypto]" \\\n'
        f"\t&& rm /tmp/electrum.tar.gz\n"
        "\n"
        "# The entrypoint provisions the wallet, opens the ring channel, and keeps\n"
        "# the swap server alive (mounted per network by the compose service).\n"
        'ENTRYPOINT ["/bin/sh", "/scripts/electrum-entrypoint.sh"]\n'
    )


def generate_electrum_image(cfg: ArgusConfig, output_dir: Path) -> Path | None:
    """Write ``generated/electrum/`` (the shared build context). Returns its dir,
    or None when no enabled network runs the Electrum swap provider."""
    if not electrum_enabled_anywhere(cfg):
        return None

    out_dir = output_dir / "electrum"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "Dockerfile").write_text(_dockerfile())
    return out_dir
