"""Generate a ufw firewall script that opens exactly the public service ports.

Everything Argus marks "closed" (bitcoind RPC/ZMQ, LND gRPC/REST, Fulcrum admin,
mempool API/DB, Bitcart component ports) is bound to 127.0.0.1, so it is never
internet-reachable regardless of the firewall. This script's job is the inverse:
when ufw is enabled with a default-deny incoming policy, it must explicitly
allow the *public* ports — otherwise they'd be blocked (and e.g. the Bitcart
store/admin SSR, which fetches the public API URL, would hang).

Public ports = LND P2P, Fulcrum Electrum, the shared Caddy HTTP ports (cashu /
mempool / bitcart), and Bitcart's btclnd P2P pool. Plus SSH, and ACME/HTTPS
(80/443) when SSL is enabled.
"""

from __future__ import annotations

from pathlib import Path

from .config import ArgusConfig
from .constants import NETWORK_SPECS, TOR_SOCKS_PORT


def _public_rules(cfg: ArgusConfig, port_map: dict[str, dict[str, int]]) -> list[tuple]:
    """Return (port_or_range, comment) tuples for every public port."""
    rules: list[tuple[str, str]] = []
    for net_key, net in cfg.enabled_networks():
        ports = port_map[net_key]
        spec = NETWORK_SPECS[net_key]

        if net.bitcoind.p2p_public:
            rules.append((str(ports["bitcoind_p2p"]), f"{net_key} bitcoind p2p"))
        rules.append((str(ports["lnd_p2p"]), f"{net_key} lnd p2p"))
        if net.lnd_secondary_enabled(spec):
            rules.append((str(ports["lnd2_p2p"]), f"{net_key} lnd2 p2p"))
        if net.lnd_tertiary_enabled(spec):
            rules.append((str(ports["lnd3_p2p"]), f"{net_key} lnd3 p2p"))

        for i, ix in enumerate(net.enabled_indexers()):
            rules.append(
                (str(ports[f"fulcrum_{i}_electrum_tcp"]), f"{net_key} {ix.name} electrum")
            )

        if net.cashu.enabled:
            rules.append((str(ports["cashu_public"]), f"{net_key} cashu"))
            if net.cashu.wallet:
                rules.append(
                    (str(ports["cashu_wallet_public"]), f"{net_key} cashu wallet")
                )
        if net.mempool_enabled(spec):
            rules.append((str(ports["mempool_public"]), f"{net_key} mempool"))
        if net.bitcart.enabled:
            for name in ("bitcart_store_public", "bitcart_admin_public", "bitcart_api_public"):
                rules.append((str(ports[name]), f"{net_key} {name}"))
            base = ports["bitcart_btclnd_p2p_base"]
            pool = net.bitcart.btclnd_p2p_pool_size
            rng = f"{base}" if pool == 1 else f"{base}:{base + pool - 1}"
            rules.append((rng, f"{net_key} bitcart btclnd p2p"))
        if net.cashupayserver.enabled:
            rules.append((str(ports["cashupayserver_public"]), f"{net_key} cashupayserver"))
        if net.woocommerce.enabled:
            rules.append((str(ports["woocommerce_public"]), f"{net_key} woocommerce"))
    return rules


def render_firewall(cfg: ArgusConfig, port_map: dict[str, dict[str, int]]) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by Bitcoin Argus — open the public service ports.",
        "# Closed services are bound to 127.0.0.1 and need no rule.",
        "set -euo pipefail",
        "",
        "ufw allow 22/tcp comment 'ssh'  # keep SSH open BEFORE enabling ufw",
    ]
    if cfg.global_.ssl_enabled:
        lines += [
            "ufw allow 80/tcp comment 'argus acme/http'",
            "ufw allow 443/tcp comment 'argus https'",
        ]
    lines.append("")
    # The dashboard's public port. 80/443 are already handled above when SSL is
    # on; only add a rule when it isn't already covered (e.g. a custom port, or
    # plain HTTP on :80 with SSL off).
    if cfg.web.enabled:
        from .shared import web_public_port

        web_port = web_public_port(cfg)
        covered = {80, 443} if cfg.global_.ssl_enabled else set()
        if web_port not in covered:
            lines.append(f"ufw allow {web_port}/tcp comment 'argus dashboard'")
    for port, comment in _public_rules(cfg, port_map):
        lines.append(f"ufw allow {port}/tcp comment '{comment}'")

    # Tor: the onion service needs NO inbound rule (its circuits are outbound).
    # When LND advertises over Tor it reaches the shared tor container's SOCKS
    # proxy via the host gateway, so allow only the private Docker bridge range to
    # that one port; the default-deny policy still blocks it from the internet.
    tor = cfg.global_.tor
    if tor.enabled and tor.expose_lnd_p2p:
        lines.append(
            f"ufw allow from 172.16.0.0/12 to any port {TOR_SOCKS_PORT} proto tcp "
            f"comment 'argus lnd -> tor socks (docker bridge only)'"
        )
    lines += [
        "",
        "ufw reload",
        "echo 'Public ports allowed. To enforce default-deny incoming, run:'",
        "echo '  ufw default deny incoming && ufw default allow outgoing && ufw --force enable'",
    ]
    return "\n".join(lines) + "\n"


def generate_firewall(
    cfg: ArgusConfig,
    port_map: dict[str, dict[str, int]],
    output_dir: Path,
) -> Path:
    """Write generated/firewall.sh. Returns its path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "firewall.sh"
    path.write_text(render_firewall(cfg, port_map))
    path.chmod(0o755)
    return path
