"""The single-purpose Nostr relay for Electrum submarine swaps.

The Electrum swap provider announces offers and negotiates swaps over Nostr, so
each network runs a relay locked down to just that traffic:

* It accepts ONLY the two Electrum swap kinds — ``30315`` (the offer announcement,
  a NIP-38 replaceable event) and ``25582`` (the encrypted negotiation DM, an
  ephemeral event) — and rejects everything else. Accepting only the offer kind
  would let offers appear but no swap could execute (the negotiation DMs would be
  dropped), so BOTH are whitelisted.
* It forwards the ephemeral ``25582`` DMs to live subscribers.
* It expires events older than ``relay.retention_hours``.
* It serves a public WebSocket (fronted as wss by the shared Caddy).

We use **nostr-rs-relay** directly from its upstream image (no build): its
``config.toml`` has a native ``event_kind_allowlist`` (requirement 1, zero custom
code), it natively forwards ephemeral events without storing them and never stores
more than one replaceable offer per provider (so storage is naturally bounded),
and it serves a plain WebSocket. Age-based retention isn't a native knob, so a
tiny sidecar sweeps the SQLite store on a loop to honour the 24h cap. This module
renders each network's ``config.toml`` and the sweep script; the image itself is
pinned in ``global.nostr_relay_image``.
"""

from __future__ import annotations

from .constants import ELECTRUM_SWAP_KINDS, NOSTR_RELAY_INTERNAL_PORT
from .context import BuildContext

# Where the relay stores its SQLite DB inside the container (a mounted volume), and
# the DB filename nostr-rs-relay uses within it. The retention sweeper opens the
# same path read-write to delete aged-out rows.
RELAY_DB_DIR = "/usr/src/app/db"
RELAY_DB_FILE = f"{RELAY_DB_DIR}/nostr.db"
# Where the relay reads its config inside the container (upstream image default).
RELAY_CONFIG_PATH = "/usr/src/app/config.toml"


def render_relay_conf(ctx: BuildContext) -> str:
    """Render one network's nostr-rs-relay ``config.toml``.

    Binds a public WebSocket, points the SQLite store at the mounted volume, and —
    the whole point — whitelists ONLY the two Electrum swap kinds so the relay
    carries nothing else.
    """
    port = NOSTR_RELAY_INTERNAL_PORT
    kinds = ", ".join(str(k) for k in ELECTRUM_SWAP_KINDS)
    name = f"argus-{ctx.net_key} electrum-swaps"
    return (
        "# Generated by Bitcoin Argus — do not edit by hand.\n"
        "[info]\n"
        f'name = "{name}"\n'
        'description = "Single-purpose relay for Electrum submarine swaps '
        '(event kinds 30315 + 25582 only)."\n'
        "\n"
        "[database]\n"
        f'data_directory = "{RELAY_DB_DIR}"\n'
        "\n"
        "[network]\n"
        'address = "0.0.0.0"\n'
        f"port = {port}\n"
        "\n"
        "[limits]\n"
        "# The whole point of this relay: accept ONLY Electrum's two swap kinds\n"
        "# (30315 offer announcement + 25582 ephemeral negotiation DM). Every other\n"
        "# kind is discarded, so nothing else can use the relay.\n"
        f"event_kind_allowlist = [{kinds}]\n"
    )


def render_retention_sweep(retention_hours: int) -> str:
    """Render the retention sweeper's loop (runs in a minimal alpine sidecar).

    nostr-rs-relay has no native age-based purge, so this deletes any stored event
    older than the retention window on a loop. In practice little accumulates (the
    ephemeral DMs are never stored and the replaceable offers are bounded to one
    per provider), so this is mostly a guaranteed-cap safety net — hence
    best-effort (``|| true``): a transient SQLite lock just retries next cycle.
    """
    seconds = retention_hours * 3600
    return (
        "#!/bin/sh\n"
        "# Generated by Bitcoin Argus — expire relay events older than the window.\n"
        "set -u\n"
        f"RETENTION_SECONDS={seconds}\n"
        "SWEEP_INTERVAL=3600\n"
        'DB="/db/nostr.db"\n'
        "apk add --no-cache sqlite >/dev/null 2>&1 || true\n"
        "while true; do\n"
        "  sleep \"${SWEEP_INTERVAL}\"\n"
        "  [ -f \"$DB\" ] || continue\n"
        "  CUTOFF=$(( $(date +%s) - RETENTION_SECONDS ))\n"
        '  sqlite3 "$DB" "DELETE FROM event WHERE created_at < ${CUTOFF};" '
        ">/dev/null 2>&1 || true\n"
        "done\n"
    )
