"""Generate the operator-run ``open-mining.sh`` (+ compose overrides).

For regtest with auto-channels, bitcoind's P2P port is deliberately NOT published
on ``docker compose up`` (see ``builders/bitcoind.py``), so the chain stays
private while LND channels are funded and confirmed. After the ``lnd-channels``
setup completes, the operator runs ``open-mining.sh`` to expose the port: it
re-publishes it via a small compose override (``open-mining.override.yml``) and
adds the matching ufw rule. Custom-signet is never gated (outsiders can't mine it
without our signing key), so it never appears here.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from .config import ArgusConfig
from .constants import CHAIN_INTERNAL_PORTS, NETWORK_SPECS


def _gated_networks(cfg: ArgusConfig) -> list[str]:
    return [
        k
        for k, net in cfg.enabled_networks()
        if net.bitcoind_p2p_gated(k, NETWORK_SPECS[k])
    ]


def _write_override(out_dir: Path, net_key: str, p2p_host: int) -> None:
    internal = CHAIN_INTERNAL_PORTS[NETWORK_SPECS[net_key].chain]["p2p"]
    override = {
        "services": {
            "bitcoind": {
                # Appended to the base (which publishes no P2P port while gated),
                # re-publishing it publicly so external peers can mine.
                "ports": [f"{p2p_host}:{internal}"],
            }
        }
    }
    path = out_dir / net_key / "open-mining.override.yml"
    path.write_text(yaml.safe_dump(override, sort_keys=False))


def _render_script(entries: list[tuple[str, str, int]]) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by Bitcoin Argus — open regtest mining P2P after channel setup.",
        "#",
        "# WARNING: once open, ANYONE can attach a regtest node and mine — including",
        "# deep multi-block reorgs. That is intentional here (robustness testing /",
        "# public faucet mining), but the chain state is then adversarial.",
        "#",
        "# NOTE: a later plain `docker compose up -d` (without the override) re-closes",
        "# the port; re-run this script, or keep passing -f open-mining.override.yml.",
        "set -euo pipefail",
        "",
        'cd "$(dirname "$0")"',
        'FORCE="${1:-}"',
        "",
        "open_net() {  # dir project port",
        '  local dir="$1" proj="$2" port="$3"',
        '  local state',
        "  state=\"$(docker inspect -f '{{.State.Status}} {{.State.ExitCode}}' "
        '"${proj}-lnd-channels" 2>/dev/null || echo missing)"',
        '  if [ "$state" != "exited 0" ] && [ "$FORCE" != "--force" ]; then',
        '    echo "[$proj] lnd-channels not complete (state: $state); refusing." >&2',
        '    echo "       Wait for channel setup, or re-run with --force." >&2',
        "    return 1",
        "  fi",
        '  echo "[$proj] re-publishing bitcoind P2P on :$port (public mining)"',
        '  ( cd "$dir" && docker compose -f docker-compose.yml '
        "-f open-mining.override.yml up -d bitcoind )",
        '  ufw allow "${port}/tcp" comment "$proj bitcoind p2p (public mining)" || true',
        "  ufw reload || true",
        "}",
        "",
    ]
    for net_key, project, port in entries:
        lines.append(f'open_net "{net_key}" "{project}" "{port}"')
    lines += ["", 'echo "Public mining enabled. Mine responsibly."']
    return "\n".join(lines) + "\n"


def generate_open_mining(
    cfg: ArgusConfig,
    port_map: dict[str, dict[str, int]],
    output_dir: Path,
) -> Path | None:
    """Write generated/open-mining.sh + per-net overrides. Returns the script path
    (or None if no network is gated)."""
    gated = _gated_networks(cfg)
    if not gated:
        return None

    entries: list[tuple[str, str, int]] = []
    for net_key in gated:
        p2p_host = port_map[net_key]["bitcoind_p2p"]
        _write_override(output_dir, net_key, p2p_host)
        entries.append((net_key, f"argus-{net_key}", p2p_host))

    path = output_dir / "open-mining.sh"
    path.write_text(_render_script(entries))
    path.chmod(0o755)
    return path
