"""Auto-reset for the mined networks (regtest + custom-signet).

When a mined network's on-disk chain (bitcoind ``size_on_disk``) grows past a
configured cap, the whole installation for that network is torn down and
re-deployed to its base config — wiping every coin, Lightning channel,
transaction, and the mempool/Fulcrum/Cashu/Bitcart state with it. A custom
signet keeps its challenge + signing key (``secrets/`` is untouched), so it
resets to genesis as the *same* signet.

Two artefacts are generated:

* ``generated/<net>/reset.sh`` — the idempotent reset for one network (core
  ``docker compose down -v``/``up -d`` plus a pure-docker Bitcart recreate). It
  is self-locating and can be run by hand by an operator, or by the controller.
* ``generated/reset/`` — a small, long-running *controller* compose project
  (one container, the only thing with read-write Docker socket access) that
  polls each reset-enabled network's ``size_on_disk`` and runs that network's
  ``reset.sh`` when it reaches the cap. It also publishes a tiny
  ``reset_state.json`` (size + cap + block interval per network) that the
  dashboard reads — via the same read-only socket-proxy ``get_archive`` trick
  used for donations/LND info — to show the "resets in X" countdown.

The time-to-reset estimate assumes *maximum use of all blocks*: every block
mined at the consensus-maximum serialized size (:data:`MAX_BLOCK_BYTES`) at the
configured block interval. That is deliberately the fastest plausible growth, so
the countdown is a conservative lower bound.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import yaml

from .config import ArgusConfig
from .constants import (
    CHAIN_INTERNAL_PORTS,
    MAX_BLOCK_BYTES,
    NETWORK_SPECS,
    RESET_CONTROLLER_CONTAINER,
    RESET_STATE_FILE,
)
from .resources import global_log

BYTES_PER_GB = 1024**3  # GiB


# --- Time-to-reset estimate (pure; shared by the dashboard + tests) ----------

def growth_bytes_per_second(block_interval_seconds: int) -> float:
    """Fastest plausible chain growth: one max-size block per block interval."""
    if block_interval_seconds <= 0:
        return 0.0
    return MAX_BLOCK_BYTES / block_interval_seconds


def seconds_until_reset(
    size_on_disk: int | None, limit_bytes: int, block_interval_seconds: int
) -> float | None:
    """Estimated seconds until ``size_on_disk`` reaches ``limit_bytes``.

    Returns ``0.0`` when already at/over the cap (a reset is imminent) and
    ``None`` when it cannot be estimated (size unknown, or non-positive cap/rate).
    """
    if size_on_disk is None or limit_bytes <= 0:
        return None
    if size_on_disk >= limit_bytes:
        return 0.0
    rate = growth_bytes_per_second(block_interval_seconds)
    if rate <= 0:
        return None
    return (limit_bytes - size_on_disk) / rate


def format_reset_eta(seconds: float | None) -> str | None:
    """Render a countdown as "X days, Y hours" (or finer when under a day).

    ``None`` input => ``None`` (unknown); ``<=0`` => "imminent".
    """
    if seconds is None:
        return None
    seconds = int(seconds)
    if seconds <= 0:
        return "imminent"

    def plural(n: int, unit: str) -> str:
        return f"{n} {unit}{'' if n == 1 else 's'}"

    days = seconds // 86400
    hours = (seconds % 86400) // 3600
    minutes = (seconds % 3600) // 60
    if days > 0:
        return f"{plural(days, 'day')}, {plural(hours, 'hour')}"
    if hours > 0:
        return f"{plural(hours, 'hour')}, {plural(minutes, 'minute')}"
    return plural(minutes, "minute")


def limit_bytes(max_size_gb: float) -> int:
    return int(max_size_gb * BYTES_PER_GB)


# --- Generated artefacts -----------------------------------------------------

# One network's reset. POSIX sh so it runs under the operator's shell on the
# host AND under the alpine-based controller image. Self-locating via $0.
_RESET_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — re-deploy the '{net}' network to its base config.
#
# Tears the whole network down (wiping all chain/LND/mempool/Fulcrum/Cashu and
# Bitcart state) and brings it back up fresh. The controller runs this on the
# size cap; an operator can also run it by hand. secrets/ is untouched, so a
# custom signet keeps its challenge/key and resets to genesis as the same signet.
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
NET="{net}"
PROJECT="argus-$NET"
COMPOSE="$HERE/docker-compose.yml"

echo "[reset:$NET] tearing down core stack (docker compose down -v)..."
docker compose -p "$PROJECT" -f "$COMPOSE" down -v --remove-orphans

# Bitcart is its own compose project (deployed by the BareBits installer). Wipe
# its containers + volumes by compose-project label — pure docker, so this works
# from the controller too (re-running the installer would need bash/apt/root).
BC_PROJECT="argus-bitcart-$NET"
BC_DOCKER_DIR="/opt/bitcart-docker-lnd-$BC_PROJECT"
if [ -d "$BC_DOCKER_DIR" ]; then
  echo "[reset:$NET] tearing down Bitcart ($BC_PROJECT)..."
  CIDS="$(docker ps -aq --filter "label=com.docker.compose.project=$BC_PROJECT" || true)"
  [ -n "$CIDS" ] && docker rm -f $CIDS >/dev/null 2>&1 || true
  VOLS="$(docker volume ls -q --filter "label=com.docker.compose.project=$BC_PROJECT" || true)"
  [ -n "$VOLS" ] && docker volume rm $VOLS >/dev/null 2>&1 || true
fi

echo "[reset:$NET] bringing core stack back up (base config)..."
docker compose -p "$PROJECT" -f "$COMPOSE" up -d --build

# Recreate Bitcart via bitcart-docker's fast-path start.sh (no source rebuild;
# the checkout + its env/plugin config persist on the host across the wipe), then
# reattach its Neutrino btclnd to our network so it re-syncs the fresh chain.
if [ -d "$BC_DOCKER_DIR" ]; then
  echo "[reset:$NET] recreating Bitcart..."
  ( cd "$BC_DOCKER_DIR" && ./start.sh )
  BTCLND_CT="$BC_PROJECT-btclnd-1"
  docker network connect "$PROJECT-net" "$BTCLND_CT" 2>/dev/null || true
  docker restart "$BTCLND_CT" >/dev/null 2>&1 || true
fi

echo "[reset:$NET] done — re-deployed to base config."
"""


# The controller image: docker CLI + compose plugin, plus bash (bitcart-docker's
# start.sh is bash) and git (defensive — start.sh may stamp a version).
_DOCKERFILE = """\
# Generated by Bitcoin Argus — the auto-reset controller image.
ARG RESET_IMAGE=docker:27-cli
FROM ${RESET_IMAGE}
RUN apk add --no-cache bash git
ENTRYPOINT ["/bin/sh", "-c", "exec /bin/sh \\"$ARGUS_DEPLOY_ROOT/reset/watch.sh\\""]
"""


# The poll loop. Reads its per-network table from reset/nets.tsv, RPC creds from
# each network's generated .env, and writes the dashboard state file atomically.
_WATCH_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — auto-reset controller poll loop.
set -u

: "${{ARGUS_DEPLOY_ROOT:?ARGUS_DEPLOY_ROOT must be the host path to generated/}}"
STATE="{state_file}"
NETS_TSV="$ARGUS_DEPLOY_ROOT/reset/nets.tsv"
POLL="${{POLL_INTERVAL:-300}}"
TAB="$(printf '\\t')"

mkdir -p "$(dirname "$STATE")"
echo "[reset-controller] watching $NETS_TSV (poll ${{POLL}}s)"

# size_on_disk for a network's bitcoind, via the daemon (docker exec). Empty on
# any failure (node not up yet, RPC not ready) so the caller writes null.
read_size() {{  # container chain rpcport user pass
  docker exec "$1" bitcoin-cli -chain="$2" -rpcconnect=127.0.0.1 -rpcport="$3" \\
    -rpcuser="$4" -rpcpassword="$5" getblockchaininfo 2>/dev/null \\
    | grep -o '"size_on_disk": *[0-9]*' | grep -o '[0-9]*$'
}}

env_value() {{  # key envfile
  [ -f "$2" ] || return 0
  grep -E "^$1=" "$2" | head -n1 | cut -d= -f2-
}}

while true; do
  TMP="${{STATE}}.tmp"
  : > "$TMP"
  printf '{{' >> "$TMP"
  first=1
  while IFS="$TAB" read -r net chain rpcport container interval limit gb netdir; do
    [ -z "$net" ] && continue
    ENVF="$ARGUS_DEPLOY_ROOT/$netdir/.env"
    U="$(env_value RPC_USER "$ENVF")"
    P="$(env_value RPC_PASSWORD "$ENVF")"
    SIZE="$(read_size "$container" "$chain" "$rpcport" "$U" "$P")"

    [ "$first" = 1 ] || printf ',' >> "$TMP"
    first=0
    if [ -n "$SIZE" ]; then
      printf '"%s":{{"size_on_disk":%s,"limit_bytes":%s,"block_interval_seconds":%s,"max_size_gb":%s}}' \\
        "$net" "$SIZE" "$limit" "$interval" "$gb" >> "$TMP"
      if [ "$SIZE" -ge "$limit" ]; then
        echo "[reset-controller] $net size_on_disk=$SIZE >= cap=$limit — resetting"
        sh "$ARGUS_DEPLOY_ROOT/$netdir/reset.sh" \\
          || echo "[reset-controller] $net reset.sh FAILED"
      fi
    else
      printf '"%s":{{"size_on_disk":null,"limit_bytes":%s,"block_interval_seconds":%s,"max_size_gb":%s}}' \\
        "$net" "$limit" "$interval" "$gb" >> "$TMP"
    fi
  done < "$NETS_TSV"
  printf '}}\\n' >> "$TMP"
  mv "$TMP" "$STATE"
  sleep "$POLL"
done
"""


def reset_networks(cfg: ArgusConfig) -> list[str]:
    """Enabled networks with auto-reset on (in canonical order)."""
    return [k for k, net in cfg.enabled_networks() if net.reset_enabled(k)]


def _nets_tsv(cfg: ArgusConfig) -> str:
    rows: list[str] = []
    for net_key in reset_networks(cfg):
        net = cfg.networks[net_key]
        spec = NETWORK_SPECS[net_key]
        rpc_port = CHAIN_INTERNAL_PORTS[spec.chain]["rpc"]
        rows.append(
            "\t".join(
                [
                    net_key,
                    spec.chain,
                    str(rpc_port),
                    f"argus-{net_key}-bitcoind",
                    str(net.miner.block_interval_seconds),
                    str(limit_bytes(net.reset.max_size_gb)),
                    _fmt_gb(net.reset.max_size_gb),
                    net_key,  # netdir, relative to ARGUS_DEPLOY_ROOT (= generated/)
                ]
            )
        )
    return "".join(r + "\n" for r in rows)


def _fmt_gb(gb: float) -> str:
    """Compact numeric for JSON (30 not 30.0; 0.05 stays 0.05)."""
    return f"{gb:g}"


def _poll_interval(cfg: ArgusConfig) -> int:
    intervals = [
        cfg.networks[k].reset.check_interval_seconds for k in reset_networks(cfg)
    ]
    return min(intervals) if intervals else 300


def _any_bitcart(cfg: ArgusConfig) -> bool:
    return any(cfg.networks[k].bitcart.enabled for k in reset_networks(cfg))


def _controller_compose(cfg: ArgusConfig) -> dict:
    deploy_root = "${ARGUS_DEPLOY_ROOT}"
    volumes = [
        # The only read-write Docker socket in the install (this is the
        # "privileged" surface the operator opted into).
        "/var/run/docker.sock:/var/run/docker.sock",
        # The generated tree, mounted at its IDENTICAL host path so the compose
        # bind-mount sources the controller passes to the daemon resolve to real
        # host paths.
        f"{deploy_root}:{deploy_root}",
    ]
    # Bitcart's bitcart-docker checkouts live under /opt; the recreate needs them.
    if _any_bitcart(cfg):
        volumes.append("/opt:/opt")

    return {
        "name": "argus-reset",
        "services": {
            "reset-controller": {
                "build": {
                    "context": ".",
                    "dockerfile": "Dockerfile",
                    "args": {"RESET_IMAGE": "${RESET_CONTROLLER_IMAGE}"},
                },
                "image": "argus-reset-controller:local",
                "container_name": RESET_CONTROLLER_CONTAINER,
                "restart": "unless-stopped",
                # All work is via the Docker socket (unix) + docker exec; no net.
                "network_mode": "none",
                "environment": {
                    "ARGUS_DEPLOY_ROOT": deploy_root,
                    "POLL_INTERVAL": "${POLL_INTERVAL}",
                },
                "volumes": volumes,
            }
        },
    }


def generate_reset(cfg: ArgusConfig, output_dir: Path) -> Path | None:
    """Generate ``generated/<net>/reset.sh`` for each reset-enabled network and
    the ``generated/reset/`` controller project. Returns the controller dir, or
    ``None`` when no enabled network has reset on."""
    nets = reset_networks(cfg)
    if not nets:
        return None

    # Per-network reset scripts.
    for net_key in nets:
        net_dir = output_dir / net_key
        net_dir.mkdir(parents=True, exist_ok=True)
        script = net_dir / "reset.sh"
        script.write_text(_RESET_SH.format(net=net_key))
        script.chmod(0o755)

    # The controller project.
    out_dir = output_dir / "reset"
    out_dir.mkdir(parents=True, exist_ok=True)

    compose = _controller_compose(cfg)
    rotation, log_block = global_log(cfg)
    if rotation:
        for svc in compose["services"].values():
            svc.setdefault("logging", log_block)

    (out_dir / "Dockerfile").write_text(_DOCKERFILE)
    (out_dir / "watch.sh").write_text(
        _WATCH_SH.format(state_file=RESET_STATE_FILE)
    )
    (out_dir / "watch.sh").chmod(0o755)
    (out_dir / "nets.tsv").write_text(_nets_tsv(cfg))
    (out_dir / "docker-compose.yml").write_text(
        yaml.safe_dump(compose, sort_keys=False, default_flow_style=False)
    )
    (out_dir / ".env").write_text(
        f"RESET_CONTROLLER_IMAGE={cfg.global_.reset_controller_image}\n"
        f"POLL_INTERVAL={_poll_interval(cfg)}\n"
    )

    return out_dir
