"""Generate the dashboard project (``generated/web/``).

Like the shared Caddy layer, the dashboard spans every enabled network, so it is
generated from the full config rather than per-network. The output is a
self-contained build context: the ``argus`` source is copied in alongside a
Dockerfile, a compose file (the Flask/gunicorn app plus a read-only
docker-socket-proxy sidecar), and the deployment's ``config.yaml``. That mirrors
how the rest of ``generated/`` is portable to the target host as-is.

The shared Caddy fronts the dashboard at the site root (see :mod:`argus.shared`);
gunicorn listens on :8000 in-container, published to the host loopback on
:data:`~argus.constants.WEB_BACKEND_PORT`.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import yaml

from .config import ArgusConfig
from .constants import FAUCET_BACKEND_PORT, WEB_BACKEND_PORT
from .resources import global_log

_GUNICORN_PORT = 8000  # in-container listen port (dashboard and faucet alike)


def _dockerfile() -> str:
    return (
        "# Generated by Bitcoin Argus — the dashboard image.\n"
        "ARG PYTHON_IMAGE=python:3.12-slim\n"
        "FROM ${PYTHON_IMAGE}\n"
        "WORKDIR /app\n"
        "COPY argus/web/requirements.txt /tmp/web-requirements.txt\n"
        "RUN pip install --no-cache-dir 'pydantic>=2' 'PyYAML>=6' \\\n"
        "    && pip install --no-cache-dir -r /tmp/web-requirements.txt\n"
        "COPY argus /app/argus\n"
        "ENV PYTHONUNBUFFERED=1 CONFIG_PATH=/app/config.yaml CACHE_DB=/data/cache.db\n"
        f"EXPOSE {_GUNICORN_PORT}\n"
        # The dashboard's first (cold-cache) request collects per-container stats +
        # volume sizes; on a large multi-network install that can run past the
        # stock 120s worker timeout even with the parallel stats collection, so the
        # window is widened (the result is cached for an hour afterward).
        'CMD ["gunicorn", "-b", "0.0.0.0:%d", "-w", "2", "--timeout", "240", '
        '"argus.web.wsgi:app"]\n' % _GUNICORN_PORT
    )


def _compose(
    onion_hostname: str | None,
    lnd_net_keys: list[str],
    faucet_net_keys: list[str],
    metrics_history=None,
    faucet_ip_salt: str | None = None,
) -> dict:
    history_on = bool(metrics_history and metrics_history.enabled)
    web_env = {
        "DOCKER_HOST": "tcp://socket-proxy:2375",
        "CONFIG_PATH": "/app/config.yaml",
        "CACHE_DB": "/data/cache.db",
        "HOST_ROOT": "/host",
    }
    if history_on:
        # The dashboard reads the time-series store the sampler writes (read-only).
        web_env["HISTORY_DB"] = "/history/metrics.db"
    # The dashboard shows the installation's onion address (and the per-service
    # onion connection lines) when Tor is enabled. Passed by env so a config edit
    # doesn't require a rebuild; absent => the Tor UI is simply omitted.
    if onion_hostname:
        web_env["ONION_HOSTNAME"] = onion_hostname

    # Both the dashboard and the faucet join each relevant network's compose
    # network (declared external) so they can reach that network's primary LND
    # node by its unique container name (argus-<net>-lnd) over REST. The `argus`
    # service alias is NOT usable: every per-net LND shares it, so it would collide
    # across the networks joined here. Aliased locally as `net-<key>` ->
    # argus-<key>-net. The dashboard needs the LNURL networks; the faucet needs
    # the faucet networks; the top-level `networks:` declares their union once.
    def _net_aliases(keys: list[str]) -> list[str]:
        return [f"net-{k}" for k in keys]

    all_net_keys = list(dict.fromkeys([*lnd_net_keys, *faucet_net_keys]))
    extra_networks: dict[str, dict] = {
        f"net-{k}": {"name": f"argus-{k}-net", "external": True}
        for k in all_net_keys
    }

    services: dict[str, dict] = {
        # Read-only Docker API proxy: the only thing that touches the socket.
        # Exposes just the GET endpoints the dashboard reads; POST stays off.
        "socket-proxy": {
            "image": "${SOCKET_PROXY_IMAGE}",
            "container_name": "argus-web-socket-proxy",
            "restart": "unless-stopped",
            "environment": {
                # GET-only surface the dashboard needs. VERSION lets the
                # Docker SDK auto-negotiate the API version on connect.
                "VERSION": "1",
                "CONTAINERS": "1",
                "VOLUMES": "1",
                "IMAGES": "1",
                "INFO": "1",
                "SYSTEM": "1",
                "NETWORKS": "1",
                "PING": "1",
                "POST": "0",
            },
            "volumes": ["/var/run/docker.sock:/var/run/docker.sock:ro"],
            "networks": ["web"],
        },
        "web": {
            "build": {
                "context": ".",
                "dockerfile": "Dockerfile",
                "args": {"PYTHON_IMAGE": "${WEB_PYTHON_IMAGE}"},
            },
            "image": "argus-web:local",
            "container_name": "argus-web",
            "restart": "unless-stopped",
            "depends_on": ["socket-proxy"],
            "environment": web_env,
            "volumes": [
                "web_cache:/data",
                # Host root (read-only) so disk totals reflect the real machine.
                "/:/host:ro",
                # Config is mounted (not baked) so edits don't need a rebuild.
                "./config.yaml:/app/config.yaml:ro",
            ],
            # Closed to the internet; the shared Caddy fronts it.
            "ports": [f"127.0.0.1:{WEB_BACKEND_PORT}:{_GUNICORN_PORT}"],
            "networks": ["web", *_net_aliases(lnd_net_keys)],
        },
    }

    volumes: dict[str, dict] = {"web_cache": {}}

    # The metrics-history sampler: a THIRD service from the same image (so a
    # sampler bug runs in its own process and can't crash the dashboard, like the
    # faucet). It records per-bucket CPU/RAM/disk/net over time into a shared
    # SQLite volume the dashboard reads read-only. Only generated when enabled.
    if history_on:
        mh = metrics_history
        services["web"]["volumes"].append("metrics_data:/history:ro")
        services["metrics-sampler"] = {
            "image": "argus-web:local",
            "container_name": "argus-metrics-sampler",
            "restart": "unless-stopped",
            "depends_on": ["socket-proxy"],
            "command": ["python", "-m", "argus.web.sampler"],
            "environment": {
                "DOCKER_HOST": "tcp://socket-proxy:2375",
                "HISTORY_DB": "/history/metrics.db",
                "HOST_ROOT": "/host",
                "SAMPLE_INTERVAL_SECONDS": str(mh.sample_interval_seconds),
                "DISK_SAMPLE_INTERVAL_SECONDS": str(
                    mh.disk_sample_interval_seconds
                ),
                "RAW_RETENTION_HOURS": str(mh.raw_retention_hours),
                "HOURLY_RETENTION_DAYS": str(mh.hourly_retention_days),
                "DAILY_RETENTION_DAYS": str(mh.daily_retention_days),
            },
            "volumes": [
                "metrics_data:/history",
                # Host root (read-only) for whole-host CPU/mem/disk/net totals.
                "/:/host:ro",
            ],
            "networks": ["web"],
        }
        volumes["metrics_data"] = {}

    # The faucet: a SECOND service from the same image (so a faucet bug runs in a
    # separate process and can't crash the dashboard). It reads each faucet
    # network's admin.macaroon + tls.cert from that network's LND data volume,
    # mounted read-only — the one place this install holds a fund-moving
    # credential, kept off the dashboard. It joins the faucet networks for
    # reachability and the `web` network to read donation info via the socket
    # proxy. Only generated when at least one network has a faucet.
    if faucet_net_keys:
        faucet_env = {
            "CONFIG_PATH": "/app/config.yaml",
            "FAUCET_DB": "/faucet/faucet.db",
            "LND_DIR_ROOT": "/lnd",
            # For reading the public donation address via the read-only proxy.
            "DOCKER_HOST": "tcp://socket-proxy:2375",
        }
        if onion_hostname:
            faucet_env["ONION_HOSTNAME"] = onion_hostname
        # Install-wide salt for hashing visitor IPs (per-IP daily limit). Stable
        # across regenerations so the stored hashes keep matching.
        if faucet_ip_salt:
            faucet_env["FAUCET_IP_SALT"] = faucet_ip_salt

        faucet_volumes = [
            "faucet_data:/faucet",
            "./config.yaml:/app/config.yaml:ro",
        ]
        for k in faucet_net_keys:
            # The per-network LND data volume (external — created by that
            # network's stack), read-only: holds admin.macaroon + tls.cert.
            vol = f"argus-{k}_lnd_data"
            faucet_volumes.append(f"{vol}:/lnd/{k}:ro")
            volumes[vol] = {"name": vol, "external": True}

        services["faucet"] = {
            "image": "argus-web:local",
            "container_name": "argus-faucet",
            "restart": "unless-stopped",
            "depends_on": ["web", "socket-proxy"],
            "command": [
                "gunicorn",
                "-b",
                f"0.0.0.0:{_GUNICORN_PORT}",
                "-w",
                "2",
                "--timeout",
                "120",
                "argus.faucet.wsgi:app",
            ],
            "environment": faucet_env,
            "volumes": faucet_volumes,
            "ports": [f"127.0.0.1:{FAUCET_BACKEND_PORT}:{_GUNICORN_PORT}"],
            "networks": ["web", *_net_aliases(faucet_net_keys)],
        }
        volumes["faucet_data"] = {}

    return {
        "name": "argus-web",
        "services": services,
        "volumes": volumes,
        "networks": {"web": {"name": "argus-web-net"}, **extra_networks},
    }


def _copy_source(out_dir: Path) -> None:
    """Copy the ``argus`` package into the build context (self-contained image)."""
    pkg_root = Path(__file__).resolve().parent  # .../argus
    dest = out_dir / "argus"
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(
        pkg_root,
        dest,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "tests"),
    )


def generate_web(
    cfg: ArgusConfig,
    output_dir: Path,
    config_path: str | Path,
    onion_hostname: str | None = None,
    faucet_ip_salt: str | None = None,
) -> Path | None:
    """Generate ``generated/web/``. Returns its dir, or None if web is disabled."""
    if not cfg.web.enabled:
        return None

    out_dir = output_dir / "web"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Join each enabled network's compose network only when LNURL is on (the
    # dashboard mints invoices on their LND nodes); otherwise stay isolated.
    lnd_net_keys = (
        [k for k, _ in cfg.enabled_networks()] if cfg.web.lnurl.enabled else []
    )
    # The faucet is a separate service joining each faucet-enabled network (for
    # LND reachability + its read-only data volume).
    faucet_net_keys = [k for k, _ in cfg.faucet_networks()]
    compose = _compose(
        onion_hostname,
        lnd_net_keys,
        faucet_net_keys,
        cfg.web.metrics_history,
        faucet_ip_salt,
    )
    rotation, log_block = global_log(cfg)
    if rotation:
        for svc in compose["services"].values():
            svc.setdefault("logging", log_block)

    (out_dir / "Dockerfile").write_text(_dockerfile())
    (out_dir / "docker-compose.yml").write_text(
        yaml.safe_dump(compose, sort_keys=False, default_flow_style=False)
    )
    (out_dir / ".env").write_text(
        f"WEB_PYTHON_IMAGE={cfg.global_.web_python_image}\n"
        f"SOCKET_PROXY_IMAGE={cfg.global_.socket_proxy_image}\n"
    )

    # Ship the source and the active config inside the build context.
    _copy_source(out_dir)
    shutil.copyfile(config_path, out_dir / "config.yaml")

    return out_dir
