"""Generate the dashboard project (``generated/web/``).

Like the shared Caddy layer, the dashboard spans every enabled network, so it is
generated from the full config rather than per-network. The output is a
self-contained build context: the ``argus`` source is copied in alongside a
Dockerfile, a compose file (the Flask/gunicorn app plus a read-only
docker-socket-proxy sidecar), and the deployment's ``config.yaml``. That mirrors
how the rest of ``generated/`` is portable to the target host as-is.

The shared Caddy fronts the dashboard at the site root (see :mod:`argus.shared`);
gunicorn listens on :8000 in-container, published to the host loopback on
:data:`~argus.constants.WEB_BACKEND_PORT`.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import yaml

from .config import ArgusConfig
from .constants import WEB_BACKEND_PORT
from .resources import global_log

_GUNICORN_PORT = 8000  # in-container listen port


def _dockerfile() -> str:
    return (
        "# Generated by Bitcoin Argus — the dashboard image.\n"
        "ARG PYTHON_IMAGE=python:3.12-slim\n"
        "FROM ${PYTHON_IMAGE}\n"
        "WORKDIR /app\n"
        "COPY argus/web/requirements.txt /tmp/web-requirements.txt\n"
        "RUN pip install --no-cache-dir 'pydantic>=2' 'PyYAML>=6' \\\n"
        "    && pip install --no-cache-dir -r /tmp/web-requirements.txt\n"
        "COPY argus /app/argus\n"
        "ENV PYTHONUNBUFFERED=1 CONFIG_PATH=/app/config.yaml CACHE_DB=/data/cache.db\n"
        f"EXPOSE {_GUNICORN_PORT}\n"
        'CMD ["gunicorn", "-b", "0.0.0.0:%d", "-w", "2", "--timeout", "120", '
        '"argus.web.wsgi:app"]\n' % _GUNICORN_PORT
    )


def _compose() -> dict:
    return {
        "name": "argus-web",
        "services": {
            # Read-only Docker API proxy: the only thing that touches the socket.
            # Exposes just the GET endpoints the dashboard reads; POST stays off.
            "socket-proxy": {
                "image": "${SOCKET_PROXY_IMAGE}",
                "container_name": "argus-web-socket-proxy",
                "restart": "unless-stopped",
                "environment": {
                    # GET-only surface the dashboard needs. VERSION lets the
                    # Docker SDK auto-negotiate the API version on connect.
                    "VERSION": "1",
                    "CONTAINERS": "1",
                    "VOLUMES": "1",
                    "IMAGES": "1",
                    "INFO": "1",
                    "SYSTEM": "1",
                    "NETWORKS": "1",
                    "PING": "1",
                    "POST": "0",
                },
                "volumes": ["/var/run/docker.sock:/var/run/docker.sock:ro"],
                "networks": ["web"],
            },
            "web": {
                "build": {
                    "context": ".",
                    "dockerfile": "Dockerfile",
                    "args": {"PYTHON_IMAGE": "${WEB_PYTHON_IMAGE}"},
                },
                "image": "argus-web:local",
                "container_name": "argus-web",
                "restart": "unless-stopped",
                "depends_on": ["socket-proxy"],
                "environment": {
                    "DOCKER_HOST": "tcp://socket-proxy:2375",
                    "CONFIG_PATH": "/app/config.yaml",
                    "CACHE_DB": "/data/cache.db",
                    "HOST_ROOT": "/host",
                },
                "volumes": [
                    "web_cache:/data",
                    # Host root (read-only) so disk totals reflect the real machine.
                    "/:/host:ro",
                    # Config is mounted (not baked) so edits don't need a rebuild.
                    "./config.yaml:/app/config.yaml:ro",
                ],
                # Closed to the internet; the shared Caddy fronts it.
                "ports": [f"127.0.0.1:{WEB_BACKEND_PORT}:{_GUNICORN_PORT}"],
                "networks": ["web"],
            },
        },
        "volumes": {"web_cache": {}},
        "networks": {"web": {"name": "argus-web-net"}},
    }


def _copy_source(out_dir: Path) -> None:
    """Copy the ``argus`` package into the build context (self-contained image)."""
    pkg_root = Path(__file__).resolve().parent  # .../argus
    dest = out_dir / "argus"
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(
        pkg_root,
        dest,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "tests"),
    )


def generate_web(
    cfg: ArgusConfig,
    output_dir: Path,
    config_path: str | Path,
) -> Path | None:
    """Generate ``generated/web/``. Returns its dir, or None if web is disabled."""
    if not cfg.web.enabled:
        return None

    out_dir = output_dir / "web"
    out_dir.mkdir(parents=True, exist_ok=True)

    compose = _compose()
    rotation, log_block = global_log(cfg)
    if rotation:
        for svc in compose["services"].values():
            svc.setdefault("logging", log_block)

    (out_dir / "Dockerfile").write_text(_dockerfile())
    (out_dir / "docker-compose.yml").write_text(
        yaml.safe_dump(compose, sort_keys=False, default_flow_style=False)
    )
    (out_dir / ".env").write_text(
        f"WEB_PYTHON_IMAGE={cfg.global_.web_python_image}\n"
        f"SOCKET_PROXY_IMAGE={cfg.global_.socket_proxy_image}\n"
    )

    # Ship the source and the active config inside the build context.
    _copy_source(out_dir)
    shutil.copyfile(config_path, out_dir / "config.yaml")

    return out_dir
