"""Admin credential surfacing: builder, generated file, CLI, and stability."""

from __future__ import annotations

import stat

import yaml

from argus.cli import main
from argus.credentials import build_credentials, format_credentials
from argus.generate import generate
from argus.ports import allocate
from argus.secrets import read_onion_hostname
from helpers import BITCART_OFF, BITCART_OK, make, validated


def _gen(tmp_path, data):
    cfgp = tmp_path / "config.yaml"
    cfgp.write_text(yaml.safe_dump(data))
    out, sec = tmp_path / "gen", tmp_path / "sec"
    generate(str(cfgp), output_dir=out, secrets_dir=sec)
    return out, sec


def _bitcart_pw(sec, net):
    for line in (sec / net / "secrets.env").read_text().splitlines():
        if line.startswith("BITCART_ADMIN_PASSWORD="):
            return line.split("=", 1)[1]
    raise AssertionError("BITCART_ADMIN_PASSWORD not persisted")


def test_build_credentials_bitcart_enabled(tmp_path):
    data = make({"regtest": {"enabled": True, "bitcart": BITCART_OK}})
    _, sec = _gen(tmp_path, data)
    cfg = validated(data)
    port_map = allocate(cfg)
    creds = build_credentials(cfg, port_map, sec)

    assert len(creds) == 1
    c = creds[0]
    assert c.network == "regtest"
    assert c.component == "Bitcart admin"
    assert c.username == "admin@example.com"
    # The surfaced password is exactly the persisted secret (never regenerated).
    assert c.password == _bitcart_pw(sec, "regtest")
    port = port_map["regtest"]["bitcart_admin_public"]
    assert c.login_url == f"http://x.com:{port}/"  # ssl off in test default
    assert c.onion_url is None


def test_login_url_https_when_ssl_on(tmp_path):
    data = make({"regtest": {"enabled": True, "bitcart": BITCART_OK}},
                ssl_enabled=True, acme_email="ops@x.com")
    _, sec = _gen(tmp_path, data)
    cfg = validated(data)
    port_map = allocate(cfg)
    creds = build_credentials(cfg, port_map, sec)
    port = port_map["regtest"]["bitcart_admin_public"]
    assert creds[0].login_url == f"https://x.com:{port}/"


def test_bitcart_disabled_yields_no_credentials(tmp_path):
    data = make({"regtest": {"enabled": True, "bitcart": BITCART_OFF}})
    _, sec = _gen(tmp_path, data)
    cfg = validated(data)
    assert build_credentials(cfg, allocate(cfg), sec) == []


def test_only_filters_to_one_network(tmp_path):
    data = make({
        "regtest": {"enabled": True, "bitcart": BITCART_OK},
        "signet": {"enabled": True, "bitcart": BITCART_OK},
    })
    _, sec = _gen(tmp_path, data)
    cfg = validated(data)
    creds = build_credentials(cfg, allocate(cfg), sec, only="signet")
    assert [c.network for c in creds] == ["signet"]


def test_pending_when_secrets_missing(tmp_path):
    # No generate run => no secrets.env. The row still appears, marked pending,
    # and is never auto-generated by the read-only surface.
    data = make({"regtest": {"enabled": True, "bitcart": BITCART_OK}})
    cfg = validated(data)
    creds = build_credentials(cfg, allocate(cfg), tmp_path / "absent")
    assert creds[0].password is None
    assert "pending" in format_credentials(creds)


def test_onion_url_present_when_tor_enabled(tmp_path):
    data = make({"regtest": {"enabled": True, "bitcart": BITCART_OK}},
                tor={"enabled": True})
    _, sec = _gen(tmp_path, data)
    cfg = validated(data)
    port_map = allocate(cfg)
    onion = read_onion_hostname(sec)
    assert onion and onion.endswith(".onion")
    creds = build_credentials(cfg, port_map, sec, onion_hostname=onion)
    port = port_map["regtest"]["bitcart_admin_public"]
    assert creds[0].onion_url == f"http://{onion}:{port}/"


def test_generate_writes_credentials_file_0600(tmp_path):
    out, sec = _gen(tmp_path, make({"regtest": {"enabled": True, "bitcart": BITCART_OK}}))
    f = out / "CREDENTIALS.txt"
    assert f.is_file()
    assert stat.S_IMODE(f.stat().st_mode) == 0o600  # holds the admin password
    text = f.read_text()
    assert "[regtest]" in text
    assert "Bitcart admin" in text
    assert _bitcart_pw(sec, "regtest") in text


def test_no_credentials_file_when_no_logins(tmp_path):
    out, _ = _gen(tmp_path, make({"regtest": {"enabled": True, "bitcart": BITCART_OFF}}))
    assert not (out / "CREDENTIALS.txt").exists()


def test_credentials_stable_across_regenerate(tmp_path):
    # The operator's stated requirement: credentials must not change between
    # rebuilds. Secrets are idempotent, so the file is byte-identical on re-gen.
    data = make({"regtest": {"enabled": True, "bitcart": BITCART_OK}})
    out, sec = _gen(tmp_path, data)
    first = (out / "CREDENTIALS.txt").read_text()
    generate(str(tmp_path / "config.yaml"), output_dir=out, secrets_dir=sec)
    assert (out / "CREDENTIALS.txt").read_text() == first


def test_format_no_credentials():
    assert "no admin logins" in format_credentials([])


def test_cli_credentials_prints_password(tmp_path, capsys):
    data = make({"regtest": {"enabled": True, "bitcart": BITCART_OK}})
    _, sec = _gen(tmp_path, data)
    rc = main(["-c", str(tmp_path / "config.yaml"),
               "credentials", "--secrets-dir", str(sec)])
    assert rc == 0
    out = capsys.readouterr().out
    assert "Bitcart admin" in out
    assert _bitcart_pw(sec, "regtest") in out


def test_cli_credentials_unknown_network(tmp_path, capsys):
    data = make({"regtest": {"enabled": True, "bitcart": BITCART_OK}})
    _, sec = _gen(tmp_path, data)
    rc = main(["-c", str(tmp_path / "config.yaml"),
               "credentials", "nosuch", "--secrets-dir", str(sec)])
    assert rc == 1
    assert "unknown network" in capsys.readouterr().err
