#!/bin/sh
# Generated by Bitcoin Argus — custom-signet block producer.
#
# Imports the block-signing key (as the bare-multisig descriptor that matches the
# signet challenge), then mines the initial maturity blocks fast and settles into
# one block per interval. Blocks are signed via the wallet and grinded at minimum
# signet difficulty (cheap), mirroring the regtest miner's cadence.
set -eu

CLI="bitcoin-cli -signet -rpcconnect=${RPC_CONNECT} -rpcport=${RPC_PORT} \
-rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD}"
WCLI="${CLI} -rpcwallet=signer"
GRIND="bitcoin-util grind"
MINER="python3 /signet/miner"

echo "[signet-miner] waiting for bitcoind RPC..."
until $CLI getblockchaininfo >/dev/null 2>&1; do sleep 2; done

# A descriptor wallet to hold the signing key.
$CLI -named createwallet wallet_name=signer descriptors=true >/dev/null 2>&1 \
  || $CLI loadwallet signer >/dev/null 2>&1 || true

# Import the signing key as multi(1,KEY): a *bare* multisig that exactly matches
# the challenge script (5121<pubkey>51ae). combo()/wpkh() do NOT cover the bare
# multisig, so the wallet could not otherwise sign blocks.
CHK=$($CLI getdescriptorinfo "multi(1,${SIGNET_MINER_WIF})" \
  | python3 -c 'import sys,json;print(json.load(sys.stdin)["checksum"])')
$WCLI importdescriptors \
  "[{\"desc\":\"multi(1,${SIGNET_MINER_WIF})#${CHK}\",\"timestamp\":\"now\"}]" \
  >/dev/null 2>&1 || true

ADDR=$($WCLI getnewaddress)
echo "[signet-miner] mining rewards to ${ADDR}"

mine_one() {
  $MINER --cli="$WCLI" generate --grind-cmd="$GRIND" --address="$ADDR" --min-nbits >/dev/null
}

HEIGHT=$($CLI getblockcount)
if [ "$HEIGHT" -lt "$INITIAL_BLOCKS" ]; then
  echo "[signet-miner] generating initial blocks up to ${INITIAL_BLOCKS}"
  while [ "$($CLI getblockcount)" -lt "$INITIAL_BLOCKS" ]; do mine_one; done
fi

echo "[signet-miner] steady state: 1 block every ${INTERVAL}s"
while true; do
  mine_one
  sleep "$INTERVAL"
done
