"""Builder for the Ark ASP (Ark Service Provider).

Deployed *alongside* — not instead of — this network's LND liquidity ring and
Cashu/Fedimint stack. The pieces (all on the network's isolated compose project):

* **captaind** — Second's Ark server. Runs the Ark protocol (cheap, self-custodial
  off-chain VTXOs) and an on-chain wallet that seeds rounds. The published image
  bundles its own PostgreSQL, so this is a single container; its config
  (``captaind.toml``, generated here) points it at the network's bitcoind (RPC) and
  at the CLN bridge's gRPC + hold-invoice gRPC (mTLS, certs read from the shared
  ``cln`` volume).

* **cln** — a Core Lightning node (+ the Boltz hold-invoice plugin) built from
  source (see :mod:`argus.ark_cln`). It is captaind's Ark<->Lightning bridge and
  opens ONE channel into the ring (default ``argus1``), so Ark Lightning traffic
  rides the triangle's self-rebalancing channels — no separate liquidity
  machinery, which is what makes this work on networks Argus can't mine.

* **ark-setup** sidecar (captaind image) — once captaind is up, reads its on-chain
  ``rounds.address`` via ``captaind rpc`` and surfaces it as the deposit address to
  fund (external funding; Ark creates no coins).

* **ark-channel** sidecar (cln image) — surfaces the bridge's on-chain deposit
  address, then once funded connects to the target ring node (its identity pubkey
  read from the node's argus_liquidity.json) and opens the ``channel_btc`` channel.

Funding is external on every network (the operator/faucet sends coins to the two
printed addresses). Sidecar steps are guarded by marker files in the shared
``ark_state`` volume, so re-running ``docker compose up`` is idempotent.
"""

from __future__ import annotations

from ..ark_cln import ARK_CLN_IMAGE
from ..constants import (
    ARK_CLN_INTERNAL_PORTS,
    ARK_NETWORK_KEY,
    CAPTAIND_INTERNAL_PORTS,
    CHAIN_INTERNAL_PORTS,
    LND_INTERNAL_PORTS,
)
from ..context import BuildContext, Fragment


# --- Sidecar scripts --------------------------------------------------------

# Surface captaind's on-chain deposit address (rounds.address). captaind funds its
# rounds/VTXOs from this wallet; on a network Argus can't mine the operator/faucet
# seeds it. Idempotent: the address is stable, cached in the shared state volume.
_SETUP_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — surface the Ark server's on-chain deposit address.
set -eu

STATE=/state
ADDR_FILE="${STATE}/captaind_deposit.txt"

echo "[ark-setup] waiting for captaind admin RPC at ${CAPTAIND_ADDR}..."
until captaind rpc --addr "${CAPTAIND_ADDR}" wallet >/dev/null 2>&1; do sleep 5; done

if [ ! -s "${ADDR_FILE}" ]; then
  ADDR=$(captaind rpc --addr "${CAPTAIND_ADDR}" wallet 2>/dev/null \
         | grep -oE '(bcrt1|tb1|bc1)[a-z0-9]+' | head -1 || true)
  [ -n "${ADDR}" ] && printf '%s\\n' "${ADDR}" > "${ADDR_FILE}"
fi

if [ -s "${ADDR_FILE}" ]; then
  echo "[ark-setup] Ark server (captaind) on-chain deposit address:"
  cat "${ADDR_FILE}"
  echo "[ark-setup] FUND THIS (external funding) to seed Ark rounds/VTXOs."
  echo "[ark-setup] done"
else
  echo "[ark-setup] rounds.address not available yet; exiting to retry"
  exit 1
fi
"""

# Surface the CLN bridge's on-chain deposit address, then open one channel into
# the ring. The target ring node's identity pubkey is read from its LND data
# volume (argus_liquidity.json, written by the node's status sidecar). connect is
# idempotent; fundchannel is retried until the bridge is funded and the peer is
# reachable, and a marker makes the open one-shot.
_CHANNEL_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — fund-surface + open the Ark bridge's ring channel.
set -eu

STATE=/state
LCLI="lightning-cli --network=${NETWORK}"
ADDR_FILE="${STATE}/cln_deposit.txt"
DONE="${STATE}/channel_opened"

echo "[ark-channel] waiting for CLN..."
until $LCLI getinfo >/dev/null 2>&1; do sleep 5; done

if [ ! -s "${ADDR_FILE}" ]; then
  A=$($LCLI newaddr bech32 2>/dev/null \
      | grep -oE '(bcrt1|tb1|bc1)[a-z0-9]+' | head -1 || true)
  [ -n "$A" ] && printf '%s\\n' "$A" > "${ADDR_FILE}"
fi
if [ -s "${ADDR_FILE}" ]; then
  echo "[ark-channel] Ark Lightning bridge (CLN) on-chain deposit address:"
  cat "${ADDR_FILE}"
  echo "[ark-channel] FUND THIS with >= ${CHANNEL_BTC} BTC so the bridge can open"
  echo "[ark-channel] its ${CHANNEL_BTC} BTC channel into the ring (${TARGET_ALIAS})."
fi

if [ -f "${DONE}" ]; then
  echo "[ark-channel] channel already opened; nothing to do"; exit 0
fi

echo "[ark-channel] waiting for ${TARGET_ALIAS} (${TARGET_SVC}) identity pubkey..."
PUBKEY=""
while [ -z "${PUBKEY}" ]; do
  PUBKEY=$(grep -oE '"pubkey":"[0-9a-f]{66}"' /lnd/argus_liquidity.json 2>/dev/null \
           | grep -oE '[0-9a-f]{66}' | head -1 || true)
  [ -z "${PUBKEY}" ] && sleep 5
done
echo "[ark-channel] target ${TARGET_ALIAS} pubkey=${PUBKEY}"

i=0
while [ ! -f "${DONE}" ]; do
  $LCLI connect "${PUBKEY}@${TARGET_SVC}:${LND_P2P}" >/dev/null 2>&1 || true
  if $LCLI fundchannel id="${PUBKEY}" amount="${CHANNEL_SAT}sat" 2>&1 | grep -q '"txid"'; then
    touch "${DONE}"
    echo "[ark-channel] channel to ${TARGET_ALIAS} (${CHANNEL_SAT} sat) broadcast"
    break
  fi
  i=$((i + 1))
  echo "[ark-channel] not ready (bridge funded? peer synced?); retry ${i}"
  sleep 20
done
echo "[ark-channel] done"
"""


def _captaind_toml(ctx: BuildContext, ark_net: str, rpc_port: int) -> str:
    """Render captaind.toml for this network.

    Mirrors the layout of the published image's baked config but points bitcoind
    at the network's own node (RPC user/pass from the secret store, not the demo
    cookie) and the CLN gRPC/hold cert paths at this network's CLN dir
    (``/data/cln/<ark_net>/...``). The bundled PostgreSQL stays on localhost.
    Secrets are hex (no TOML-quote metacharacters), so plain quoting is safe.
    """
    p = CAPTAIND_INTERNAL_PORTS
    cp = ARK_CLN_INTERNAL_PORTS
    rpc_user = ctx.secrets["RPC_USER"]
    rpc_pass = ctx.secrets["RPC_PASSWORD"]
    return (
        "# Generated by Bitcoin Argus — captaind (Ark server) configuration.\n"
        'data_dir = "/data/captaind"\n'
        f'network = "{ark_net}"\n'
        "\n"
        "[bitcoind]\n"
        f'url = "bitcoind:{rpc_port}"\n'
        f'rpc_user = "{rpc_user}"\n'
        f'rpc_pass = "{rpc_pass}"\n'
        "\n"
        "[postgres]\n"
        '# Bundled with the captaind image (managed by its entrypoint).\n'
        'host = "localhost"\n'
        "port = 5432\n"
        'name = "bark-server-db"\n'
        'user = "postgres"\n'
        'password = "postgres"\n'
        "\n"
        "[rpc]\n"
        f'public_address = "0.0.0.0:{p["public"]}"\n'
        f'admin_address = "0.0.0.0:{p["admin"]}"\n'
        "\n"
        "[[cln_array]]\n"
        f'uri = "https://cln:{cp["grpc"]}"\n'
        "priority = 1\n"
        f'server_cert_path = "/data/cln/{ark_net}/ca.pem"\n'
        f'client_cert_path = "/data/cln/{ark_net}/client.pem"\n'
        f'client_key_path = "/data/cln/{ark_net}/client-key.pem"\n'
        f'hold_invoice.uri = "https://cln:{cp["hold"]}"\n'
        f'hold_invoice.server_cert_path = "/data/cln/{ark_net}/hold/ca.pem"\n'
        f'hold_invoice.client_cert_path = "/data/cln/{ark_net}/hold/client.pem"\n'
        f'hold_invoice.client_key_path = "/data/cln/{ark_net}/hold/client-key.pem"\n'
    )


def _cln_service(ctx: BuildContext, ark_net: str) -> dict:
    """The Core Lightning bridge node (+ Boltz hold plugin)."""
    cp = ARK_CLN_INTERNAL_PORTS
    environment = {
        "NETWORK": ark_net,
        "CLN_ALIAS": ctx.net.ark.cln_alias,
        # Host only: CLN defaults the bitcoind RPC port per network, which matches
        # our bitcoind's per-chain RPC port (regtest 18443, testnet 18332, etc.).
        "BITCOIN_RPCCONNECT": "bitcoind",
        "BITCOIN_RPCUSER": "${RPC_USER}",
        "BITCOIN_RPCPASSWORD": "${RPC_PASSWORD}",
    }
    environment.update(ctx.net.ark.extra_env)
    return {
        "build": {"context": "../ark-cln", "dockerfile": "Dockerfile"},
        "image": ARK_CLN_IMAGE,
        "container_name": f"{ctx.project}-cln",
        # Keep the hostname "cln": cln_start.sh then trusts CLN's default gRPC
        # server cert (valid for "cln"), which captaind dials as https://cln:9736.
        "hostname": "cln",
        "restart": "unless-stopped",
        "depends_on": {"bitcoind": {"condition": "service_healthy"}},
        "environment": environment,
        "volumes": ["ark_cln_data:/root/.lightning"],
        "ports": [
            f"0.0.0.0:{ctx.ports['ark_cln_p2p']}:{cp['p2p']}",  # PUBLIC LN node
            f"127.0.0.1:{ctx.ports['ark_cln_grpc']}:{cp['grpc']}",  # debug
            f"127.0.0.1:{ctx.ports['ark_cln_hold']}:{cp['hold']}",  # debug
        ],
        "healthcheck": {
            "test": ["CMD-SHELL", f"lightning-cli --network={ark_net} getinfo || exit 1"],
            "interval": "15s",
            "timeout": "10s",
            "retries": 10,
            "start_period": "120s",
        },
        "networks": [ctx.network_name],
    }


def _captaind_service(ctx: BuildContext) -> dict:
    """The Ark server (captaind, bundled PostgreSQL)."""
    p = CAPTAIND_INTERNAL_PORTS
    return {
        "image": "${ARK_CAPTAIND_IMAGE}",
        "container_name": f"{ctx.project}-captaind",
        "restart": "unless-stopped",
        "depends_on": {
            "bitcoind": {"condition": "service_healthy"},
            "cln": {"condition": "service_healthy"},
        },
        # The image's entrypoint (start.sh) starts the bundled postgres, runs
        # `captaind create` once, then `captaind start`, all against this config.
        "environment": {"CAPTAIND_CONFIG": "/config/captaind.toml"},
        "volumes": [
            "./ark/captaind.toml:/config/captaind.toml:ro",
            "ark_captaind_data:/data/captaind",
            "ark_captaind_pg:/var/lib/postgresql/data",
            # CLN's gRPC + hold mTLS certs (read-only); captaind connects with them.
            "ark_cln_data:/data/cln:ro",
        ],
        # gRPC API on loopback (the shared Caddy fronts it publicly via h2c) and the
        # admin RPC on loopback (operator/debug; the sidecar reaches it internally).
        "ports": [
            f"127.0.0.1:{ctx.ports['ark_captaind']}:{p['public']}",
            f"127.0.0.1:{ctx.ports['ark_captaind_admin']}:{p['admin']}",
        ],
        "healthcheck": {
            "test": [
                "CMD-SHELL",
                f"captaind rpc --addr 127.0.0.1:{p['admin']} wallet || exit 1",
            ],
            "interval": "15s",
            "timeout": "10s",
            "retries": 10,
            "start_period": "180s",
        },
        "networks": [ctx.network_name],
    }


def build_ark(ctx: BuildContext) -> Fragment:
    net = ctx.net
    ark_net = ARK_NETWORK_KEY[ctx.spec.chain]
    rpc_port = CHAIN_INTERNAL_PORTS[ctx.spec.chain]["rpc"]
    p = CAPTAIND_INTERNAL_PORTS

    target_alias, target_svc, target_vol = net.ark_channel_target(ctx.spec)
    channel_btc = net.ark.channel.channel_btc
    channel_sat = round(channel_btc * 1e8)

    # Write the captaind config + sidecar scripts into the per-network context.
    conf_dir = ctx.out_dir / "ark"
    conf_dir.mkdir(parents=True, exist_ok=True)
    (conf_dir / "captaind.toml").write_text(_captaind_toml(ctx, ark_net, rpc_port))
    (conf_dir / "ark-setup.sh").write_text(_SETUP_SH)
    (conf_dir / "ark-channel.sh").write_text(_CHANNEL_SH)

    services: dict[str, dict] = {
        "cln": _cln_service(ctx, ark_net),
        "captaind": _captaind_service(ctx),
    }

    # Deposit-address sidecar (captaind image — it bundles the captaind binary).
    services["ark-setup"] = {
        "image": "${ARK_CAPTAIND_IMAGE}",
        "container_name": f"{ctx.project}-ark-setup",
        "restart": "on-failure",
        "depends_on": {"captaind": {"condition": "service_healthy"}},
        "entrypoint": ["/bin/sh", "/scripts/ark-setup.sh"],
        "environment": {"CAPTAIND_ADDR": f"captaind:{p['admin']}"},
        "volumes": [
            "./ark/ark-setup.sh:/scripts/ark-setup.sh:ro",
            "ark_state:/state",
        ],
        "networks": [ctx.network_name],
    }

    # Channel sidecar (cln image — it has lightning-cli). Reads the target ring
    # node's pubkey from its data volume (read-only) and opens the bridge channel.
    services["ark-channel"] = {
        "image": ARK_CLN_IMAGE,
        "container_name": f"{ctx.project}-ark-channel",
        "restart": "on-failure",
        "depends_on": {
            "cln": {"condition": "service_healthy"},
            target_svc: {"condition": "service_healthy"},
        },
        "entrypoint": ["/bin/sh", "/scripts/ark-channel.sh"],
        "environment": {
            "NETWORK": ark_net,
            "TARGET_ALIAS": target_alias,
            "TARGET_SVC": target_svc,
            "LND_P2P": str(LND_INTERNAL_PORTS["p2p"]),
            "CHANNEL_BTC": f"{channel_btc:g}",
            "CHANNEL_SAT": str(channel_sat),
        },
        "volumes": [
            "./ark/ark-channel.sh:/scripts/ark-channel.sh:ro",
            "ark_cln_data:/root/.lightning",
            f"{target_vol}:/lnd:ro",
            "ark_state:/state",
        ],
        "networks": [ctx.network_name],
    }

    volumes = {
        "ark_cln_data": {},
        "ark_captaind_data": {},
        "ark_captaind_pg": {},
        "ark_state": {},
    }

    return Fragment(
        services=services,
        volumes=volumes,
        env={
            "ARK_CAPTAIND_IMAGE": ctx.cfg.global_.ark_captaind_image,
            # CLN reads these for its bitcoind RPC auth (same node the ring uses).
            "RPC_USER": ctx.secrets["RPC_USER"],
            "RPC_PASSWORD": ctx.secrets["RPC_PASSWORD"],
        },
    )
