"""Builder for the Bitcoin Core (or Knots) node.

Emits a ``bitcoin.conf`` (so we avoid fragile long command lines and YAML/shell
escaping of user args) plus a compose service. RPC is published on 127.0.0.1
only; ZMQ stays on the internal compose network (LND reaches it by service name).
"""

from __future__ import annotations

from ..constants import (
    CHAIN_INTERNAL_PORTS,
    ZMQ_BLOCK_INTERNAL,
    ZMQ_TX_INTERNAL,
)
from ..context import BuildContext, Fragment

# Networks whose regtest/signet wallet needs a fallback fee to create transactions.
_FALLBACKFEE_CHAINS = {"regtest", "signet", "test", "testnet4"}

# Self-rebind P2P gate (regtest auto-channels): run bitcoind with no inbound P2P
# listener until LND channel setup writes the shared marker, then restart with
# P2P open. Mining/funding use RPC + ZMQ (unaffected by -listen), so the chain is
# private exactly while channels are being funded — no host firewall step needed.
_GATE_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — regtest P2P self-gate.
set -u
MARKER=/state/channels
if [ ! -f "$MARKER" ]; then
  echo "[bitcoind-gate] P2P closed (no inbound listener) until LND channels are set up"
  bitcoind "$@" -listen=0 &
  BPID=$!
  while [ ! -f "$MARKER" ]; do
    kill -0 "$BPID" 2>/dev/null || { wait "$BPID"; exit $?; }
    sleep 5
  done
  echo "[bitcoind-gate] channels ready — restarting with P2P open"
  kill "$BPID" 2>/dev/null
  wait "$BPID" 2>/dev/null
fi
exec bitcoind "$@"
"""


def _sanitize_conf_arg(arg: str) -> str:
    """Turn an operator-supplied flag into a safe ``key=value`` conf line.

    Accepts ``-foo=bar``, ``foo=bar``, ``-foo`` (=> ``foo=1``). Rejects newlines
    to prevent injecting extra config directives.
    """
    if "\n" in arg or "\r" in arg:
        raise ValueError(f"bitcoind extra_arg contains a newline: {arg!r}")
    cleaned = arg.strip().lstrip("-")
    if not cleaned:
        raise ValueError("empty bitcoind extra_arg")
    if "=" not in cleaned:
        cleaned = f"{cleaned}=1"
    return cleaned


def _render_conf(ctx: BuildContext) -> str:
    spec = ctx.spec
    net = ctx.net
    chain = spec.chain
    internal = CHAIN_INTERNAL_PORTS[chain]
    # For a self-mined custom signet the challenge is auto-generated into the
    # secret store (matched with the miner's signing key); fall back to that.
    challenge = (
        net.signet_challenge
        or ctx.secrets.get("SIGNET_CHALLENGE")
        or spec.default_signet_challenge
    )

    lines: list[str] = [
        "# Generated by Bitcoin Argus — do not edit by hand.",
        f"chain={chain}",
        "server=1",
        "listen=1",  # accept inbound P2P (the P2P port is published publicly)
    ]
    if net.prune > 0:
        lines.append(f"prune={net.prune}")
    else:
        # txindex is required by Fulcrum/mempool and harmless otherwise.
        lines.append("txindex=1")
    lines += [
        f"rpcuser={ctx.secrets['RPC_USER']}",
        f"rpcpassword={ctx.secrets['RPC_PASSWORD']}",
        # Resource tuning (profile/overrides resolved in argus.resources).
        f"dbcache={ctx.resources.bitcoind_dbcache}",
        f"maxmempool={ctx.resources.bitcoind_maxmempool}",
    ]
    for arg in net.bitcoind.extra_args:
        lines.append(_sanitize_conf_arg(arg))

    # Per-chain section. rpcallowip is broad but RPC is only reachable on the
    # isolated compose network and via 127.0.0.1 on the host (never the internet).
    lines += [
        "",
        f"[{chain}]",
        "rpcbind=0.0.0.0",
        "rpcallowip=0.0.0.0/0",
        f"rpcport={internal['rpc']}",
        f"port={internal['p2p']}",
        f"zmqpubrawblock=tcp://0.0.0.0:{ZMQ_BLOCK_INTERNAL}",
        f"zmqpubrawtx=tcp://0.0.0.0:{ZMQ_TX_INTERNAL}",
    ]
    if net.bitcart.enabled:
        # BIP157 compact block filters so Bitcart's Neutrino LND can sync
        # against this node (works on every network, regtest included).
        lines += ["blockfilterindex=1", "peerblockfilters=1"]
    if chain in _FALLBACKFEE_CHAINS:
        lines.append("fallbackfee=0.00001")
    if challenge:
        lines.append(f"signetchallenge={challenge}")
    if spec.signetblocktime is not None:
        # Knots-only knob; Mutinynet's 30s blocks.
        lines.append(f"signetblocktime={spec.signetblocktime}")
    if ctx.net_key == "mutinynet" or spec.requires_challenge:
        # Isolated custom signet: don't waste time on the public signet DNS seeds
        # (a different challenge means a different network anyway).
        lines.append("dnsseed=0")
    for node in (*spec.default_addnodes, *net.addnode):
        lines.append(f"addnode={node}")

    return "\n".join(lines) + "\n"


def build_bitcoind(ctx: BuildContext) -> Fragment:
    internal = CHAIN_INTERNAL_PORTS[ctx.spec.chain]

    # Write the conf next to the compose file (gitignored output dir).
    conf_dir = ctx.out_dir / "bitcoin"
    conf_dir.mkdir(parents=True, exist_ok=True)
    (conf_dir / "bitcoin.conf").write_text(_render_conf(ctx))

    image_var = "BITCOIND_IMAGE"
    image = (
        ctx.cfg.global_.bitcoind_knots_image
        if ctx.spec.needs_knots
        else ctx.cfg.global_.bitcoind_image
    )

    rpc_host_port = ctx.ports["bitcoind_rpc"]
    gated = ctx.net.bitcoind_p2p_gated(ctx.net_key, ctx.spec)
    p2p_host_port = ctx.ports["bitcoind_p2p"]
    # RPC is always closed (loopback only). The P2P port is published normally;
    # when gated, bitcoind itself keeps the inbound listener closed (see below)
    # until LND channels are set up, so no host firewall step is involved.
    port_maps = [f"127.0.0.1:{rpc_host_port}:{internal['rpc']}"]
    if ctx.net.bitcoind.p2p_public:
        # Public so peers can connect their own node (firewall opens it).
        port_maps.append(f"{p2p_host_port}:{internal['p2p']}")
    else:
        # Loopback only (operator-only) — e.g. to stop strangers reorging regtest.
        port_maps.append(f"127.0.0.1:{p2p_host_port}:{internal['p2p']}")

    volumes = [
        "bitcoind_data:/data",
        "./bitcoin/bitcoin.conf:/data/bitcoin.conf:ro",
    ]
    service = {
        "image": f"${{{image_var}}}",
        "container_name": f"{ctx.project}-bitcoind",
        "restart": "unless-stopped",
        # Run bitcoind directly. This bypasses the official bitcoin/bitcoin image's
        # /entrypoint.sh, which would force its own -datadir (overriding our /data
        # volume) and drop to an unprivileged user (breaking writes to /data). It
        # is also correct for lncm/bitcoind (whose entrypoint is bitcoind anyway).
        # bitcoind runs fine as root in the container; the gated path overrides this
        # with its wrapper, which likewise execs bitcoind directly.
        "entrypoint": ["bitcoind"],
        "command": ["-datadir=/data", "-conf=/data/bitcoin.conf"],
        "volumes": volumes,
        "ports": port_maps,
        "networks": [ctx.network_name],
        "healthcheck": {
            "test": [
                "CMD-SHELL",
                "bitcoin-cli -datadir=/data -conf=/data/bitcoin.conf "
                "getblockchaininfo >/dev/null 2>&1 || exit 1",
            ],
            "interval": "15s",
            "timeout": "10s",
            "retries": 10,
            "start_period": "30s",
        },
    }

    if gated:
        # Auto-gate: bitcoind holds its P2P listener closed until the lnd-channels
        # marker appears in the shared state volume, then restarts with P2P open.
        # Replaces the image's `bitcoind` entrypoint with the wrapper; `command`
        # (the conf args) is passed through as "$@".
        (conf_dir / "bitcoind-gate.sh").write_text(_GATE_SH)
        service["entrypoint"] = ["/bin/sh", "/scripts/bitcoind-gate.sh"]
        volumes.append("./bitcoin/bitcoind-gate.sh:/scripts/bitcoind-gate.sh:ro")
        volumes.append("lnd_setup_state:/state:ro")

    return Fragment(
        services={"bitcoind": service},
        volumes={"bitcoind_data": {}},
        env={image_var: image},
    )
