"""Builder for the donations / coin-recycling sidecar.

Every enabled network gets a single bitcoind wallet. On the *mined* networks
(regtest -> ``miner``, custom-signet -> ``signer``) that wallet already exists and
receives the mined coinbase, so this sidecar reuses it — it must NOT recreate it
(recreating ``signer`` would lose the block-signing descriptor, and recreating
either could race the miner). On the non-mined networks bitcoind has no wallet of
its own, so the sidecar creates a plain ``donation`` wallet.

In that single wallet it derives one *stable, reused* receive address (label
``donation``) — the public donation address shown on the dashboard. Mined coins
and donated coins live together in the wallet; there is no separation. The
operator sweeps the wallet back to the faucet whenever they like.

The sidecar then writes ``{address, total_received, balance}`` to a small JSON
file on a fixed interval. ``total_received`` is the lifetime received at the
donation address (``getreceivedbyaddress`` — keeps climbing even after a sweep);
``balance`` is the whole wallet's balance. The dashboard reads that file through
the read-only docker-socket-proxy (``get_archive``), the same trick it uses for
LND pubkeys, so no RPC credentials reach the public-facing web container.
"""

from __future__ import annotations

from ..constants import CHAIN_INTERNAL_PORTS
from ..context import BuildContext, Fragment

# bitcoin-cli network selector per bitcoind ``chain`` value.
_CHAIN_FLAG: dict[str, str] = {
    "regtest": "-regtest",
    "test": "-testnet",
    "testnet4": "-testnet4",
    "signet": "-signet",
}

# How often the sidecar refreshes the figures. The dashboard caches them for an
# hour anyway, so this only bounds how stale the file can be between refreshes.
DONATIONS_INTERVAL_SECONDS = 300

DONATIONS_STATE_FILE = "/state/donations.json"

_DONATIONS_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — donation address + figures writer.
set -u

CLI="bitcoin-cli ${CHAIN_FLAG} -rpcconnect=${RPC_CONNECT} -rpcport=${RPC_PORT} \
-rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD}"
STATE=/state
OUT="${STATE}/donations.json"
ADDRF="${STATE}/donation_address"
LABEL=donation

echo "[donations] waiting for bitcoind RPC..."
until $CLI getblockchaininfo >/dev/null 2>&1; do sleep 2; done

# Get the single wallet ready. On mined networks the miner owns it, so only wait
# for it (never create — that would race the miner / drop the signing key). On
# non-mined networks bitcoind has no wallet, so create a plain one.
if [ "${CREATE_WALLET}" = "1" ]; then
  $CLI -named createwallet wallet_name=${WALLET} load_on_startup=true >/dev/null 2>&1 \\
    || $CLI loadwallet ${WALLET} >/dev/null 2>&1 || true
else
  echo "[donations] waiting for wallet '${WALLET}' (owned by the miner)..."
  until $CLI -rpcwallet=${WALLET} getwalletinfo >/dev/null 2>&1; do
    $CLI loadwallet ${WALLET} >/dev/null 2>&1 || true
    sleep 5
  done
fi

WCLI="${CLI} -rpcwallet=${WALLET}"

# Derive a stable donation address, reused across restarts. Prefer the one we
# persisted; re-derive only if it's missing or no longer belongs to the wallet
# (e.g. the wallet volume was wiped while /state survived).
ADDR=""
if [ -s "${ADDRF}" ]; then
  ADDR=$(cat "${ADDRF}")
  $WCLI getaddressinfo "${ADDR}" 2>/dev/null | grep -q '"ismine": *true' || ADDR=""
fi
if [ -z "${ADDR}" ]; then
  echo "[donations] deriving a fresh donation address..."
  until ADDR=$($WCLI getnewaddress "${LABEL}" 2>/dev/null); do sleep 5; done
  printf '%s' "${ADDR}" > "${ADDRF}"
fi
echo "[donations] donation address ${ADDR}"

write_json() {
  # Skip the write on any transient RPC failure so we keep the last good file.
  RECEIVED=$($WCLI getreceivedbyaddress "${ADDR}" 0 2>/dev/null) || return
  BAL=$($WCLI getbalance 2>/dev/null) || return
  [ -n "${RECEIVED}" ] && [ -n "${BAL}" ] || return
  printf '{"address":"%s","total_received":"%s","balance":"%s"}\\n' \\
    "${ADDR}" "${RECEIVED}" "${BAL}" > "${OUT}.tmp"
  mv "${OUT}.tmp" "${OUT}"
}

echo "[donations] writing figures every ${INTERVAL}s"
while true; do
  write_json
  sleep "${INTERVAL}"
done
"""


def _wallet_plan(ctx: BuildContext) -> tuple[str, bool]:
    """Return ``(wallet_name, create)`` for this network's single wallet.

    Mined networks reuse the miner's wallet and must not recreate it; non-mined
    networks get a plain ``donation`` wallet that this sidecar creates.
    """
    miner_runs = ctx.spec.supports_miner and ctx.net.miner.enabled
    if miner_runs:
        return ("miner" if ctx.spec.chain == "regtest" else "signer"), False
    return "donation", True


def build_donations(ctx: BuildContext) -> Fragment:
    chain = ctx.spec.chain
    flag = _CHAIN_FLAG.get(chain)
    if flag is None:  # defensive; every known chain is mapped above
        raise NotImplementedError(f"donations sidecar: unknown chain {chain!r}")

    wallet, create = _wallet_plan(ctx)

    script_dir = ctx.out_dir / "donations"
    script_dir.mkdir(parents=True, exist_ok=True)
    (script_dir / "donations.sh").write_text(_DONATIONS_SH)

    service = {
        "image": "${BITCOIND_IMAGE}",
        "container_name": f"{ctx.project}-donations",
        "restart": "unless-stopped",
        # Root so it can write the state volume (created root-owned; the bitcoind
        # image otherwise runs as a non-root user). It only reads via RPC + writes
        # its own small JSON, mirroring the lnd-setup sidecar.
        "user": "0:0",
        "depends_on": {"bitcoind": {"condition": "service_healthy"}},
        "entrypoint": ["/bin/sh", "/scripts/donations.sh"],
        "volumes": [
            "./donations/donations.sh:/scripts/donations.sh:ro",
            "donations_state:/state",
        ],
        "environment": {
            "CHAIN_FLAG": flag,
            "RPC_CONNECT": "bitcoind",
            "RPC_PORT": str(CHAIN_INTERNAL_PORTS[chain]["rpc"]),
            "RPC_USER": "${RPC_USER}",
            "RPC_PASSWORD": "${RPC_PASSWORD}",
            "WALLET": wallet,
            "CREATE_WALLET": "1" if create else "0",
            "INTERVAL": str(DONATIONS_INTERVAL_SECONDS),
        },
        "networks": [ctx.network_name],
    }

    return Fragment(
        services={"donations": service},
        volumes={"donations_state": {}},
    )
