"""Builder for the Electrum submarine-swap provider + its local Nostr relay.

Deployed *alongside* this network's LND liquidity ring. The pieces (all on the
network's isolated compose project):

* **electrum** — one Electrum wallet (built from source, see :mod:`argus.electrum`)
  running headless as a submarine-swap **server**. Electrum's Lightning is a
  non-routing client, so it can't join the ring's circular-rebalancing triangle;
  instead it opens ONE channel into the ring (``electrum.target_node``, 50/50 from
  the start via ``--push_amount``) and holds a large on-chain ``reserve_btc`` — the
  fuel a swap server self-heals with, swapping on-chain<->Lightning rather than
  routing. Attaching to the (announced, internet-reachable, self-rebalancing) ring
  gives external testers a routable path to reach it. It runs the ``swapserver``
  plugin (Electrum >= 4.6), announcing offers on the local relay below.

* **nostr-relay** — a single-purpose relay (see :mod:`argus.nostr_relay`) the swap
  provider announces on. It accepts ONLY the two Electrum swap kinds (30315 offer +
  25582 negotiation) and expires events older than ``relay.retention_hours``. Its
  WebSocket is fronted publicly by the shared Caddy (wss) so outside testers can
  discover the provider and run swaps against it.

* **electrum-fund** sidecar (bitcoind image) — on a network Argus mines
  (``funding: auto``) it funds the wallet's on-chain address with
  ``reserve_btc + channel_btc`` from the miner/signer wallet; on ``external`` it is
  omitted and the operator sends coins to the address the entrypoint prints.

The entrypoint provisions the wallet, opens the ring channel once funded, and then
blocks as PID 1 (so the swap server keeps running); sidecar/step state is guarded
by marker files in the shared ``electrum_state`` volume, so re-running
``docker compose up`` is idempotent.
"""

from __future__ import annotations

from ..constants import (
    CHAIN_INTERNAL_PORTS,
    ELECTRUM_INTERNAL_PORTS,
    ELECTRUM_NETWORK_FLAG,
    FULCRUM_INTERNAL_PORTS,
    LND_INTERNAL_PORTS,
    NOSTR_RELAY_INTERNAL_PORT,
)
from ..context import BuildContext, Fragment
from ..electrum import ELECTRUM_IMAGE
from ..nostr_relay import (
    RELAY_CONFIG_PATH,
    RELAY_DB_DIR,
    render_relay_conf,
    render_retention_sweep,
)


# --- Electrum entrypoint (PID 1 of the electrum container) -------------------
#
# Runs from a mounted file (not an inline entrypoint) so Compose's variable
# interpolation never mangles the shell ``$`` references. All Electrum CLI calls
# share the container's datadir, so the CLI reaches the backgrounded daemon over
# its own loopback RPC automatically — no cross-container RPC/credentials needed.
_ENTRYPOINT_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — Electrum swap-server provisioning + supervision.
set -u

E="electrum --${NET_FLAG} -D /data"
STATE=/state

log() { echo "[electrum] $*"; }

# --- 1. Static config (offline; writes the config file before the daemon) -----
$E setconfig log_to_file true >/dev/null 2>&1 || true
# Use this network's own Fulcrum as the (only) Electrum server, plaintext TCP.
$E setconfig server "${ELECTRUM_SERVER}" >/dev/null 2>&1 || true
$E setconfig oneserver true >/dev/null 2>&1 || true
# Gossip so the wallet can pathfind for swap payouts (vs. hardcoded trampolines).
$E setconfig use_gossip true >/dev/null 2>&1 || true
# The swap server: announce + negotiate over the local relay, with our fee + PoW.
$E setconfig nostr_relays "${NOSTR_RELAYS}" >/dev/null 2>&1 || true
$E setconfig plugins.swapserver.enabled true >/dev/null 2>&1 || true
$E setconfig plugins.swapserver.fee_millionths "${FEE_MILLIONTHS}" >/dev/null 2>&1 || true
$E setconfig swapserver_pow_target "${POW_TARGET}" >/dev/null 2>&1 || true
__EXTRA_CONFIG__

# --- 2. Wallet (unencrypted => always unlocked, required by the swap server) ---
if [ ! -f "${STATE}/created" ]; then
  log "creating wallet (segwit, unencrypted — testnet only)"
  $E create >/dev/null 2>&1 && : > "${STATE}/created"
fi

# --- 3. Start the daemon and load the wallet ----------------------------------
# `electrum daemon` (no -d) runs in the FOREGROUND — we background it as a shell
# job (so this script stays PID 1 and can drive the CLI over the daemon's own
# loopback RPC), then `wait` on it at the end. `-d` would detach/fork and the
# container would exit, so it is deliberately NOT used.
log "starting daemon"
$E daemon &
DAEMON_PID=$!
log "waiting for daemon RPC..."
until $E getinfo >/dev/null 2>&1; do sleep 2; done
# Loading the wallet into THIS running daemon is what starts the swap server
# (an unencrypted wallet is always unlocked, which the swap server requires).
$E load_wallet >/dev/null 2>&1 || true

# --- 4. Publish the on-chain deposit address + LN node id for the funder -------
if [ ! -s "${STATE}/electrum_addr.txt" ]; then
  A=$($E getunusedaddress 2>/dev/null | tr -d '"[:space:]')
  [ -n "$A" ] && printf '%s' "$A" > "${STATE}/electrum_addr.txt"
fi
NID=$($E nodeid 2>/dev/null | tr -d '"[:space:]')
[ -n "$NID" ] && printf '%s' "$NID" > "${STATE}/electrum_nodeid.txt"
ADDR=$(cat "${STATE}/electrum_addr.txt" 2>/dev/null || echo "")
if [ "${FUNDING}" = "external" ]; then
  log "EXTERNAL funding — send >= ${NEED_BTC} BTC on-chain to: ${ADDR}"
else
  log "on-chain deposit address: ${ADDR} (funded automatically)"
fi

# --- 5. Wait for on-chain funds, then open ONE 50/50 channel into the ring -----
confirmed() {
  $E getbalance 2>/dev/null | grep -o '"confirmed": *"[0-9.]*"' \
    | grep -oE '[0-9.]+' | head -1
}
ge_channel() {  # confirmed balance >= channel size (+ a little for fees)?
  awk "BEGIN{c=\\"$(confirmed)\\"+0; exit !(c >= ${CHANNEL_BTC} + 0.001)}"
}

if [ ! -f "${STATE}/channel_opened" ]; then
  log "waiting for >= ${CHANNEL_BTC} BTC confirmed to open the ring channel..."
  until ge_channel; do sleep 10; done

  log "waiting for target ring node ${TARGET_ALIAS} (${TARGET_SVC}) pubkey..."
  PUBKEY=""
  while [ -z "$PUBKEY" ]; do
    PUBKEY=$(grep -oE '"pubkey":"[0-9a-f]{66}"' /lnd/argus_liquidity.json 2>/dev/null \
             | grep -oE '[0-9a-f]{66}' | head -1 || true)
    [ -z "$PUBKEY" ] && sleep 5
  done
  PEER="${PUBKEY}@${TARGET_SVC}:${LND_P2P}"
  log "opening ${CHANNEL_BTC} BTC channel to ${TARGET_ALIAS} (push ${PUSH_BTC} => 50/50)"
  $E add_peer "$PEER" >/dev/null 2>&1 || true
  i=0
  while [ ! -f "${STATE}/channel_opened" ]; do
    if $E open_channel "$PEER" "${CHANNEL_BTC}" --push_amount "${PUSH_BTC}" >/dev/null 2>&1; then
      : > "${STATE}/channel_opened"
      log "ring channel broadcast"
      break
    fi
    i=$((i + 1)); log "channel open not ready (funds/peer sync?); retry ${i}"; sleep 20
  done
fi

# --- 6. Supervise: write a periodic status snapshot while the daemon lives, and
# keep PID 1 tied to the daemon so a crash restarts the container.
LIQ="${STATE}/electrum_status.json"
log "swap server up; supervising daemon"
( while kill -0 "$DAEMON_PID" 2>/dev/null; do
    BAL=$($E getbalance 2>/dev/null | tr -d '\\n')
    NCH=$($E list_channels 2>/dev/null | grep -c '"channel_id"' || echo 0)
    printf '{"nodeid":"%s","address":"%s","num_channels":%s,"balance":%s}\\n' \
      "${NID}" "${ADDR}" "${NCH:-0}" "${BAL:-{}}" > "${LIQ}.tmp" 2>/dev/null \
      && mv "${LIQ}.tmp" "${LIQ}" 2>/dev/null || true
    sleep "${STATUS_INTERVAL}"
  done ) &

wait "$DAEMON_PID"
log "daemon exited; container will restart"
exit 1
"""

# --- Funding sidecar (bitcoind image; ``auto`` funding only) -----------------
#
# Sends reserve_btc + channel_btc to the Electrum wallet's address from the
# miner/signer wallet, mining to maturity/confirmation on regtest. Mirrors the LND
# ring's lnd-setup. Idempotent via the shared-state marker.
_FUND_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — fund the Electrum swap wallet's on-chain address.
set -eu

CLI="bitcoin-cli ${CHAIN_FLAG} -rpcconnect=${RPC_CONNECT} -rpcport=${RPC_PORT} \
-rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD}"
WCLI="${CLI} -rpcwallet=${FUNDING_WALLET}"
STATE=/state

if [ -f "${STATE}/electrum_funded" ]; then
  echo "[electrum-fund] already funded; nothing to do"; exit 0
fi

echo "[electrum-fund] waiting for bitcoind RPC..."
until $CLI getblockchaininfo >/dev/null 2>&1; do sleep 2; done

echo "[electrum-fund] waiting for funding wallet '${FUNDING_WALLET}'..."
until $WCLI getwalletinfo >/dev/null 2>&1; do
  $CLI loadwallet "${FUNDING_WALLET}" >/dev/null 2>&1 || true
  sleep 3
done

echo "[electrum-fund] waiting for the Electrum deposit address..."
until [ -s "${STATE}/electrum_addr.txt" ]; do sleep 3; done
ADDR=$(cat "${STATE}/electrum_addr.txt")

NEED=${NEED_BTC}
echo "[electrum-fund] need >= ${NEED} BTC in ${FUNDING_WALLET}; addr ${ADDR}"
enough() { awk "BEGIN{exit !($($WCLI getbalance) >= ${NEED})}"; }

if [ "${CAN_MINE}" = "1" ]; then
  MADDR=$($WCLI getnewaddress)
  while ! enough; do
    echo "[electrum-fund] mining to mature funds (balance $($WCLI getbalance))"
    $CLI generatetoaddress 20 "$MADDR" >/dev/null
  done
else
  echo "[electrum-fund] waiting for the signer to accumulate matured coins..."
  while ! enough; do echo "  balance $($WCLI getbalance)"; sleep 10; done
fi

echo "[electrum-fund] sending ${NEED} BTC to ${ADDR}"
$WCLI -named sendtoaddress address="$ADDR" amount=${NEED} fee_rate=2 >/dev/null
if [ "${CAN_MINE}" = "1" ]; then
  echo "[electrum-fund] confirming"
  $CLI generatetoaddress 6 "$MADDR" >/dev/null
fi

touch "${STATE}/electrum_funded"
echo "[electrum-fund] funding complete"
"""


def _electrum_service(ctx: BuildContext) -> dict:
    net, spec = ctx.net, ctx.spec
    chain = spec.chain
    ep = ELECTRUM_INTERNAL_PORTS
    net_flag = ELECTRUM_NETWORK_FLAG[chain]

    indexer = net.enabled_indexers()[0]  # validated: >= 1 when electrum is on
    electrum_server = f"{indexer.name}:{FULCRUM_INTERNAL_PORTS['tcp']}:t"

    # The relay list the swap server announces on: the local relay (in-cluster ws)
    # first, then any operator-configured extras (e.g. public relays).
    relays = []
    if net.electrum_relay_enabled(spec):
        relays.append(f"ws://nostr-relay:{NOSTR_RELAY_INTERNAL_PORT}")
    relays += list(net.electrum.relay.extra_relays)
    nostr_relays = ",".join(relays)

    target_alias, target_svc, target_vol = net.electrum_channel_target(spec)
    channel_btc = net.electrum.channel_btc
    push_btc = channel_btc / 2.0
    need_btc = net.electrum.reserve_btc + channel_btc

    depends: dict[str, dict] = {
        "bitcoind": {"condition": "service_healthy"},
        indexer.name: {"condition": "service_healthy"},
        target_svc: {"condition": "service_healthy"},
    }
    if net.electrum_relay_enabled(spec):
        depends["nostr-relay"] = {"condition": "service_started"}

    return {
        "build": {"context": "../electrum", "dockerfile": "Dockerfile"},
        "image": ELECTRUM_IMAGE,
        "container_name": f"{ctx.project}-electrum",
        "restart": "unless-stopped",
        "depends_on": depends,
        "entrypoint": ["/bin/sh", "/scripts/electrum-entrypoint.sh"],
        "environment": {
            "NET_FLAG": net_flag,
            "ELECTRUM_SERVER": electrum_server,
            "NOSTR_RELAYS": nostr_relays,
            "FEE_MILLIONTHS": str(net.electrum.fee_millionths),
            "POW_TARGET": str(net.electrum.pow_target),
            "FUNDING": net.electrum_funding_mode(spec),
            "CHANNEL_BTC": f"{channel_btc:g}",
            "PUSH_BTC": f"{push_btc:g}",
            "NEED_BTC": f"{need_btc:g}",
            "TARGET_ALIAS": target_alias,
            "TARGET_SVC": target_svc,
            "LND_P2P": str(LND_INTERNAL_PORTS["p2p"]),
            "STATUS_INTERVAL": "30",
        },
        "volumes": [
            "electrum_data:/data",
            "electrum_state:/state",
            "./electrum/electrum-entrypoint.sh:/scripts/electrum-entrypoint.sh:ro",
            # The target ring node's data volume (read-only) — the entrypoint reads
            # its identity pubkey from argus_liquidity.json to open the channel.
            f"{target_vol}:/lnd:ro",
        ],
        # JSON-RPC on loopback only (debug); swaps ride nostr, not this port.
        "ports": [f"127.0.0.1:{ctx.ports['electrum_rpc']}:{ep['rpc']}"],
        "networks": [ctx.network_name],
    }


def _fund_service(ctx: BuildContext) -> dict:
    chain = ctx.spec.chain
    rpc_internal = CHAIN_INTERNAL_PORTS[chain]["rpc"]
    can_mine = chain == "regtest"
    funding_wallet = "miner" if chain == "regtest" else "signer"
    need_btc = ctx.net.electrum.reserve_btc + ctx.net.electrum.channel_btc
    return {
        "image": "${BITCOIND_IMAGE}",
        "container_name": f"{ctx.project}-electrum-fund",
        # Root to write the shared-state marker (the state volume is root-owned and
        # shared with the electrum container, whose UID differs).
        "user": "0:0",
        "restart": "on-failure",
        "depends_on": {
            "bitcoind": {"condition": "service_healthy"},
            "electrum": {"condition": "service_started"},
        },
        "entrypoint": ["/bin/sh", "/scripts/electrum-fund.sh"],
        "environment": {
            "CHAIN_FLAG": "-regtest" if chain == "regtest" else "-signet",
            "CAN_MINE": "1" if can_mine else "0",
            "FUNDING_WALLET": funding_wallet,
            "RPC_CONNECT": "bitcoind",
            "RPC_PORT": str(rpc_internal),
            "RPC_USER": "${RPC_USER}",
            "RPC_PASSWORD": "${RPC_PASSWORD}",
            "NEED_BTC": f"{need_btc:g}",
        },
        "volumes": [
            "./electrum/electrum-fund.sh:/scripts/electrum-fund.sh:ro",
            "electrum_state:/state",
        ],
        "networks": [ctx.network_name],
    }


def _relay_service(ctx: BuildContext) -> dict:
    rp = NOSTR_RELAY_INTERNAL_PORT
    return {
        "image": "${NOSTR_RELAY_IMAGE}",
        "container_name": f"{ctx.project}-nostr-relay",
        "restart": "unless-stopped",
        "user": "0:0",  # write the SQLite store on the shared (root-owned) volume
        "volumes": [
            f"nostr_relay_data:{RELAY_DB_DIR}",
            f"./nostr-relay/config.toml:{RELAY_CONFIG_PATH}:ro",
        ],
        # WebSocket backend on loopback; the host-networked Caddy fronts it as wss.
        # The local Electrum wallet reaches it in-cluster at ws://nostr-relay:7777.
        "ports": [f"127.0.0.1:{ctx.ports['nostr_relay_backend']}:{rp}"],
        "networks": [ctx.network_name],
    }


def _relay_sweeper_service(ctx: BuildContext) -> dict:
    """Minimal sidecar that expires relay events older than the retention window.

    nostr-rs-relay has no native age purge, so this mounts the relay's SQLite store
    and sweeps it on a loop (see :func:`argus.nostr_relay.render_retention_sweep`).
    """
    return {
        "image": "${SQLITE_IMAGE}",
        "container_name": f"{ctx.project}-nostr-relay-sweeper",
        "restart": "unless-stopped",
        "user": "0:0",
        "depends_on": {"nostr-relay": {"condition": "service_started"}},
        "entrypoint": ["/bin/sh", "/scripts/retention-sweep.sh"],
        "volumes": [
            "nostr_relay_data:/db",
            "./nostr-relay/retention-sweep.sh:/scripts/retention-sweep.sh:ro",
        ],
        "networks": [ctx.network_name],
    }


def build_electrum(ctx: BuildContext) -> Fragment:
    net, spec = ctx.net, ctx.spec

    conf_dir = ctx.out_dir / "electrum"
    conf_dir.mkdir(parents=True, exist_ok=True)

    # Splice the operator's extra setconfig pairs into the entrypoint.
    extra_lines = "\n".join(
        f'$E setconfig {k} "{v}" >/dev/null 2>&1 || true'
        for k, v in net.electrum.extra_config.items()
    )
    entrypoint = _ENTRYPOINT_SH.replace("__EXTRA_CONFIG__", extra_lines)
    (conf_dir / "electrum-entrypoint.sh").write_text(entrypoint)

    services: dict[str, dict] = {"electrum": _electrum_service(ctx)}
    volumes: dict[str, dict] = {"electrum_data": {}, "electrum_state": {}}
    env = {"ELECTRUM_IMAGE": ELECTRUM_IMAGE}

    if net.electrum_funding_mode(spec) == "auto":
        (conf_dir / "electrum-fund.sh").write_text(_FUND_SH)
        services["electrum-fund"] = _fund_service(ctx)
        env["BITCOIND_IMAGE"] = ctx.cfg.global_.bitcoind_image

    if net.electrum_relay_enabled(spec):
        relay_dir = ctx.out_dir / "nostr-relay"
        relay_dir.mkdir(parents=True, exist_ok=True)
        (relay_dir / "config.toml").write_text(render_relay_conf(ctx))
        (relay_dir / "retention-sweep.sh").write_text(
            render_retention_sweep(net.electrum.relay.retention_hours)
        )
        services["nostr-relay"] = _relay_service(ctx)
        services["nostr-relay-sweeper"] = _relay_sweeper_service(ctx)
        volumes["nostr_relay_data"] = {}
        env["NOSTR_RELAY_IMAGE"] = ctx.cfg.global_.nostr_relay_image
        env["SQLITE_IMAGE"] = ctx.cfg.global_.sqlite_image

    return Fragment(services=services, volumes=volumes, env=env)
