"""Builder for a Fedimint federation + per-ring-node Lightning gateways.

Deployed *alongside* the network's Cashu mint (not instead of it). The pieces:

* **Guardians** (``fedimintd`` x N, N = ``fedimint.guardians``) — custody on-chain
  BTC in a threshold multisig and issue Chaumian ecash backed 1:1. They track the
  chain through the network's own bitcoind over RPC (shared by all guardians;
  bitcoind never holds keys). The federation's client API is a plain WebSocket
  (no iroh, for deterministic single-host routing) fronted publicly by the shared
  Caddy so a Fedi-style wallet can join via the invite code.

* **Gateways** (``gatewayd`` x N) — bridge federation ecash <-> Lightning. One
  gateway is paired with each ring LND node (gateway *i* -> argus*i*), so the
  federation's Lightning traffic rides the triangle's self-rebalancing channels —
  no new liquidity machinery, which is what makes this work on networks where
  Argus can't mine. The gateway API is fronted publicly too so wallets can take
  Lightning deposits/withdrawals through it.

* **Setup sidecar** (``fedimint-setup``) — drives the federation's non-interactive
  DKG once (set-local-params -> add-peer -> start-dkg, exactly what Fedimint's own
  ``devimint`` does), then copies the resulting invite code to a shared volume.

* **Gateways sidecar** (``fedimint-gateways``) — registers each gateway with the
  federation (``connect-fed``) and surfaces each gateway's ecash-peg-in address.

* **Fund sidecar** (``fedimint-fund``, ``auto`` funding only) — pegs each gateway's
  ``float_btc`` ecash float in from the same wallet that funds the ring (mine +
  confirm). On ``external`` funding the peg-in address is surfaced instead and the
  operator/faucet sends the coins (mirrors the ring's auto/external split).

DKG/funding flows are sequenced through marker files in the shared
``fedimint_state`` volume so re-running ``docker compose up`` is idempotent.
"""

from __future__ import annotations

from ..constants import (
    CHAIN_INTERNAL_PORTS,
    FEDIMINTD_INTERNAL_PORTS,
    GATEWAYD_INTERNAL_PORT,
    LND_INTERNAL_PORTS,
    LND_NETWORK_KEY,
    FEDIMINT_NETWORK_KEY,
)
from ..context import BuildContext, Fragment

# Service / data-volume names per index, mirroring the LND ring's lnd/lnd2/lnd3.
# Guardian peer ids are 0-based; the first guardian (index 0) is the DKG leader.
_GUARDIAN_SERVICES = ("fedimintd", "fedimintd2", "fedimintd3")
_GATEWAY_SERVICES = ("gatewayd", "gatewayd2", "gatewayd3")
_LND_SERVICES = ("lnd", "lnd2", "lnd3")
_LND_VOLUMES = ("lnd_data", "lnd2_data", "lnd3_data")


# --- Sidecar scripts --------------------------------------------------------

# Non-interactive DKG: wait for every guardian to reach AwaitingLocalParams, set
# each peer's local params (the leader also fixes the federation name + size),
# exchange connection info pairwise, start DKG on all, then publish the invite
# code the leader writes to its data dir. Mirrors devimint's run_cli_dkg_v2.
_SETUP_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — run the federation's non-interactive DKG.
set -eu

PW="${GUARDIAN_PASSWORD}"
NAME="${FEDERATION_NAME}"
N="${GUARDIANS}"
STATE=/state
FCLI="fedimint-cli --password ${PW}"

if [ -f "${STATE}/invite-code" ]; then
  echo "[fedimint-setup] federation already established; nothing to do"; exit 0
fi

# Guardian API endpoints in peer order (peer 0 first = DKG leader).
set -- ${ENDPOINTS}

echo "[fedimint-setup] waiting for ${N} guardian(s) to reach AwaitingLocalParams..."
for ep in "$@"; do
  until $FCLI admin setup "$ep" status 2>/dev/null | grep -q AwaitingLocalParams; do
    echo "[fedimint-setup]   $ep not ready yet"; sleep 3
  done
done

echo "[fedimint-setup] setting local params + collecting connection info..."
INFOS=""
i=0
for ep in "$@"; do
  if [ "$i" = 0 ]; then
    out=$($FCLI admin setup "$ep" set-local-params "Guardian $i" \
            --federation-name "${NAME}" --federation-size "${N}")
  else
    out=$($FCLI admin setup "$ep" set-local-params "Guardian $i")
  fi
  # set-local-params prints the connection info as a JSON string; strip quotes.
  info=$(printf '%s' "$out" | tr -d '"' | tr -d '\\n')
  INFOS="${INFOS} ${info}"
  i=$((i + 1))
done

# Exchange peer connection info: add every peer's info to every OTHER guardian.
# (For a single-guardian federation this loop adds nothing — solo DKG.)
echo "[fedimint-setup] exchanging peer connection info..."
ei=0
for ep in "$@"; do
  ii=0
  for info in ${INFOS}; do
    if [ "$ii" != "$ei" ]; then
      $FCLI admin setup "$ep" add-peer "$info"
    fi
    ii=$((ii + 1))
  done
  ei=$((ei + 1))
done

echo "[fedimint-setup] starting DKG on all guardian(s)..."
for ep in "$@"; do
  $FCLI admin setup "$ep" start-dkg
done

echo "[fedimint-setup] waiting for the leader to publish the invite code..."
until [ -s /leader/invite-code ]; do sleep 3; done
cp /leader/invite-code "${STATE}/invite-code"
echo "[fedimint-setup] federation is up. invite code:"
cat "${STATE}/invite-code"; echo
"""

# Register each gateway with the federation and surface its ecash peg-in address
# (so the fund sidecar — or, on external-funded nets, the operator/faucet — can
# top up the gateway's ecash float). Idempotent via per-gateway marker files.
_GATEWAYS_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — register gateways + expose ecash peg-in addresses.
set -eu

PW="${GATEWAY_PASSWORD}"
PORT="${GW_PORT}"
STATE=/state

echo "[fedimint-gw] waiting for the federation invite code..."
until [ -s "${STATE}/invite-code" ]; do sleep 3; done
INVITE=$(cat "${STATE}/invite-code")

i=0
for gw in ${GATEWAYS}; do
  G="gateway-cli --rpcpassword ${PW} -a http://${gw}:${PORT}/"
  echo "[fedimint-gw] waiting for ${gw} to answer RPC..."
  until $G info >/dev/null 2>&1; do sleep 3; done

  if [ ! -f "${STATE}/gw${i}_joined" ]; then
    echo "[fedimint-gw] ${gw} connect-fed"
    $G connect-fed "${INVITE}" >/dev/null 2>&1 \
      || echo "[fedimint-gw] ${gw} already joined (or join pending)"
    touch "${STATE}/gw${i}_joined"
  fi

  # Federation id (32-byte hex) — read off the federation_id line so the 66-hex
  # gateway pubkey on another line can't be mistaken for it.
  FED=$($G info | tr ',{}' '\\n' | grep federation_id \
          | grep -oE '[0-9a-f]{64}' | head -1 || true)
  if [ -n "${FED}" ]; then
    ADDR=$($G ecash pegin --federation-id="${FED}" 2>/dev/null \
             | grep -oE '(bcrt1|tb1|bc1)[a-z0-9]+' | head -1 || true)
    if [ -n "${ADDR}" ]; then
      printf '%s\\n' "${ADDR}" > "${STATE}/gw${i}_pegin.txt"
      echo "[fedimint-gw] ${gw} ecash peg-in address: ${ADDR}"
    fi
  fi
  i=$((i + 1))
done
echo "[fedimint-gw] gateways registered"
"""

# Peg each gateway's ecash float in from the ring's funding wallet (auto funding
# only). Mirrors the ring's lnd-setup: mine on regtest, wait for the signer to
# accumulate coins on the custom signets, then send + confirm.
_FUND_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — peg gateway ecash float in (auto funding only).
set -eu

CLI="bitcoin-cli ${CHAIN_FLAG} -rpcconnect=${RPC_CONNECT} -rpcport=${RPC_PORT} \
-rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD}"
WCLI="${CLI} -rpcwallet=${FUNDING_WALLET}"
STATE=/state

if [ -f "${STATE}/funded_gw" ]; then
  echo "[fedimint-fund] gateway float already funded; nothing to do"; exit 0
fi

echo "[fedimint-fund] waiting for bitcoind RPC + funding wallet '${FUNDING_WALLET}'..."
until $CLI getblockchaininfo >/dev/null 2>&1; do sleep 2; done
until $WCLI getwalletinfo >/dev/null 2>&1; do
  $CLI loadwallet "${FUNDING_WALLET}" >/dev/null 2>&1 || true; sleep 3
done

echo "[fedimint-fund] waiting for gateway peg-in addresses..."
until ls "${STATE}"/gw*_pegin.txt >/dev/null 2>&1; do sleep 3; done

enough() { awk "BEGIN{exit !($($WCLI getbalance) >= ${FLOAT_BTC})}"; }
MADDR=$($WCLI getnewaddress)

for f in "${STATE}"/gw*_pegin.txt; do
  ADDR=$(cat "$f")
  while ! enough; do
    if [ "${CAN_MINE}" = "1" ]; then
      echo "[fedimint-fund] mining to mature funds (balance $($WCLI getbalance))"
      $CLI generatetoaddress 10 "$MADDR" >/dev/null
    else
      echo "[fedimint-fund] waiting for the signer's matured coins (balance $($WCLI getbalance))"
      sleep 10
    fi
  done
  echo "[fedimint-fund] sending ${FLOAT_BTC} BTC to ${ADDR}"
  $WCLI -named sendtoaddress address="${ADDR}" amount=${FLOAT_BTC} fee_rate=2 >/dev/null
done

if [ "${CAN_MINE}" = "1" ]; then $CLI generatetoaddress 6 "$MADDR" >/dev/null; fi
touch "${STATE}/funded_gw"
echo "[fedimint-fund] gateway ecash float pegged in (claims confirm via the steady miner)"
"""

# Gateway entrypoint: compute the bcrypt password hash gatewayd expects from the
# plaintext gateway-cli password at runtime, then exec the daemon. Matches the
# pattern in Fedimint's own gatewayd-startos entrypoint (create-password-hash
# wraps its output in quotes, so strip them).
_GW_ENTRYPOINT = (
    'H=$(gateway-cli create-password-hash "$GW_PASSWORD" | tr -d \'"\' | tr -d "\\n"); '
    'export FM_GATEWAY_BCRYPT_PASSWORD_HASH="$H"; '
    "exec gatewayd lnd"
)


def _guardian_service(ctx: BuildContext, i: int) -> dict:
    """One ``fedimintd`` guardian (peer ``i``)."""
    svc = _GUARDIAN_SERVICES[i]
    vol = f"{svc}_data"
    p = FEDIMINTD_INTERNAL_PORTS
    rpc_internal = CHAIN_INTERNAL_PORTS[ctx.spec.chain]["rpc"]
    fm_net = FEDIMINT_NETWORK_KEY[ctx.spec.chain]
    scheme = "wss" if ctx.cfg.global_.ssl_enabled else "ws"
    api_public = ctx.ports[f"fedimintd_{i}_api_public"]

    environment = {
        "FM_BITCOIN_NETWORK": fm_net,
        # All guardians share the network's bitcoind (a blockchain view +
        # broadcaster, never a key holder), so this is safe on a single host.
        "FM_BITCOIND_URL": f"http://bitcoind:{rpc_internal}",
        "FM_BITCOIND_USERNAME": "${RPC_USER}",
        "FM_BITCOIND_PASSWORD": "${RPC_PASSWORD}",
        "FM_BIND_P2P": f"0.0.0.0:{p['p2p']}",
        # P2P is container-internal: peers reach each other by service name.
        "FM_P2P_URL": f"fedimint://{svc}:{p['p2p']}",
        "FM_BIND_API": f"0.0.0.0:{p['api']}",
        # The advertised client API URL embedded in the invite code — the public
        # Caddy endpoint (TLS-terminated; Caddy proxies wss -> the ws backend).
        "FM_API_URL": f"{scheme}://{ctx.cfg.global_.hostname}:{api_public}",
        "FM_BIND_UI": f"0.0.0.0:{p['ui']}",
        "FM_DATA_DIR": "/data",
    }
    environment.update(ctx.net.fedimint.extra_env)

    return {
        "image": "${FEDIMINTD_IMAGE}",
        "container_name": f"{ctx.project}-{svc}",
        "restart": "unless-stopped",
        "depends_on": {"bitcoind": {"condition": "service_healthy"}},
        "environment": environment,
        "volumes": [f"{vol}:/data"],
        # API + UI on loopback (Caddy fronts the API publicly); P2P stays internal.
        "ports": [
            f"127.0.0.1:{ctx.ports[f'fedimintd_{i}_api']}:{p['api']}",
            f"127.0.0.1:{ctx.ports[f'fedimintd_{i}_ui']}:{p['ui']}",
        ],
        "networks": [ctx.network_name],
    }


def _gateway_service(ctx: BuildContext, i: int) -> dict:
    """One ``gatewayd`` (LND backend), paired with ring node ``i``."""
    svc = _GATEWAY_SERVICES[i]
    vol = f"{svc}_data"
    lnd_svc = _LND_SERVICES[i]
    lnd_vol = _LND_VOLUMES[i]
    lnd_net = LND_NETWORK_KEY[ctx.spec.chain]
    grpc = LND_INTERNAL_PORTS["grpc"]
    fm_net = FEDIMINT_NETWORK_KEY[ctx.spec.chain]
    scheme = "https" if ctx.cfg.global_.ssl_enabled else "http"
    api_public = ctx.ports[f"gatewayd_{i}_api_public"]

    environment = {
        "FM_GATEWAY_DATA_DIR": "/data",
        "FM_GATEWAY_LISTEN_ADDR": f"0.0.0.0:{GATEWAYD_INTERNAL_PORT}",
        # Advertised (public) API/UI URL clients use to take Lightning deposits.
        "FM_GATEWAY_API_ADDR": f"{scheme}://{ctx.cfg.global_.hostname}:{api_public}",
        "FM_GATEWAY_NETWORK": fm_net,
        # LND backend uses the LNv1 gateway protocol.
        "FM_GATEWAY_LIGHTNING_MODULE_MODE": "LNv1",
        # The LND node's cert carries a SAN for its own service name (tlsextradomain
        # in lnd.conf), so gRPC TLS verification against this host succeeds.
        "FM_LND_RPC_ADDR": f"https://{lnd_svc}:{grpc}",
        "FM_LND_TLS_CERT": "/lnd/tls.cert",
        "FM_LND_MACAROON": f"/lnd/data/chain/bitcoin/{lnd_net}/admin.macaroon",
        # Plaintext gateway-cli password; the entrypoint derives the bcrypt hash.
        "GW_PASSWORD": "${FEDIMINT_GATEWAY_PASSWORD}",
    }
    environment.update(ctx.net.fedimint.gateway.extra_env)

    return {
        "image": "${GATEWAYD_IMAGE}",
        "container_name": f"{ctx.project}-{svc}",
        "restart": "unless-stopped",
        "depends_on": {lnd_svc: {"condition": "service_healthy"}},
        "entrypoint": ["/bin/sh", "-c", _GW_ENTRYPOINT],
        "environment": environment,
        "volumes": [f"{vol}:/data", f"{lnd_vol}:/lnd:ro"],
        # API/UI on loopback; Caddy fronts it publicly (wss).
        "ports": [
            f"127.0.0.1:{ctx.ports[f'gatewayd_{i}_api']}:{GATEWAYD_INTERNAL_PORT}",
        ],
        "networks": [ctx.network_name],
    }


def build_fedimint(ctx: BuildContext) -> Fragment:
    net = ctx.net
    n = net.fedimint_guardian_count(ctx.spec)
    p = FEDIMINTD_INTERNAL_PORTS
    chain = ctx.spec.chain
    rpc_internal = CHAIN_INTERNAL_PORTS[chain]["rpc"]
    funding = net.lnd_funding_mode(ctx.spec)
    can_mine = chain == "regtest"
    funding_wallet = "miner" if chain == "regtest" else "signer"

    guardian_services = _GUARDIAN_SERVICES[:n]
    gateway_services = _GATEWAY_SERVICES[:n]

    services: dict[str, dict] = {}
    volumes: dict[str, dict] = {"fedimint_state": {}}

    for i in range(n):
        services[_GUARDIAN_SERVICES[i]] = _guardian_service(ctx, i)
        volumes[f"{_GUARDIAN_SERVICES[i]}_data"] = {}
        services[_GATEWAY_SERVICES[i]] = _gateway_service(ctx, i)
        volumes[f"{_GATEWAY_SERVICES[i]}_data"] = {}

    # Write the sidecar scripts into the per-network build context.
    conf_dir = ctx.out_dir / "fedimint"
    conf_dir.mkdir(parents=True, exist_ok=True)
    (conf_dir / "setup.sh").write_text(_SETUP_SH)
    (conf_dir / "gateways.sh").write_text(_GATEWAYS_SH)

    # DKG sidecar (fedimintd image — it bundles fedimint-cli). Endpoints are the
    # guardians' internal ws API URLs in peer order; it reads the leader's
    # data volume read-only to publish the invite code.
    endpoints = " ".join(f"ws://{svc}:{p['api']}" for svc in guardian_services)
    services["fedimint-setup"] = {
        "image": "${FEDIMINTD_IMAGE}",
        "container_name": f"{ctx.project}-fedimint-setup",
        # Root so it can write the shared-state markers (volume is root-owned and
        # shared with the gateway/fund sidecars, whose container UIDs differ).
        "user": "0:0",
        "restart": "on-failure",
        "depends_on": {
            svc: {"condition": "service_started"} for svc in guardian_services
        },
        "entrypoint": ["/bin/sh", "/scripts/setup.sh"],
        "environment": {
            "GUARDIAN_PASSWORD": "${FEDIMINT_GUARDIAN_PASSWORD}",
            "FEDERATION_NAME": net.fedimint_federation_name(ctx.net_key),
            "GUARDIANS": str(n),
            "ENDPOINTS": endpoints,
        },
        "volumes": [
            "./fedimint/setup.sh:/scripts/setup.sh:ro",
            # Leader (peer 0) data volume, read-only, to read /data/invite-code.
            f"{_GUARDIAN_SERVICES[0]}_data:/leader:ro",
            "fedimint_state:/state",
        ],
        "networks": [ctx.network_name],
    }

    # Gateways sidecar (gatewayd image — it bundles gateway-cli): connect-fed +
    # surface each gateway's ecash peg-in address.
    gw_depends = {svc: {"condition": "service_started"} for svc in gateway_services}
    gw_depends["fedimint-setup"] = {"condition": "service_started"}
    services["fedimint-gateways"] = {
        "image": "${GATEWAYD_IMAGE}",
        "container_name": f"{ctx.project}-fedimint-gateways",
        "user": "0:0",
        "restart": "on-failure",
        "depends_on": gw_depends,
        "entrypoint": ["/bin/sh", "/scripts/gateways.sh"],
        "environment": {
            "GATEWAY_PASSWORD": "${FEDIMINT_GATEWAY_PASSWORD}",
            "GATEWAYS": " ".join(gateway_services),
            "GW_PORT": str(GATEWAYD_INTERNAL_PORT),
        },
        "volumes": [
            "./fedimint/gateways.sh:/scripts/gateways.sh:ro",
            "fedimint_state:/state",
        ],
        "networks": [ctx.network_name],
    }

    # Fund sidecar (auto funding only): peg the ecash float in from the ring's
    # funding wallet. On external funding the peg-in addresses are surfaced (above)
    # and the operator/faucet sends the coins instead.
    if funding == "auto":
        (conf_dir / "fund.sh").write_text(_FUND_SH)
        services["fedimint-fund"] = {
            "image": "${BITCOIND_IMAGE}",
            "container_name": f"{ctx.project}-fedimint-fund",
            "user": "0:0",
            "restart": "on-failure",
            "depends_on": {
                "bitcoind": {"condition": "service_healthy"},
                "fedimint-gateways": {"condition": "service_started"},
            },
            "entrypoint": ["/bin/sh", "/scripts/fund.sh"],
            "environment": {
                "CHAIN_FLAG": "-regtest" if chain == "regtest" else "-signet",
                "CAN_MINE": "1" if can_mine else "0",
                "FUNDING_WALLET": funding_wallet,
                "RPC_CONNECT": "bitcoind",
                "RPC_PORT": str(rpc_internal),
                "RPC_USER": "${RPC_USER}",
                "RPC_PASSWORD": "${RPC_PASSWORD}",
                "FLOAT_BTC": str(net.fedimint.gateway.float_btc),
            },
            "volumes": [
                "./fedimint/fund.sh:/scripts/fund.sh:ro",
                "fedimint_state:/state",
            ],
            "networks": [ctx.network_name],
        }

    return Fragment(
        services=services,
        volumes=volumes,
        env={
            "FEDIMINTD_IMAGE": ctx.cfg.global_.fedimintd_image,
            "GATEWAYD_IMAGE": ctx.cfg.global_.gatewayd_image,
            "RPC_USER": ctx.secrets["RPC_USER"],
            "RPC_PASSWORD": ctx.secrets["RPC_PASSWORD"],
            "FEDIMINT_GUARDIAN_PASSWORD": ctx.secrets["FEDIMINT_GUARDIAN_PASSWORD"],
            "FEDIMINT_GATEWAY_PASSWORD": ctx.secrets["FEDIMINT_GATEWAY_PASSWORD"],
        },
    )
