"""Builder for a Fedimint federation + per-ring-node Lightning gateways.

Deployed *alongside* the network's Cashu mint (not instead of it). The pieces:

* **Guardians** (``fedimintd`` x N, N = ``fedimint.guardians``) — custody on-chain
  BTC in a threshold multisig and issue Chaumian ecash backed 1:1. They track the
  chain through the network's own bitcoind over RPC (shared by all guardians;
  bitcoind never holds keys). The federation's client API is a plain WebSocket
  (no iroh, for deterministic single-host routing) fronted publicly by the shared
  Caddy so a Fedi-style wallet can join via the invite code.

* **Gateways** (``gatewayd`` x N) — bridge federation ecash <-> Lightning. One
  gateway is paired with each ring LND node (gateway *i* -> argus*i*), so the
  federation's Lightning traffic rides the triangle's self-rebalancing channels —
  no new liquidity machinery, which is what makes this work on networks where
  Argus can't mine. The gateway API is fronted publicly too so wallets can take
  Lightning deposits/withdrawals through it.

* **Setup sidecar** (``fedimint-setup``) — drives the federation's non-interactive
  DKG once (set-local-params -> add-peer -> start-dkg, exactly what Fedimint's own
  ``devimint`` does), then copies the resulting invite code to a shared volume.

* **Gateways sidecar** (``fedimint-gateways``) — creates each gateway's wallet (so
  it leaves the NotConfigured state and reaches Running), registers it with the
  federation (``connect-fed``), and pegs its ``float_btc`` ecash float in from the
  gateway's OWN on-chain wallet (``ecash pegin-from-onchain``). Because that wallet
  is the gateway's ring-funded LND node, the float is funded identically on every
  network — mined or not — with no separate funding wallet and no auto/external
  split.

DKG/funding flows are sequenced through marker files in the shared
``fedimint_state`` volume so re-running ``docker compose up`` is idempotent.
"""

from __future__ import annotations

from ..constants import (
    CHAIN_INTERNAL_PORTS,
    FEDIMINTD_INTERNAL_PORTS,
    GATEWAYD_INTERNAL_PORT,
    LND_INTERNAL_PORTS,
    LND_NETWORK_KEY,
    FEDIMINT_NETWORK_KEY,
)
from ..context import BuildContext, Fragment

# Service / data-volume names per index, mirroring the LND ring's lnd/lnd2/lnd3.
# Guardian peer ids are 0-based; the first guardian (index 0) is the DKG leader.
_GUARDIAN_SERVICES = ("fedimintd", "fedimintd2", "fedimintd3")
_GATEWAY_SERVICES = ("gatewayd", "gatewayd2", "gatewayd3")
_LND_SERVICES = ("lnd", "lnd2", "lnd3")
_LND_VOLUMES = ("lnd_data", "lnd2_data", "lnd3_data")


# --- Sidecar scripts --------------------------------------------------------

# Non-interactive DKG: wait for every guardian to reach AwaitingLocalParams, set
# each peer's local params (the leader also fixes the federation name + size),
# exchange connection info pairwise, start DKG on all, then publish the invite
# code the leader writes to its data dir. Mirrors devimint's run_cli_dkg_v2.
_SETUP_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — run the federation's non-interactive DKG.
set -eu

PW="${GUARDIAN_PASSWORD}"
NAME="${FEDERATION_NAME}"
N="${GUARDIANS}"
STATE=/state
FCLI="fedimint-cli --password ${PW}"

if [ -f "${STATE}/invite-code" ]; then
  echo "[fedimint-setup] federation already established; nothing to do"; exit 0
fi

# Guardian API endpoints in peer order (peer 0 first = DKG leader).
set -- ${ENDPOINTS}

echo "[fedimint-setup] waiting for ${N} guardian(s) to reach AwaitingLocalParams..."
for ep in "$@"; do
  until $FCLI admin setup "$ep" status 2>/dev/null | grep -q AwaitingLocalParams; do
    echo "[fedimint-setup]   $ep not ready yet"; sleep 3
  done
done

echo "[fedimint-setup] setting local params + collecting connection info..."
INFOS=""
i=0
for ep in "$@"; do
  if [ "$i" = 0 ]; then
    out=$($FCLI admin setup "$ep" set-local-params "Guardian $i" \
            --federation-name "${NAME}" --federation-size "${N}")
  else
    out=$($FCLI admin setup "$ep" set-local-params "Guardian $i")
  fi
  # set-local-params prints the connection info as a JSON string; strip quotes.
  info=$(printf '%s' "$out" | tr -d '"' | tr -d '\\n')
  INFOS="${INFOS} ${info}"
  i=$((i + 1))
done

# Exchange peer connection info: add every peer's info to every OTHER guardian.
# (For a single-guardian federation this loop adds nothing — solo DKG.)
echo "[fedimint-setup] exchanging peer connection info..."
ei=0
for ep in "$@"; do
  ii=0
  for info in ${INFOS}; do
    if [ "$ii" != "$ei" ]; then
      $FCLI admin setup "$ep" add-peer "$info"
    fi
    ii=$((ii + 1))
  done
  ei=$((ei + 1))
done

echo "[fedimint-setup] starting DKG on all guardian(s)..."
for ep in "$@"; do
  $FCLI admin setup "$ep" start-dkg
done

echo "[fedimint-setup] waiting for the leader to publish the invite code..."
until [ -s /leader/invite-code ]; do sleep 3; done
cp /leader/invite-code "${STATE}/invite-code"
echo "[fedimint-setup] federation is up. invite code:"
cat "${STATE}/invite-code"; echo
"""

# Initialise each gateway (create its wallet/mnemonic so it reaches Running),
# register it with the federation, and surface its ecash peg-in address (so the
# fund sidecar — or, on external-funded nets, the operator/faucet — can top up the
# gateway's ecash float). Idempotent via per-gateway marker files.
_GATEWAYS_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — init + register gateways + expose peg-in addresses.
set -eu

PW="${GATEWAY_PASSWORD}"
PORT="${GW_PORT}"
STATE=/state

echo "[fedimint-gw] waiting for the federation invite code..."
until [ -s "${STATE}/invite-code" ]; do sleep 3; done
INVITE=$(cat "${STATE}/invite-code")

i=0
for gw in ${GATEWAYS}; do
  G="gateway-cli --rpcpassword ${PW} -a http://${gw}:${PORT}/"
  BASE="http://${gw}:${PORT}"

  echo "[fedimint-gw] waiting for ${gw} webserver..."
  until curl -s -o /dev/null -m 5 "${BASE}/"; do sleep 3; done

  # gatewayd boots NotConfigured; create its wallet (generates the mnemonic) so it
  # reaches Running and can join a federation. The create-wallet UI route is allowed
  # without auth while unconfigured (is_allowed_setup_route); the marker keeps it
  # one-shot.
  if [ ! -f "${STATE}/gw${i}_wallet" ]; then
    echo "[fedimint-gw] ${gw} create wallet"
    curl -s -m 20 -o /dev/null -X POST "${BASE}/ui/wallet/create" || true
    touch "${STATE}/gw${i}_wallet"
  fi

  echo "[fedimint-gw] waiting for ${gw} to reach Running..."
  until $G info 2>/dev/null | grep -q '"gateway_state": *"Running"'; do sleep 3; done

  if [ ! -f "${STATE}/gw${i}_joined" ]; then
    echo "[fedimint-gw] ${gw} connect-fed"
    $G connect-fed "${INVITE}" >/dev/null 2>&1 \
      || echo "[fedimint-gw] ${gw} already joined (or join pending)"
    touch "${STATE}/gw${i}_joined"
  fi

  # Federation id (32-byte hex) — read off the federation_id line so the 66-hex
  # gateway pubkey on another line can't be mistaken for it.
  FED=$($G info | tr ',{}' '\\n' | grep federation_id \
          | grep -oE '[0-9a-f]{64}' | head -1 || true)

  # Peg the ecash float in from the gateway's OWN on-chain wallet (its ring-funded
  # LND node) — works identically on every network, mined or not, with no separate
  # funding wallet. Three marker-guarded phases so a restart never re-sends: get a
  # federation peg-in address, send the float to it on-chain (--amount is msats),
  # then recheck the deposit to claim ecash. Deposits are NOT auto-claimed and the
  # claim needs the federation's finality delay (block confirmations), so recheck
  # retries; if still unconfirmed we exit non-zero to retry on the next restart.
  if [ -n "${FED}" ] && [ "${FLOAT_MSAT}" -gt 0 ] && [ ! -f "${STATE}/gw${i}_funded" ]; then
    if [ ! -f "${STATE}/gw${i}_sent" ]; then
      ADDR=$($G ecash pegin --federation-id="${FED}" 2>/dev/null \
               | grep -oE '(bcrt1|tb1|bc1)[a-z0-9]+' | head -1 || true)
      if [ -n "${ADDR}" ] \
         && $G onchain send --address "${ADDR}" --amount "${FLOAT_MSAT}" \
              --fee-rate-sats-per-vbyte 2 >/dev/null 2>&1; then
        printf '%s\\n' "${ADDR}" > "${STATE}/gw${i}_addr"
        touch "${STATE}/gw${i}_sent"
        echo "[fedimint-gw] ${gw} sent ${FLOAT_MSAT} msat float to ${ADDR}"
      else
        echo "[fedimint-gw] ${gw} float send not ready (on-chain funds?); will retry"
        PENDING=1
      fi
    fi
    if [ -f "${STATE}/gw${i}_addr" ]; then
      ADDR=$(cat "${STATE}/gw${i}_addr")
      echo "[fedimint-gw] ${gw} claiming float (recheck until confirmed)..."
      j=0
      while [ "$j" -lt 20 ]; do
        $G ecash pegin-recheck --address "${ADDR}" --federation-id "${FED}" \
          >/dev/null 2>&1 || true
        BAL=$($G get-balances 2>/dev/null \
               | grep -oE '"ecash_balance_msats": [0-9]+' | grep -oE '[0-9]+' | head -1)
        if [ -n "${BAL}" ] && [ "${BAL}" -gt 0 ]; then break; fi
        j=$((j + 1)); sleep 15
      done
      if [ -n "${BAL}" ] && [ "${BAL}" -gt 0 ]; then
        touch "${STATE}/gw${i}_funded"
        echo "[fedimint-gw] ${gw} float claimed (${BAL} msat ecash)"
      else
        echo "[fedimint-gw] ${gw} float not confirmed yet; will retry"; PENDING=1
      fi
    fi
  fi
  i=$((i + 1))
done

if [ "${PENDING:-0}" = 1 ]; then
  echo "[fedimint-gw] some gateway floats not funded yet; exiting to retry"; exit 1
fi
echo "[fedimint-gw] gateways registered + funded"
"""

# Gateway entrypoint script: compute the bcrypt password hash gatewayd expects
# from the plaintext gateway-cli password at runtime, then exec the daemon.
# Matches the pattern in Fedimint's own gatewayd-startos entrypoint
# (create-password-hash wraps its output in quotes, so strip them). Mounted as a
# file (not an inline entrypoint) so Compose never interpolates its ``$`` vars.
_GW_ENTRY_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — derive gatewayd's bcrypt password hash, then run.
set -eu
H=$(gateway-cli create-password-hash "$GW_PASSWORD" | tr -d '"' | tr -d '\\n')
export FM_GATEWAY_BCRYPT_PASSWORD_HASH="$H"
exec gatewayd lnd
"""


def _guardian_service(ctx: BuildContext, i: int) -> dict:
    """One ``fedimintd`` guardian (peer ``i``)."""
    svc = _GUARDIAN_SERVICES[i]
    vol = f"{svc}_data"
    p = FEDIMINTD_INTERNAL_PORTS
    rpc_internal = CHAIN_INTERNAL_PORTS[ctx.spec.chain]["rpc"]
    fm_net = FEDIMINT_NETWORK_KEY[ctx.spec.chain]
    scheme = "wss" if ctx.cfg.global_.ssl_enabled else "ws"
    api_public = ctx.ports[f"fedimintd_{i}_api_public"]

    environment = {
        "FM_BITCOIN_NETWORK": fm_net,
        # All guardians share the network's bitcoind (a blockchain view +
        # broadcaster, never a key holder), so this is safe on a single host.
        "FM_BITCOIND_URL": f"http://bitcoind:{rpc_internal}",
        "FM_BITCOIND_USERNAME": "${RPC_USER}",
        "FM_BITCOIND_PASSWORD": "${RPC_PASSWORD}",
        "FM_BIND_P2P": f"0.0.0.0:{p['p2p']}",
        # P2P is container-internal: peers reach each other by service name.
        "FM_P2P_URL": f"fedimint://{svc}:{p['p2p']}",
        "FM_BIND_API": f"0.0.0.0:{p['api']}",
        # The advertised client API URL embedded in the invite code — the public
        # Caddy endpoint (TLS-terminated; Caddy proxies wss -> the ws backend).
        "FM_API_URL": f"{scheme}://{ctx.cfg.global_.hostname}:{api_public}",
        "FM_BIND_UI": f"0.0.0.0:{p['ui']}",
        "FM_DATA_DIR": "/data",
    }
    environment.update(ctx.net.fedimint.extra_env)

    return {
        "image": "${FEDIMINTD_IMAGE}",
        "container_name": f"{ctx.project}-{svc}",
        "restart": "unless-stopped",
        "depends_on": {"bitcoind": {"condition": "service_healthy"}},
        "environment": environment,
        "volumes": [f"{vol}:/data"],
        # API + UI on loopback (Caddy fronts the API publicly); P2P stays internal.
        "ports": [
            f"127.0.0.1:{ctx.ports[f'fedimintd_{i}_api']}:{p['api']}",
            f"127.0.0.1:{ctx.ports[f'fedimintd_{i}_ui']}:{p['ui']}",
        ],
        "networks": [ctx.network_name],
    }


def _gateway_service(ctx: BuildContext, i: int) -> dict:
    """One ``gatewayd`` (LND backend), paired with ring node ``i``."""
    svc = _GATEWAY_SERVICES[i]
    vol = f"{svc}_data"
    lnd_svc = _LND_SERVICES[i]
    lnd_vol = _LND_VOLUMES[i]
    lnd_net = LND_NETWORK_KEY[ctx.spec.chain]
    grpc = LND_INTERNAL_PORTS["grpc"]
    rpc_internal = CHAIN_INTERNAL_PORTS[ctx.spec.chain]["rpc"]
    fm_net = FEDIMINT_NETWORK_KEY[ctx.spec.chain]
    scheme = "https" if ctx.cfg.global_.ssl_enabled else "http"
    api_public = ctx.ports[f"gatewayd_{i}_api_public"]

    environment = {
        "FM_GATEWAY_DATA_DIR": "/data",
        "FM_GATEWAY_LISTEN_ADDR": f"0.0.0.0:{GATEWAYD_INTERNAL_PORT}",
        # Advertised (public) API/UI URL clients use to take Lightning deposits.
        "FM_GATEWAY_API_ADDR": f"{scheme}://{ctx.cfg.global_.hostname}:{api_public}",
        "FM_GATEWAY_NETWORK": fm_net,
        # The gateway needs a Bitcoin backend (for on-chain ops/fees) even with the
        # LND lightning backend — reuse the network's bitcoind, like the guardians.
        "FM_BITCOIND_URL": f"http://bitcoind:{rpc_internal}",
        "FM_BITCOIND_USERNAME": "${RPC_USER}",
        "FM_BITCOIND_PASSWORD": "${RPC_PASSWORD}",
        # LND backend uses the LNv1 gateway protocol.
        "FM_GATEWAY_LIGHTNING_MODULE_MODE": "LNv1",
        # The LND node's cert carries a SAN for its own service name (tlsextradomain
        # in lnd.conf), so gRPC TLS verification against this host succeeds.
        "FM_LND_RPC_ADDR": f"https://{lnd_svc}:{grpc}",
        "FM_LND_TLS_CERT": "/lnd/tls.cert",
        "FM_LND_MACAROON": f"/lnd/data/chain/bitcoin/{lnd_net}/admin.macaroon",
        # Plaintext gateway-cli password; the entrypoint derives the bcrypt hash.
        "GW_PASSWORD": "${FEDIMINT_GATEWAY_PASSWORD}",
    }
    environment.update(ctx.net.fedimint.gateway.extra_env)

    return {
        "image": "${GATEWAYD_IMAGE}",
        "container_name": f"{ctx.project}-{svc}",
        "restart": "unless-stopped",
        "depends_on": {lnd_svc: {"condition": "service_healthy"}},
        "entrypoint": ["/bin/sh", "/scripts/gateway-entry.sh"],
        "environment": environment,
        "volumes": [
            f"{vol}:/data",
            f"{lnd_vol}:/lnd:ro",
            "./fedimint/gateway-entry.sh:/scripts/gateway-entry.sh:ro",
        ],
        # API/UI on loopback; Caddy fronts it publicly (wss).
        "ports": [
            f"127.0.0.1:{ctx.ports[f'gatewayd_{i}_api']}:{GATEWAYD_INTERNAL_PORT}",
        ],
        "networks": [ctx.network_name],
    }


def build_fedimint(ctx: BuildContext) -> Fragment:
    net = ctx.net
    n = net.fedimint_guardian_count(ctx.spec)
    p = FEDIMINTD_INTERNAL_PORTS
    # ecash float per gateway, in msats (gatewayd's --amount unit).
    float_msat = round(net.fedimint.gateway.float_btc * 1e8) * 1000

    guardian_services = _GUARDIAN_SERVICES[:n]
    gateway_services = _GATEWAY_SERVICES[:n]

    services: dict[str, dict] = {}
    volumes: dict[str, dict] = {"fedimint_state": {}}

    for i in range(n):
        services[_GUARDIAN_SERVICES[i]] = _guardian_service(ctx, i)
        volumes[f"{_GUARDIAN_SERVICES[i]}_data"] = {}
        services[_GATEWAY_SERVICES[i]] = _gateway_service(ctx, i)
        volumes[f"{_GATEWAY_SERVICES[i]}_data"] = {}

    # Write the sidecar scripts into the per-network build context.
    conf_dir = ctx.out_dir / "fedimint"
    conf_dir.mkdir(parents=True, exist_ok=True)
    (conf_dir / "setup.sh").write_text(_SETUP_SH)
    (conf_dir / "gateways.sh").write_text(_GATEWAYS_SH)
    (conf_dir / "gateway-entry.sh").write_text(_GW_ENTRY_SH)

    # DKG sidecar (fedimintd image — it bundles fedimint-cli). Endpoints are the
    # guardians' internal ws API URLs in peer order; it reads the leader's
    # data volume read-only to publish the invite code.
    endpoints = " ".join(f"ws://{svc}:{p['api']}" for svc in guardian_services)
    services["fedimint-setup"] = {
        "image": "${FEDIMINTD_IMAGE}",
        "container_name": f"{ctx.project}-fedimint-setup",
        # Root so it can write the shared-state markers (volume is root-owned and
        # shared with the gateway/fund sidecars, whose container UIDs differ).
        "user": "0:0",
        "restart": "on-failure",
        "depends_on": {
            svc: {"condition": "service_started"} for svc in guardian_services
        },
        "entrypoint": ["/bin/sh", "/scripts/setup.sh"],
        "environment": {
            "GUARDIAN_PASSWORD": "${FEDIMINT_GUARDIAN_PASSWORD}",
            "FEDERATION_NAME": net.fedimint_federation_name(ctx.net_key),
            "GUARDIANS": str(n),
            "ENDPOINTS": endpoints,
        },
        "volumes": [
            "./fedimint/setup.sh:/scripts/setup.sh:ro",
            # Leader (peer 0) data volume, read-only, to read /data/invite-code.
            f"{_GUARDIAN_SERVICES[0]}_data:/leader:ro",
            "fedimint_state:/state",
        ],
        "networks": [ctx.network_name],
    }

    # Gateways sidecar (gatewayd image — it bundles gateway-cli): create each
    # gateway's wallet, register it with the federation, and peg its ecash float in
    # from its own on-chain wallet (the ring-funded LND node) — so funding works
    # the same on every network with no separate funding wallet.
    gw_depends = {svc: {"condition": "service_started"} for svc in gateway_services}
    gw_depends["fedimint-setup"] = {"condition": "service_started"}
    services["fedimint-gateways"] = {
        "image": "${GATEWAYD_IMAGE}",
        "container_name": f"{ctx.project}-fedimint-gateways",
        "user": "0:0",
        "restart": "on-failure",
        "depends_on": gw_depends,
        "entrypoint": ["/bin/sh", "/scripts/gateways.sh"],
        "environment": {
            "GATEWAY_PASSWORD": "${FEDIMINT_GATEWAY_PASSWORD}",
            "GATEWAYS": " ".join(gateway_services),
            "GW_PORT": str(GATEWAYD_INTERNAL_PORT),
            "FLOAT_MSAT": str(float_msat),
        },
        "volumes": [
            "./fedimint/gateways.sh:/scripts/gateways.sh:ro",
            "fedimint_state:/state",
        ],
        "networks": [ctx.network_name],
    }

    return Fragment(
        services=services,
        volumes=volumes,
        env={
            "FEDIMINTD_IMAGE": ctx.cfg.global_.fedimintd_image,
            "GATEWAYD_IMAGE": ctx.cfg.global_.gatewayd_image,
            "RPC_USER": ctx.secrets["RPC_USER"],
            "RPC_PASSWORD": ctx.secrets["RPC_PASSWORD"],
            "FEDIMINT_GUARDIAN_PASSWORD": ctx.secrets["FEDIMINT_GUARDIAN_PASSWORD"],
            "FEDIMINT_GATEWAY_PASSWORD": ctx.secrets["FEDIMINT_GATEWAY_PASSWORD"],
        },
    )
