"""Builder for Fulcrum — the Electrum server for light wallets (and, later, the
mempool backend).

One service per enabled indexer entry, so a network can run several Fulcrum
instances. The Electrum TCP port is published publicly; the admin port is bound
to 127.0.0.1. TLS for the Electrum-SSL port is wired in the cert/Caddy phase;
for now Fulcrum serves plaintext TCP (Electrum wallets can connect with `:t`).
"""

from __future__ import annotations

from ..constants import CHAIN_INTERNAL_PORTS, FULCRUM_INTERNAL_PORTS
from ..context import BuildContext, Fragment


def _render_conf(ctx: BuildContext) -> str:
    rpc_internal = CHAIN_INTERNAL_PORTS[ctx.spec.chain]["rpc"]
    fp = FULCRUM_INTERNAL_PORTS
    # Fulcrum auto-detects the network from bitcoind's getblockchaininfo.
    lines = [
        "# Generated by Bitcoin Argus — do not edit by hand.",
        "datadir = /data",
        f"bitcoind = bitcoind:{rpc_internal}",
        f"rpcuser = {ctx.secrets['RPC_USER']}",
        f"rpcpassword = {ctx.secrets['RPC_PASSWORD']}",
        f"tcp = 0.0.0.0:{fp['tcp']}",
        f"admin = 0.0.0.0:{fp['admin']}",
        # SSL (fp['ssl']) is enabled once the shared cert layer exists.
        "peering = false",
        "announce = false",
    ]
    return "\n".join(lines) + "\n"


def build_fulcrum(ctx: BuildContext) -> Fragment:
    fp = FULCRUM_INTERNAL_PORTS
    services: dict[str, dict] = {}
    volumes: dict[str, dict] = {}

    for i, ix in enumerate(ctx.net.enabled_indexers()):
        name = ix.name  # validated: [a-z0-9-]
        vol = f"{name.replace('-', '_')}_data"
        conf_dir = ctx.out_dir / name
        conf_dir.mkdir(parents=True, exist_ok=True)
        (conf_dir / "fulcrum.conf").write_text(_render_conf(ctx))

        services[name] = {
            "image": "${FULCRUM_IMAGE}",
            "container_name": f"{ctx.project}-{name}",
            "restart": "unless-stopped",
            "depends_on": {"bitcoind": {"condition": "service_healthy"}},
            "command": ["Fulcrum", "/etc/fulcrum.conf"],
            "volumes": [
                f"{vol}:/data",
                f"./{name}/fulcrum.conf:/etc/fulcrum.conf:ro",
            ],
            "ports": [
                # Electrum TCP is PUBLIC; admin is closed (loopback only).
                f"{ctx.ports[f'fulcrum_{i}_electrum_tcp']}:{fp['tcp']}",
                f"127.0.0.1:{ctx.ports[f'fulcrum_{i}_admin']}:{fp['admin']}",
            ],
            "networks": [ctx.network_name],
            "healthcheck": {
                "test": [
                    "CMD-SHELL",
                    f"FulcrumAdmin -p {fp['admin']} getinfo >/dev/null 2>&1 || exit 1",
                ],
                "interval": "20s",
                "timeout": "10s",
                "retries": 15,
                "start_period": "30s",
            },
        }
        volumes[vol] = {}

    return Fragment(
        services=services,
        volumes=volumes,
        env={"FULCRUM_IMAGE": ctx.cfg.global_.fulcrum_image},
    )
