"""Builder for the standalone LND node (used by Cashu and general dev work).

Connects to bitcoind over the internal compose network (RPC + ZMQ). The wallet
auto-initialises (``noseedbackup``) so the stack comes up unattended — acceptable
for testnets, never for mainnet. P2P is published publicly; gRPC and REST are
bound to 127.0.0.1 (closed to the internet).

Bitcart runs its *own* LND (a later phase); this is a separate node.
"""

from __future__ import annotations

from ..constants import (
    CHAIN_INTERNAL_PORTS,
    LND_INTERNAL_PORTS,
    LND_NETWORK_KEY,
    ZMQ_BLOCK_INTERNAL,
    ZMQ_TX_INTERNAL,
)
from ..context import BuildContext, Fragment


def _sanitize_arg(arg: str) -> str:
    """Reject newlines in operator-supplied LND args (defense against injection)."""
    if "\n" in arg or "\r" in arg:
        raise ValueError(f"lnd extra_arg contains a newline: {arg!r}")
    return arg.strip()


def _render_conf(ctx: BuildContext) -> str:
    spec = ctx.spec
    net = ctx.net
    chain = spec.chain
    if chain not in LND_NETWORK_KEY:
        raise NotImplementedError(f"LND network mapping missing for chain {chain!r}")

    rpc_internal = CHAIN_INTERNAL_PORTS[chain]["rpc"]
    challenge = net.signet_challenge or spec.default_signet_challenge
    p = LND_INTERNAL_PORTS

    lines: list[str] = [
        "# Generated by Bitcoin Argus — do not edit by hand.",
        "[Application Options]",
        f"alias=argus-{ctx.net_key}"[:32],
        "debuglevel=info",
        # Unattended wallet init/unlock — fine for testnets only.
        "noseedbackup=true",
        f"listen=0.0.0.0:{p['p2p']}",
        f"rpclisten=0.0.0.0:{p['grpc']}",
        f"restlisten=0.0.0.0:{p['rest']}",
        # Make the TLS cert valid for in-container/loopback clients (e.g. Cashu).
        "tlsextradomain=lnd",
        "accept-keysend=true",
    ]
    if net.lnd.auto_compact:
        # Disk hygiene: compact channel.db on startup + drop canceled invoices.
        lines += [
            "gc-canceled-invoices-on-startup=true",
            "gc-canceled-invoices-on-the-fly=true",
            "db.bolt.auto-compact=true",
            "db.bolt.auto-compact-min-age=168h0m0s",
        ]
    lines += [
        "",
        "[Bitcoin]",
        "bitcoin.active=true",
        f"bitcoin.{LND_NETWORK_KEY[chain]}=true",
        "bitcoin.node=bitcoind",
    ]
    if spec.is_signet and challenge:
        lines.append(f"bitcoin.signetchallenge={challenge}")
        for node in (*spec.default_addnodes, *net.addnode):
            lines.append(f"bitcoin.signetseednode={node}")

    lines += [
        "",
        "[Bitcoind]",
        f"bitcoind.rpchost=bitcoind:{rpc_internal}",
        f"bitcoind.rpcuser={ctx.secrets['RPC_USER']}",
        f"bitcoind.rpcpass={ctx.secrets['RPC_PASSWORD']}",
        f"bitcoind.zmqpubrawblock=tcp://bitcoind:{ZMQ_BLOCK_INTERNAL}",
        f"bitcoind.zmqpubrawtx=tcp://bitcoind:{ZMQ_TX_INTERNAL}",
    ]
    return "\n".join(lines) + "\n"


def build_lnd(ctx: BuildContext) -> Fragment:
    conf_dir = ctx.out_dir / "lnd"
    conf_dir.mkdir(parents=True, exist_ok=True)
    (conf_dir / "lnd.conf").write_text(_render_conf(ctx))

    p = LND_INTERNAL_PORTS
    lnd_net = LND_NETWORK_KEY[ctx.spec.chain]  # lncli --network expects this name
    # The polarlightning image runs as uid 1000 and chowns /home/lnd at startup,
    # so the data volume lives there. The read-only conf is kept OUTSIDE that path
    # (the entrypoint's `chown -R /home/lnd` would fail on a ro-mounted file).
    lnddir = "/home/lnd/.lnd"
    command = ["--configfile=/etc/lnd/lnd.conf"] + [
        _sanitize_arg(a) for a in ctx.net.lnd.extra_args
    ]

    service = {
        "image": "${LND_IMAGE}",
        "container_name": f"{ctx.project}-lnd",
        "restart": "unless-stopped",
        "depends_on": {"bitcoind": {"condition": "service_healthy"}},
        "command": command,
        "volumes": [
            f"lnd_data:{lnddir}",
            "./lnd/lnd.conf:/etc/lnd/lnd.conf:ro",
        ],
        "ports": [
            # P2P is PUBLIC; gRPC + REST are closed (loopback only).
            f"{ctx.ports['lnd_p2p']}:{p['p2p']}",
            f"127.0.0.1:{ctx.ports['lnd_grpc']}:{p['grpc']}",
            f"127.0.0.1:{ctx.ports['lnd_rest']}:{p['rest']}",
        ],
        "networks": [ctx.network_name],
        "healthcheck": {
            "test": [
                "CMD-SHELL",
                f"lncli --lnddir={lnddir} --network={lnd_net} getinfo "
                ">/dev/null 2>&1 || exit 1",
            ],
            "interval": "20s",
            "timeout": "10s",
            "retries": 15,
            "start_period": "30s",
        },
    }
    if ctx.net.lnd.extra_env:
        service["environment"] = dict(ctx.net.lnd.extra_env)

    # One-shot sidecar: once LND is healthy, record its identity pubkey to a file
    # in the data volume. The dashboard reads it (read-only, via the Docker API)
    # to show the node's connection URI and link it on the explorer — without the
    # dashboard needing any per-network volume/network wiring of its own.
    out = f"{lnddir}/argus_nodeinfo.json"
    nodeinfo_cmd = (
        "i=0; while [ $i -lt 120 ]; do "
        f"lncli --lnddir={lnddir} --network={lnd_net} --rpcserver=lnd:{p['grpc']} "
        f"getinfo > {out} 2>/dev/null && [ -s {out} ] && exit 0; "
        "i=$((i+1)); sleep 5; done; exit 1"
    )
    nodeinfo = {
        "image": "${LND_IMAGE}",
        "container_name": f"{ctx.project}-lnd-nodeinfo",
        # Exits 0 once it writes the pubkey; on-failure so a slow LND sync (e.g.
        # after a bitcoind restart) just gets retried instead of giving up.
        "restart": "on-failure",
        "depends_on": {"lnd": {"condition": "service_healthy"}},
        "entrypoint": ["/bin/sh", "-c", nodeinfo_cmd],
        "volumes": [f"lnd_data:{lnddir}"],
        "networks": [ctx.network_name],
    }

    return Fragment(
        services={"lnd": service, "lnd-nodeinfo": nodeinfo},
        volumes={"lnd_data": {}},
        env={"LND_IMAGE": ctx.cfg.global_.lnd_image},
    )
