"""Builder for the standalone LND node(s).

The primary node (``lnd``) is used by Cashu and general dev work; it connects to
bitcoind over the internal compose network (RPC + ZMQ). On networks Argus mines
(regtest / custom-signet) a **second** node (``lnd2``) can be deployed, and the
two are auto-funded and wired together with channels at startup (see the
``lnd-setup`` funding sidecar and the ``lnd-channels`` opener).

Wallets auto-initialise (``noseedbackup``) so the stack comes up unattended —
acceptable for testnets, never for mainnet. P2P is published publicly; gRPC and
REST are bound to 127.0.0.1 (closed to the internet).

Bitcart runs its *own* LND (a separate phase); these are separate nodes.
"""

from __future__ import annotations

from dataclasses import dataclass

from ..constants import (
    CHAIN_INTERNAL_PORTS,
    LND_CHANNEL_CORE_RESERVE_BTC,
    LND_INTERNAL_PORTS,
    LND_NETWORK_KEY,
    ZMQ_BLOCK_INTERNAL,
    ZMQ_TX_INTERNAL,
)
from ..context import BuildContext, Fragment


@dataclass(frozen=True)
class _Node:
    """One LND node's identity within a network's compose project."""

    service: str  # compose service / DNS name ("lnd" or "lnd2")
    alias: str  # gossip alias (<=32 bytes)
    color: str  # gossip color (#rrggbb)
    confdir: str  # output subdir holding lnd.conf ("lnd" / "lnd2")
    volume: str  # data volume name ("lnd_data" / "lnd2_data")
    p2p_key: str  # ctx.ports key for the public P2P host port
    rest_key: str
    grpc_key: str


def _sanitize_arg(arg: str) -> str:
    """Reject newlines in operator-supplied LND args (defense against injection)."""
    if "\n" in arg or "\r" in arg:
        raise ValueError(f"lnd extra_arg contains a newline: {arg!r}")
    return arg.strip()


def _nodes(ctx: BuildContext) -> list[_Node]:
    """The LND node(s) for this network (one, or two when secondary is on)."""
    net, spec = ctx.net, ctx.spec
    alias1 = net.lnd.name or (
        "argus1" if spec.supports_miner else f"argus-{ctx.net_key}"
    )
    nodes = [
        _Node(
            service="lnd",
            alias=alias1,
            color=net.lnd.color,
            confdir="lnd",
            volume="lnd_data",
            p2p_key="lnd_p2p",
            rest_key="lnd_rest",
            grpc_key="lnd_grpc",
        )
    ]
    if net.lnd_secondary_enabled(spec):
        nodes.append(
            _Node(
                service="lnd2",
                alias=net.lnd.secondary.name,
                color=net.lnd.secondary.color,
                confdir="lnd2",
                volume="lnd2_data",
                p2p_key="lnd2_p2p",
                rest_key="lnd2_rest",
                grpc_key="lnd2_grpc",
            )
        )
    return nodes


def _render_conf(ctx: BuildContext, node: _Node) -> str:
    spec = ctx.spec
    net = ctx.net
    chain = spec.chain
    if chain not in LND_NETWORK_KEY:
        raise NotImplementedError(f"LND network mapping missing for chain {chain!r}")

    rpc_internal = CHAIN_INTERNAL_PORTS[chain]["rpc"]
    challenge = net.signet_challenge or spec.default_signet_challenge
    p = LND_INTERNAL_PORTS

    lines: list[str] = [
        "# Generated by Bitcoin Argus — do not edit by hand.",
        "[Application Options]",
        f"alias={node.alias}",
        f"color={node.color}",
        "debuglevel=info",
        # Unattended wallet init/unlock — fine for testnets only.
        "noseedbackup=true",
        f"listen=0.0.0.0:{p['p2p']}",
        f"rpclisten=0.0.0.0:{p['grpc']}",
        f"restlisten=0.0.0.0:{p['rest']}",
        # Make the TLS cert valid for in-container/loopback clients (Cashu, the
        # node-info + channel sidecars) that reach the node by its service name.
        f"tlsextradomain={node.service}",
        # Channel-friendliness: accept spontaneous payments and (optionally) make
        # the node discoverable + open to large/small channels from peers.
        "accept-keysend=true",
        "accept-amp=true",
    ]
    if net.lnd.advertise_external_ip:
        # Advertise a reachable address in gossip so peers can auto-connect and
        # open channels to us, instead of needing the URI hand-fed.
        lines.append(f"externalip={ctx.cfg.global_.hostname}:{ctx.ports[node.p2p_key]}")
    if net.lnd.min_chan_size is not None:
        lines.append(f"minchansize={net.lnd.min_chan_size}")
    if net.lnd.auto_compact:
        # Disk hygiene: compact channel.db on startup + drop canceled invoices.
        lines += [
            "gc-canceled-invoices-on-startup=true",
            "gc-canceled-invoices-on-the-fly=true",
            "db.bolt.auto-compact=true",
            "db.bolt.auto-compact-min-age=168h0m0s",
        ]
    if net.lnd_wumbo_enabled(spec):
        # Namespaced option: its own [protocol] section, and the key keeps the
        # full dotted name (same convention as bitcoin.* under [Bitcoin] below).
        lines += ["", "[protocol]", "protocol.wumbo-channels=true"]
    lines += [
        "",
        "[Bitcoin]",
        "bitcoin.active=true",
        f"bitcoin.{LND_NETWORK_KEY[chain]}=true",
        "bitcoin.node=bitcoind",
    ]
    if spec.is_signet and challenge:
        lines.append(f"bitcoin.signetchallenge={challenge}")
        for n in (*spec.default_addnodes, *net.addnode):
            lines.append(f"bitcoin.signetseednode={n}")

    lines += [
        "",
        "[Bitcoind]",
        f"bitcoind.rpchost=bitcoind:{rpc_internal}",
        f"bitcoind.rpcuser={ctx.secrets['RPC_USER']}",
        f"bitcoind.rpcpass={ctx.secrets['RPC_PASSWORD']}",
        f"bitcoind.zmqpubrawblock=tcp://bitcoind:{ZMQ_BLOCK_INTERNAL}",
        f"bitcoind.zmqpubrawtx=tcp://bitcoind:{ZMQ_TX_INTERNAL}",
    ]
    return "\n".join(lines) + "\n"


def _node_service(ctx: BuildContext, node: _Node) -> dict:
    p = LND_INTERNAL_PORTS
    lnd_net = LND_NETWORK_KEY[ctx.spec.chain]
    lnddir = "/home/lnd/.lnd"
    command = [f"--configfile=/etc/lnd/{node.confdir}.conf"] + [
        _sanitize_arg(a) for a in ctx.net.lnd.extra_args
    ]
    service = {
        "image": "${LND_IMAGE}",
        "container_name": f"{ctx.project}-{node.service}",
        "restart": "unless-stopped",
        "depends_on": {"bitcoind": {"condition": "service_healthy"}},
        "command": command,
        "volumes": [
            f"{node.volume}:{lnddir}",
            f"./{node.confdir}/lnd.conf:/etc/lnd/{node.confdir}.conf:ro",
        ],
        "ports": [
            # P2P is PUBLIC; gRPC + REST are closed (loopback only).
            f"{ctx.ports[node.p2p_key]}:{p['p2p']}",
            f"127.0.0.1:{ctx.ports[node.grpc_key]}:{p['grpc']}",
            f"127.0.0.1:{ctx.ports[node.rest_key]}:{p['rest']}",
        ],
        "networks": [ctx.network_name],
        "healthcheck": {
            "test": [
                "CMD-SHELL",
                f"lncli --lnddir={lnddir} --network={lnd_net} getinfo "
                ">/dev/null 2>&1 || exit 1",
            ],
            "interval": "20s",
            "timeout": "10s",
            "retries": 15,
            "start_period": "30s",
        },
    }
    if ctx.net.lnd.extra_env:
        service["environment"] = dict(ctx.net.lnd.extra_env)
    return service


# Run from a mounted file (not an inline entrypoint) so Docker Compose's variable
# interpolation never mangles the shell ``$i`` / ``$A`` / ``$(...)`` references.
_NODEINFO_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — record LND identity pubkey (+ funding address).
set -u
OUT="${LNDDIR}/argus_nodeinfo.json"
ADDR="${LNDDIR}/argus_addr.txt"
L="lncli --lnddir=${LNDDIR} --network=${NET} --rpcserver=${RPCSERVER}"
i=0
while [ $i -lt 120 ]; do
  if $L getinfo > "$OUT" 2>/dev/null && [ -s "$OUT" ]; then
    if [ "${WRITE_ADDR}" = "1" ] && [ ! -s "$ADDR" ]; then
      A=$($L newaddress p2wkh 2>/dev/null \
          | grep -o '"address": *"[^"]*"' | cut -d'"' -f4)
      [ -n "$A" ] && printf '%s' "$A" > "$ADDR"
    fi
    exit 0
  fi
  i=$((i+1)); sleep 5
done
exit 1
"""


def _nodeinfo_service(ctx: BuildContext, node: _Node, write_addr: bool) -> dict:
    """One-shot sidecar: once LND is healthy, record its identity pubkey (and,
    when channels are enabled, a fresh funding address) into the data volume.

    The dashboard reads the pubkey (read-only, via the Docker API) to show the
    node's connection URI; the ``lnd-setup`` funding sidecar reads the address to
    send the node its initial on-chain coins.
    """
    p = LND_INTERNAL_PORTS
    lnddir = "/home/lnd/.lnd"
    return {
        "image": "${LND_IMAGE}",
        "container_name": f"{ctx.project}-{node.service}-nodeinfo",
        "restart": "on-failure",
        "depends_on": {node.service: {"condition": "service_healthy"}},
        "entrypoint": ["/bin/sh", "/scripts/nodeinfo.sh"],
        "environment": {
            "LNDDIR": lnddir,
            "NET": LND_NETWORK_KEY[ctx.spec.chain],
            "RPCSERVER": f"{node.service}:{p['grpc']}",
            "WRITE_ADDR": "1" if write_addr else "0",
        },
        "volumes": [
            f"{node.volume}:{lnddir}",
            f"./{node.confdir}/nodeinfo.sh:/scripts/nodeinfo.sh:ro",
        ],
        "networks": [ctx.network_name],
    }


# ---------------------------------------------------------------------------
# Auto-funding + channel orchestration (regtest / custom-signet only).
# ---------------------------------------------------------------------------

_SETUP_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — fund both LND nodes' on-chain wallets.
set -eu

CLI="bitcoin-cli ${CHAIN_FLAG} -rpcconnect=${RPC_CONNECT} -rpcport=${RPC_PORT} \
-rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD}"
WCLI="${CLI} -rpcwallet=${FUNDING_WALLET}"
STATE=/state
A1F=/lnd1/argus_addr.txt
A2F=/lnd2/argus_addr.txt

if [ -f "${STATE}/funded" ]; then
  echo "[lnd-setup] already funded; nothing to do"; exit 0
fi

echo "[lnd-setup] waiting for bitcoind RPC..."
until $CLI getblockchaininfo >/dev/null 2>&1; do sleep 2; done

echo "[lnd-setup] waiting for funding wallet '${FUNDING_WALLET}'..."
until $WCLI getwalletinfo >/dev/null 2>&1; do
  $CLI loadwallet "${FUNDING_WALLET}" >/dev/null 2>&1 || true
  sleep 3
done

echo "[lnd-setup] waiting for both LND funding addresses..."
until [ -s "$A1F" ] && [ -s "$A2F" ]; do sleep 3; done
A1=$(cat "$A1F"); A2=$(cat "$A2F")

NEED=$(awk "BEGIN{print 2*${FUND_BTC}+${RESERVE_BTC}}")
echo "[lnd-setup] need >= ${NEED} BTC spendable in ${FUNDING_WALLET}; addrs ${A1} ${A2}"

enough() { awk "BEGIN{exit !($($WCLI getbalance) >= ${NEED})}"; }

if [ "${CAN_MINE}" = "1" ]; then
  MADDR=$($WCLI getnewaddress)
  while ! enough; do
    echo "[lnd-setup] mining to mature funds (balance $($WCLI getbalance))"
    $CLI generatetoaddress 20 "$MADDR" >/dev/null
  done
else
  echo "[lnd-setup] waiting for the signer to accumulate matured coins..."
  while ! enough; do echo "  balance $($WCLI getbalance)"; sleep 10; done
fi

echo "[lnd-setup] funding ${FUND_BTC} BTC to each node"
$WCLI -named sendtoaddress address="$A1" amount=${FUND_BTC} fee_rate=2 >/dev/null
$WCLI -named sendtoaddress address="$A2" amount=${FUND_BTC} fee_rate=2 >/dev/null

if [ "${CAN_MINE}" = "1" ]; then
  echo "[lnd-setup] confirming funding transactions"
  $CLI generatetoaddress 6 "$MADDR" >/dev/null
fi

touch "${STATE}/funded"
echo "[lnd-setup] funding complete (channels confirm via the steady-state miner)"
"""

_CHANNELS_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — open channels between the two LND nodes.
set -eu

GRPC=__GRPC__
P2P=__P2P__
L1="lncli --network=${NET} --rpcserver=lnd:${GRPC} --lnddir=/lnd1"
L2="lncli --network=${NET} --rpcserver=lnd2:${GRPC} --lnddir=/lnd2"
STATE=/state

echo "[lnd-channels] waiting for funding to complete..."
until [ -f "${STATE}/funded" ]; do sleep 3; done
until $L1 getinfo >/dev/null 2>&1; do sleep 3; done
until $L2 getinfo >/dev/null 2>&1; do sleep 3; done

pk()  { eval "\\$$1 getinfo" | grep -o '"identity_pubkey": *"[0-9a-f]*"' \
        | grep -oE '[0-9a-f]{66}'; }
conf() { eval "\\$$1 walletbalance" | grep -o '"confirmed_balance": *"[0-9]*"' \
        | grep -oE '[0-9]+' | head -1; }

P1=$(pk L1); P2=$(pk L2)
echo "[lnd-channels] node1=$P1 node2=$P2"

echo "[lnd-channels] waiting for confirmed on-chain funds (>= ${CHAN_SAT} sat)..."
until [ "$(conf L1)" -ge "${CHAN_SAT}" ] 2>/dev/null; do sleep 5; done
until [ "$(conf L2)" -ge "${CHAN_SAT}" ] 2>/dev/null; do sleep 5; done

# Two channels — one funded by each node. A per-direction marker makes this
# idempotent (a peer-presence check can't, since after the first open BOTH nodes
# already list a channel to each other).
open_dir() {  # caller_var marker peer_pubkey peer_host
  if [ -f "${STATE}/$2" ]; then echo "[lnd-channels] $2 already opened"; return 0; fi
  echo "[lnd-channels] $1 connect $3@$4"
  eval "\\$$1 connect $3@$4" >/dev/null 2>&1 || true
  echo "[lnd-channels] $1 openchannel ${CHAN_SAT} sat -> $3"
  eval "\\$$1 openchannel --node_key=$3 --local_amt=${CHAN_SAT}"
  touch "${STATE}/$2"
}

open_dir L1 chan_l1 "$P2" "lnd2:${P2P}"
open_dir L2 chan_l2 "$P1" "lnd:${P2P}"

touch "${STATE}/channels"
echo "[lnd-channels] channel setup complete"
"""


def _setup_services(ctx: BuildContext) -> dict[str, dict]:
    """The funding + channel-opening sidecars (only when channels are enabled).

    ``lnd-setup`` runs in the bitcoind image (it needs bitcoin-cli to mine/fund);
    ``lnd-channels`` runs in the LND image (it needs lncli to open channels). They
    coordinate through marker files in the shared ``lnd_setup_state`` volume.
    """
    chain = ctx.spec.chain
    p = LND_INTERNAL_PORTS
    rpc_internal = CHAIN_INTERNAL_PORTS[chain]["rpc"]
    can_mine = chain == "regtest"
    funding_wallet = "miner" if chain == "regtest" else "signer"
    chan_sat = round(ctx.net.lnd.channels.channel_btc * 1e8)

    conf_dir = ctx.out_dir / "lnd_setup"
    conf_dir.mkdir(parents=True, exist_ok=True)
    (conf_dir / "setup.sh").write_text(_SETUP_SH)
    channels_sh = (
        _CHANNELS_SH.replace("__GRPC__", str(p["grpc"])).replace("__P2P__", str(p["p2p"]))
    )
    (conf_dir / "channels.sh").write_text(channels_sh)

    lnd_setup = {
        "image": "${BITCOIND_IMAGE}",
        "container_name": f"{ctx.project}-lnd-setup",
        # Root so it can write the shared-state markers (the state volume is
        # root-owned and shared with the LND-image channel sidecar, whose UID
        # differs). It only mines/funds via RPC + reads the LND addr files (ro).
        "user": "0:0",
        "restart": "on-failure",
        "depends_on": {
            "bitcoind": {"condition": "service_healthy"},
            "lnd": {"condition": "service_healthy"},
            "lnd2": {"condition": "service_healthy"},
        },
        "entrypoint": ["/bin/sh", "/scripts/setup.sh"],
        "environment": {
            "CHAIN_FLAG": "-regtest" if chain == "regtest" else "-signet",
            "CAN_MINE": "1" if can_mine else "0",
            "FUNDING_WALLET": funding_wallet,
            "RPC_CONNECT": "bitcoind",
            "RPC_PORT": str(rpc_internal),
            "RPC_USER": "${RPC_USER}",
            "RPC_PASSWORD": "${RPC_PASSWORD}",
            "FUND_BTC": str(ctx.net.lnd.channels.fund_btc),
            "RESERVE_BTC": str(LND_CHANNEL_CORE_RESERVE_BTC),
        },
        "volumes": [
            "./lnd_setup/setup.sh:/scripts/setup.sh:ro",
            "lnd_data:/lnd1:ro",
            "lnd2_data:/lnd2:ro",
            "lnd_setup_state:/state",
        ],
        "networks": [ctx.network_name],
    }

    lnd_channels = {
        "image": "${LND_IMAGE}",
        "container_name": f"{ctx.project}-lnd-channels",
        # Root so it can write the shared-state markers (see lnd-setup). lncli
        # only reads each node's cert/macaroon (mounted read-only).
        "user": "0:0",
        "restart": "on-failure",
        "depends_on": {
            "lnd": {"condition": "service_healthy"},
            "lnd2": {"condition": "service_healthy"},
            "lnd-setup": {"condition": "service_started"},
        },
        "entrypoint": ["/bin/sh", "/scripts/channels.sh"],
        "environment": {
            "NET": LND_NETWORK_KEY[chain],
            "CHAN_SAT": str(chan_sat),
        },
        "volumes": [
            "./lnd_setup/channels.sh:/scripts/channels.sh:ro",
            "lnd_data:/lnd1:ro",
            "lnd2_data:/lnd2:ro",
            "lnd_setup_state:/state",
        ],
        "networks": [ctx.network_name],
    }
    return {"lnd-setup": lnd_setup, "lnd-channels": lnd_channels}


def build_lnd(ctx: BuildContext) -> Fragment:
    nodes = _nodes(ctx)
    channels_on = ctx.net.lnd_channels_enabled(ctx.spec)

    services: dict[str, dict] = {}
    volumes: dict[str, dict] = {}
    for node in nodes:
        conf_dir = ctx.out_dir / node.confdir
        conf_dir.mkdir(parents=True, exist_ok=True)
        (conf_dir / "lnd.conf").write_text(_render_conf(ctx, node))
        (conf_dir / "nodeinfo.sh").write_text(_NODEINFO_SH)
        services[node.service] = _node_service(ctx, node)
        services[f"{node.service}-nodeinfo"] = _nodeinfo_service(
            ctx, node, write_addr=channels_on
        )
        volumes[node.volume] = {}

    if channels_on:
        services.update(_setup_services(ctx))
        volumes["lnd_setup_state"] = {}

    return Fragment(
        services=services,
        volumes=volumes,
        env={"LND_IMAGE": ctx.cfg.global_.lnd_image},
    )
