"""Builder for the regtest block-producing sidecar.

Mines the initial coinbase-maturity blocks, then produces one block on a fixed
interval (default 60s). Currently regtest-only; signet (custom-signet) mining
needs the signet miner tool and is a later phase — config validation enforces
this so an unsupported network never reaches here.
"""

from __future__ import annotations

from ..constants import CHAIN_INTERNAL_PORTS
from ..context import BuildContext, Fragment

# Map each supported chain to the bitcoin-cli network flag.
_CHAIN_FLAG = {"regtest": "-regtest"}

_MINE_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — regtest block producer.
set -eu

CLI="bitcoin-cli ${CLI_CHAIN_FLAG} -rpcconnect=${RPC_CONNECT} -rpcport=${RPC_PORT} \
-rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD}"

echo "[miner] waiting for bitcoind RPC..."
until $CLI getblockchaininfo >/dev/null 2>&1; do sleep 2; done

# Ensure a loaded wallet to mine into.
$CLI -named createwallet wallet_name=miner load_on_startup=true >/dev/null 2>&1 \
  || $CLI loadwallet miner >/dev/null 2>&1 || true
ADDR=$($CLI getnewaddress)
echo "[miner] mining to ${ADDR}"

HEIGHT=$($CLI getblockcount)
if [ "$HEIGHT" -lt "$INITIAL_BLOCKS" ]; then
  NEED=$((INITIAL_BLOCKS - HEIGHT))
  echo "[miner] generating $NEED maturity block(s)"
  $CLI generatetoaddress "$NEED" "$ADDR" >/dev/null
fi

echo "[miner] steady state: 1 block every ${INTERVAL}s"
while true; do
  $CLI generatetoaddress 1 "$ADDR" >/dev/null
  sleep "$INTERVAL"
done
"""


def build_miner(ctx: BuildContext) -> Fragment:
    chain = ctx.spec.chain
    if chain not in _CHAIN_FLAG:  # defensive; config validation should prevent this
        raise NotImplementedError(f"miner not implemented for chain {chain!r}")

    script_dir = ctx.out_dir / "miner"
    script_dir.mkdir(parents=True, exist_ok=True)
    (script_dir / "mine.sh").write_text(_MINE_SH)

    service = {
        "image": "${BITCOIND_IMAGE}",
        "container_name": f"{ctx.project}-miner",
        "restart": "unless-stopped",
        "depends_on": {"bitcoind": {"condition": "service_healthy"}},
        "entrypoint": ["/bin/sh", "/scripts/mine.sh"],
        "volumes": ["./miner/mine.sh:/scripts/mine.sh:ro"],
        "environment": {
            "CLI_CHAIN_FLAG": _CHAIN_FLAG[chain],
            "RPC_CONNECT": "bitcoind",
            "RPC_PORT": str(CHAIN_INTERNAL_PORTS[chain]["rpc"]),
            "RPC_USER": "${RPC_USER}",
            "RPC_PASSWORD": "${RPC_PASSWORD}",
            "INTERVAL": "${MINER_INTERVAL}",
            "INITIAL_BLOCKS": "${MINER_INITIAL_BLOCKS}",
        },
        "networks": [ctx.network_name],
    }

    return Fragment(
        services={"miner": service},
        env={
            "MINER_INTERVAL": str(ctx.net.miner.block_interval_seconds),
            "MINER_INITIAL_BLOCKS": str(ctx.net.miner.initial_blocks),
        },
    )
