"""Builder for the block-producing sidecar.

Two flavours, both producing the initial coinbase-maturity blocks and then one
block per interval (default 60s):

* **regtest** — a tiny shell loop calling ``generatetoaddress``.
* **custom signet** — a container built from the stock bitcoind image plus
  Python and the vendored Bitcoin Core signet miner (see ``argus/signet_miner``).
  It signs blocks with the auto-generated challenge key and grinds at minimum
  signet difficulty.

Config validation restricts the miner to these chains, so an unsupported network
never reaches here.
"""

from __future__ import annotations

import math
import shutil
from pathlib import Path

from ..constants import (
    CHAIN_INTERNAL_PORTS,
    COINBASE_MATURITY,
    EARLY_BLOCK_SUBSIDY_BTC,
    LND_CHANNEL_CORE_RESERVE_BTC,
)
from ..context import BuildContext, Fragment

# Map each supported chain to the bitcoin-cli network flag.
_CHAIN_FLAG = {"regtest": "-regtest"}


def _initial_blocks(ctx: BuildContext) -> int:
    """Effective initial maturity blocks.

    When auto-channels are on, the funding wallet must hold enough *matured*
    coinbase to send each node ``fund_btc`` and keep the core reserve, so we bump
    the initial height to mature enough coinbases (a coinbase at height h matures
    at h+100). For custom-signet this is essential — the signer is the only block
    producer; on regtest the setup sidecar can also mine on demand.
    """
    configured = ctx.net.miner.initial_blocks
    if not ctx.net.lnd_channels_enabled(ctx.spec):
        return configured
    need_btc = 2 * ctx.net.lnd.channels.fund_btc + LND_CHANNEL_CORE_RESERVE_BTC
    coinbases = math.ceil(need_btc / EARLY_BLOCK_SUBSIDY_BTC)
    funding_min = COINBASE_MATURITY + coinbases + 3  # +3 margin
    return max(configured, funding_min)

_SIGNET_MINER_SRC = Path(__file__).resolve().parent.parent / "signet_miner"

_MINE_SH = """\
#!/bin/sh
# Generated by Bitcoin Argus — regtest block producer.
set -eu

CLI="bitcoin-cli ${CLI_CHAIN_FLAG} -rpcconnect=${RPC_CONNECT} -rpcport=${RPC_PORT} \
-rpcuser=${RPC_USER} -rpcpassword=${RPC_PASSWORD}"

echo "[miner] waiting for bitcoind RPC..."
until $CLI getblockchaininfo >/dev/null 2>&1; do sleep 2; done

# Ensure a loaded wallet to mine into.
$CLI -named createwallet wallet_name=miner load_on_startup=true >/dev/null 2>&1 \
  || $CLI loadwallet miner >/dev/null 2>&1 || true
ADDR=$($CLI getnewaddress)
echo "[miner] mining to ${ADDR}"

HEIGHT=$($CLI getblockcount)
if [ "$HEIGHT" -lt "$INITIAL_BLOCKS" ]; then
  NEED=$((INITIAL_BLOCKS - HEIGHT))
  echo "[miner] generating $NEED maturity block(s)"
  $CLI generatetoaddress "$NEED" "$ADDR" >/dev/null
fi

echo "[miner] steady state: 1 block every ${INTERVAL}s"
while true; do
  $CLI generatetoaddress 1 "$ADDR" >/dev/null
  sleep "$INTERVAL"
done
"""


def _build_signet_miner(ctx: BuildContext) -> Fragment:
    """A built-image miner that signs + mines a self-mined custom signet."""
    miner_dir = ctx.out_dir / "miner"
    if miner_dir.exists():
        shutil.rmtree(miner_dir)
    shutil.copytree(
        _SIGNET_MINER_SRC,
        miner_dir,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )

    rpc_internal = CHAIN_INTERNAL_PORTS["signet"]["rpc"]
    service = {
        "build": {
            "context": "./miner",
            "args": {"BITCOIND_IMAGE": "${BITCOIND_IMAGE}"},
        },
        "image": f"{ctx.project}-signet-miner:local",
        "container_name": f"{ctx.project}-miner",
        "restart": "unless-stopped",
        "depends_on": {"bitcoind": {"condition": "service_healthy"}},
        "environment": {
            "RPC_CONNECT": "bitcoind",
            "RPC_PORT": str(rpc_internal),
            "RPC_USER": "${RPC_USER}",
            "RPC_PASSWORD": "${RPC_PASSWORD}",
            "SIGNET_MINER_WIF": "${SIGNET_MINER_WIF}",
            "INTERVAL": "${MINER_INTERVAL}",
            "INITIAL_BLOCKS": "${MINER_INITIAL_BLOCKS}",
        },
        "networks": [ctx.network_name],
    }
    return Fragment(
        services={"miner": service},
        env={
            "MINER_INTERVAL": str(ctx.net.miner.block_interval_seconds),
            "MINER_INITIAL_BLOCKS": str(_initial_blocks(ctx)),
            "SIGNET_MINER_WIF": ctx.secrets["SIGNET_MINER_WIF"],
        },
    )


def build_miner(ctx: BuildContext) -> Fragment:
    chain = ctx.spec.chain
    if chain == "signet":
        return _build_signet_miner(ctx)
    if chain not in _CHAIN_FLAG:  # defensive; config validation should prevent this
        raise NotImplementedError(f"miner not implemented for chain {chain!r}")

    script_dir = ctx.out_dir / "miner"
    script_dir.mkdir(parents=True, exist_ok=True)
    (script_dir / "mine.sh").write_text(_MINE_SH)

    service = {
        "image": "${BITCOIND_IMAGE}",
        "container_name": f"{ctx.project}-miner",
        "restart": "unless-stopped",
        "depends_on": {"bitcoind": {"condition": "service_healthy"}},
        "entrypoint": ["/bin/sh", "/scripts/mine.sh"],
        "volumes": ["./miner/mine.sh:/scripts/mine.sh:ro"],
        "environment": {
            "CLI_CHAIN_FLAG": _CHAIN_FLAG[chain],
            "RPC_CONNECT": "bitcoind",
            "RPC_PORT": str(CHAIN_INTERNAL_PORTS[chain]["rpc"]),
            "RPC_USER": "${RPC_USER}",
            "RPC_PASSWORD": "${RPC_PASSWORD}",
            "INTERVAL": "${MINER_INTERVAL}",
            "INITIAL_BLOCKS": "${MINER_INITIAL_BLOCKS}",
        },
        "networks": [ctx.network_name],
    }

    return Fragment(
        services={"miner": service},
        env={
            "MINER_INTERVAL": str(ctx.net.miner.block_interval_seconds),
            "MINER_INITIAL_BLOCKS": str(_initial_blocks(ctx)),
        },
    )
